'use strict';

const state={me:null,csrf:'',cases:[],selected:null};
const $=(selector)=>document.querySelector(selector);
const esc=(value)=>String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const date=(value)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Never';
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=error?'show error':'show';setTimeout(()=>el.className='',3500)}
async function api(url,options={}){const response=await fetch(url,options);const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Request failed.');return body}
function avatar(user){return user?.avatar?'https://cdn.discordapp.com/avatars/'+user.id+'/'+user.avatar+'.png?size=64':'/bot-avatar.png'}
function statusOf(item){const latest=item.appeals[0];if(item.case.status==='pardoned'||latest?.status==='accepted')return{label:'[RESOLVED]',class:'resolved'};if(['pending','processing'].includes(latest?.status))return{label:'[PENDING]',class:'pending'};if(!item.case.appealable)return{label:'[UNAPPEALABLE]',class:'blocked'};if(!item.eligibility.allowed)return{label:'['+String(item.eligibility.code||'BLOCKED').toUpperCase()+']',class:'blocked'};return{label:'APPEALABLE',class:''}}
function renderAccount(){const user=state.me;if(!user){$('#account').innerHTML='';return}$('#account').innerHTML='<div class="account"><img src="'+esc(avatar(user))+'" alt=""><span>'+esc(user.globalName||user.username)+'</span><button id="logout">Log out</button></div>';$('#logout').onclick=async()=>{await fetch('/auth/logout',{method:'POST'});location.reload()}}
function renderList(){const list=$('#case-list');$('#case-count').textContent=state.cases.length+' moderation case'+(state.cases.length===1?'':'s');if(!state.cases.length){list.innerHTML='<div class="empty">No moderation cases</div>';$('#case-detail').innerHTML='<div class="empty">No cases available</div>';return}list.innerHTML=state.cases.map((item,index)=>{const status=statusOf(item);return '<button class="case-card '+(status.class==='blocked'?'disabled ':'')+(state.selected===index?'active':'')+'" data-index="'+index+'"><div class="case-card-top"><span class="case-id">'+esc(item.case.id)+'</span><span class="badge '+status.class+'">'+esc(status.label)+'</span></div><div class="guild">'+esc(item.guildName)+'</div><div class="case-meta"><span>'+esc(item.case.type.replace('_',' '))+'</span><span>'+esc(date(item.case.createdAt))+'</span></div></button>'}).join('');list.querySelectorAll('.case-card').forEach(button=>button.onclick=()=>{state.selected=Number(button.dataset.index);renderList();renderDetail()})}
function info(label,value,wide=false){return '<div class="info '+(wide?'wide':'')+'"><span class="label">'+esc(label)+'</span><div class="value">'+esc(value||'None')+'</div></div>'}
function fieldHtml(field){const id='field-'+field.id;const required=field.required?' required':'';const note=field.description?'<small>'+esc(field.description)+'</small>':'';if(field.type==='text')return '<div class="field"><label for="'+id+'">'+esc(field.label)+(field.required?' *':'')+'</label>'+note+(field.style==='paragraph'?'<textarea':'<input type="text"')+' id="'+id+'" data-field="'+esc(field.id)+'" placeholder="'+esc(field.placeholder||'')+'" minlength="'+field.minLength+'" maxlength="'+field.maxLength+'"'+required+(field.style==='paragraph'?'></textarea>':'>')+'</div>';if(field.type==='number')return '<div class="field"><label for="'+id+'">'+esc(field.label)+(field.required?' *':'')+'</label>'+note+'<input type="number" id="'+id+'" data-field="'+esc(field.id)+'" placeholder="'+esc(field.placeholder||'')+'" step="'+field.step+'" '+(field.minimum==null?'':'min="'+field.minimum+'"')+' '+(field.maximum==null?'':'max="'+field.maximum+'"')+required+'></div>';if(field.type==='choice')return '<fieldset class="field" data-field="'+esc(field.id)+'"><legend>'+esc(field.label)+(field.required?' *':'')+'</legend>'+note+field.options.map(option=>'<label class="choice"><input type="'+(field.multiple?'checkbox':'radio')+'" name="'+id+'" value="'+esc(option.id)+'"><span>'+esc(option.label)+'</span></label>').join('')+'</fieldset>';if(field.type==='checkbox')return '<div class="field">'+note+'<label class="choice"><input type="checkbox" data-field="'+esc(field.id)+'" '+(field.default?'checked':'')+required+'><span>'+esc(field.label)+(field.required?' *':'')+'</span></label></div>';return '<div class="field"><label for="'+id+'">'+esc(field.label)+(field.required?' *':'')+'</label>'+note+'<input type="file" id="'+id+'" data-field="'+esc(field.id)+'" '+(field.maxFiles>1?'multiple':'')+(field.allowedExtensions?.length?' accept="'+field.allowedExtensions.map(x=>'.'+x).join(',')+'"':'')+required+'><small>Up to '+field.maxFiles+' file'+(field.maxFiles===1?'':'s')+', '+field.maxFileSizeMb+' MB each</small></div>'}
function blockText(item){const code=item.eligibility.code;if(code==='unappealable')return 'This case is not appealable.';if(code==='pending')return 'An appeal is awaiting review.';if(code==='resolved')return 'This case has been resolved.';if(code==='maximum')return 'The submission limit has been reached.';if(code==='cooldown')return 'Another appeal can be submitted after '+date(item.eligibility.retryAt)+'.';if(code==='disabled')return 'Appeals are not available for this server.';return 'This case cannot receive an appeal.'}
function historyHtml(item){if(!item.appeals.length)return '';return '<section class="history"><h3>Appeal history</h3>'+item.appeals.map(a=>'<div class="history-item '+esc(a.status)+'"><strong>'+esc(a.id)+' · '+esc(a.status.toUpperCase())+'</strong><div class="guild">'+esc(date(a.createdAt))+'</div>'+(a.decisionReason?'<p>'+esc(a.decisionReason)+'</p>':'')+(a.attachments?.length?'<div class="files">'+a.attachments.map(file=>'<a class="file" href="'+esc(file.url)+'" target="_blank" rel="noopener">'+esc(file.name)+'</a>').join('')+'</div>':'')+'</div>').join('')+'</section>'}
function renderDetail(){const item=state.cases[state.selected];if(!item)return;const c=item.case;const author=c.author?(c.author.globalName||c.author.username)+' ('+c.author.id+')':c.authorId||'Unknown';const evidence=c.attachments?.length?'<div class="files">'+c.attachments.map(file=>'<a class="file" href="'+esc(file.url)+'" target="_blank" rel="noopener">'+esc(file.name)+'</a>').join('')+'</div>':c.evidenceUrl?'<a class="file" href="'+esc(c.evidenceUrl)+'" target="_blank" rel="noopener">Evidence link</a>':'None';const form=item.eligibility.allowed?'<form id="appeal-form" class="appeal-form"><h2>Submit appeal</h2>'+item.form.map(fieldHtml).join('')+'<button class="primary" type="submit">Submit appeal</button></form>':'<div class="appeal-form"><div class="blocked-message">'+esc(blockText(item))+'</div></div>';$('#case-detail').innerHTML='<div class="detail-head"><div><h2>'+esc(c.id)+'</h2><p>'+esc(item.guildName)+'</p></div><span class="badge '+statusOf(item).class+'">'+esc(statusOf(item).label)+'</span></div><div class="info-grid">'+info('Author',author)+info('Punishment',c.type.replace('_',' '))+info('Issued',date(c.createdAt))+info('Expires',date(c.expiresAt))+info('Reason',c.reason,true)+info('Evidence','',true)+info('Moderator note',c.publicNote||'None',true)+'</div>'+form+historyHtml(item);const evidenceInfo=$('#case-detail .info:nth-last-child(2) .value');if(evidenceInfo)evidenceInfo.innerHTML=evidence;const formEl=$('#appeal-form');if(formEl)formEl.onsubmit=(event)=>submit(event,item)}
async function submit(event,item){event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const answers={};const data=new FormData();for(const field of item.form){if(field.type==='choice'){answers[field.id]=[...form.querySelectorAll('[name="field-'+CSS.escape(field.id)+'"]:checked')].map(el=>el.value);if(!field.multiple)answers[field.id]=answers[field.id][0]||''}else{const input=form.querySelector('[data-field="'+CSS.escape(field.id)+'"]');if(field.type==='file'){for(const file of input.files)data.append('file:'+field.id,file,file.name)}else if(field.type==='checkbox')answers[field.id]=input.checked;else answers[field.id]=input.value}}data.append('answers',JSON.stringify(answers));const button=form.querySelector('button[type="submit"]');button.disabled=true;try{await api('/api/appeal/guilds/'+item.guildId+'/cases/'+encodeURIComponent(item.case.id)+'/submissions',{method:'POST',headers:{'X-CSRF-Token':state.csrf},body:data});toast('Appeal submitted.');await loadCases()}catch(error){toast(error.message,true);button.disabled=false}}
async function loadCases(){const result=await api('/api/appeal/cases');state.cases=result.cases;state.selected=state.cases.length?Math.min(state.selected??0,state.cases.length-1):null;renderList();renderDetail()}
async function init(){try{const result=await api('/api/appeal/me');state.me=result.user;state.csrf=result.csrfToken||'';renderAccount();if(!state.me){$('#login').hidden=false;return}$('#app').hidden=false;await loadCases()}catch(error){toast(error.message,true)}}init();
