const fs = require('fs');
const path = require('path');
const { MessageFlags, SlashCommandBuilder } = require('discord.js');
const { FISH, FISH_BY_ID, RARITY_BUTTONS, RARITY_WEIGHTS, VARIANTS } = require('./Data/FishData');
const { ITEMS } = require('./Data/Item Data');
const weatherData = require('./Data/WeatherData');
const { ADMIN_WEATHER, FISH_EVENTS, GIANT_MUTATION } = require('./Data/FishingRuntimeData');

const COMPONENTS_V2_FLAG = MessageFlags.IsComponentsV2 ?? 32768;
const EPHEMERAL_FLAG = MessageFlags.Ephemeral ?? 64;
const WHITE = 0xffffff;
const GREEN = 0x57f287;
const RED = 0xed4245;
const YELLOW = 0xffd84d;
const BUTTON_SECONDARY = 2;
const BUTTON_DANGER = 4;
const LOCATION = 'Calm Fishing Lake';
const FISHING_CHANNEL_ID = '1506684299934437517';
const STORE_PATH = path.join(__dirname, '..', 'data', 'fishing-game.json');
const FISH_COIN = '<:CRFishCoin:1506701069990891751>';
const SPIN_FISH = '<a:SBSpinFish:1506656617469317251>';
const REEL_EMOJIS = ['\u{1f41f}', '\u{1f3a3}', '\u{1fa9d}', '\u{1fae7}', '\u{1f30a}', '\u{1f420}', '\u{1f421}', '\u{1f988}', '\u{1f991}', '\u{1f980}', '\u{1f41a}', '\u{1fa99}', '\u2b50', '\u{1f4a7}', '\u{1f340}'];
const RARITY_EMOJI = { common: '<:SBCommon:1506965202585780274>', uncommon: '<:SBUncommon:1506965215743447040>', rare: '<:SBRare:1506965211607994461>', epic: '<:SBEpic:1506965204624474153>', legendary: '<:SBLegendary:1506965206197207131>', mythical: '<:SBMythical:1506965209271762954>', secret: '<:SBSecret:1506965213881307186>' };

const activeGames = new Map();
const activeGameByUser = new Map();
let weatherTimerStarted = false;

function randomInt(min, max) { return Math.floor(Math.random() * ((max - min) + 1)) + min; }
function randomFloat(min, max) { return min + (Math.random() * (max - min)); }
function weightedPick(entries) { const valid = entries.filter((entry) => Number(entry.weight) > 0); const total = valid.reduce((sum, entry) => sum + Number(entry.weight), 0); if (total <= 0) return valid[0]?.value ?? null; let roll = Math.random() * total; for (const entry of valid) { roll -= Number(entry.weight); if (roll <= 0) return entry.value; } return valid[valid.length - 1]?.value ?? null; }
function normalizeId(value) { return String(value || '').trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, ''); }
function emptyState() { return { users: {}, weather: {}, forecasts: {}, events: { active: {} } }; }
function ensureStoreFile() { const dir = path.dirname(STORE_PATH); if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true }); if (!fs.existsSync(STORE_PATH)) fs.writeFileSync(STORE_PATH, JSON.stringify(emptyState(), null, 2), 'utf8'); }
function loadState() { ensureStoreFile(); try { return { ...emptyState(), ...JSON.parse(fs.readFileSync(STORE_PATH, 'utf8')) }; } catch { return emptyState(); } }
function saveState(state) { ensureStoreFile(); fs.writeFileSync(STORE_PATH, JSON.stringify({ ...emptyState(), ...state }, null, 2), 'utf8'); }
function getItemDefinition(itemId) { return ITEMS[itemId] || null; }
function getInventoryAmount(user, itemId) { return Math.max(0, Math.floor(Number(user.inventory?.[itemId]?.amount) || 0)); }
function normalizeRodDurabilities(user, itemId) { const item = getItemDefinition(itemId); const entry = user.inventory?.[itemId]; if (!item || item.type !== 'Gear/Tool' || !entry || typeof entry !== 'object') return; const amount = getInventoryAmount(user, itemId); if (item.durability === null) { entry.durability = null; delete entry.durabilities; return; } const fallback = Math.max(0, Math.floor(Number(entry.durability ?? item.durability) || item.durability)); entry.durabilities = Array.isArray(entry.durabilities) ? entry.durabilities.slice(0, amount) : [fallback]; entry.durabilities = entry.durabilities.map((durability) => Math.max(0, Math.floor(Number(durability) || item.durability))); while (entry.durabilities.length < amount) entry.durabilities.push(item.durability); entry.durability = entry.durabilities[0] ?? item.durability; }
function ensureUser(state, userId) { if (!state.users[userId]) state.users[userId] = { fishCoins: 0, inventory: {}, fishBarrel: [], equippedRodId: 'wooden_fishing_rod', equippedBaitId: null, location: LOCATION, fishCapacity: 10, fishIndex: {}, mutationIndex: {} }; const user = state.users[userId]; user.inventory = user.inventory && typeof user.inventory === 'object' ? user.inventory : {}; user.fishBarrel = Array.isArray(user.fishBarrel) ? user.fishBarrel : []; user.fishCoins = Math.max(0, Math.floor(Number(user.fishCoins) || 0)); user.fishCapacity = Math.max(10, Math.floor(Number(user.fishCapacity) || 10)); user.fishIndex = user.fishIndex && typeof user.fishIndex === 'object' ? user.fishIndex : {}; user.mutationIndex = user.mutationIndex && typeof user.mutationIndex === 'object' ? user.mutationIndex : {}; if (!user.inventory.wooden_fishing_rod) user.inventory.wooden_fishing_rod = { amount: 1, durability: null }; for (const itemId of Object.keys(user.inventory)) normalizeRodDurabilities(user, itemId); if (!user.equippedRodId || !getInventoryAmount(user, user.equippedRodId)) user.equippedRodId = 'wooden_fishing_rod'; return user; }
function getUser(userId) { const state = loadState(); const user = ensureUser(state, userId); saveState(state); return JSON.parse(JSON.stringify(user)); }
function updateUser(userId, updater) { const state = loadState(); const user = ensureUser(state, userId); const result = updater(user, state); saveState(state); return result ?? user; }
function cleanupEvents(state = loadState(), now = Date.now()) { state.events = state.events && typeof state.events === 'object' ? state.events : { active: {} }; state.events.active = state.events.active && typeof state.events.active === 'object' ? state.events.active : {}; for (const [eventId, active] of Object.entries(state.events.active)) if (!active || Number(active.endsAt) <= now || !FISH_EVENTS[eventId]) delete state.events.active[eventId]; return state.events.active; }
function activeEvents(state = loadState()) { return cleanupEvents(state); }
function hasEvent(state, eventId) { return Boolean(activeEvents(state)[eventId]); }
function weatherEmoji(name) { return ADMIN_WEATHER[name]?.emoji || weatherData.WEATHER_EMOJIS[name] || ''; }
function weatherEffects(name) { return { ...(weatherData.WEATHER_EFFECTS[name] || {}), ...(ADMIN_WEATHER[name] || {}) }; }
function seasonTime(now = new Date()) { const utc7 = now.getTime() + (7 * 60 * 60 * 1000); const day = Math.floor(utc7 / 86400000); const hour = Math.floor((utc7 % 86400000) / 3600000); const season = weatherData.SEASONS[Math.floor(day / 2) % weatherData.SEASONS.length]; const timeKey = ['Morning', 'Noon', 'Afternoon', 'Night'][Math.floor((hour % 12) / 3)]; return { season, time: { key: timeKey, emoji: weatherData.TIMES[timeKey] } }; }
function getCurrentWeather(state = loadState()) { const { season, time } = seasonTime(); const now = Date.now(); const slotStart = Math.floor(now / weatherData.WEATHER_DURATION_MS) * weatherData.WEATHER_DURATION_MS; const current = state.weather[LOCATION]; if (!current || Number(current.endsAt) <= now || (!current.manual && (current.season !== season.key || current.time !== time.key))) { const rolled = weatherData.rollWeather(season.key, time.key); state.weather[LOCATION] = { location: LOCATION, season: season.key, seasonEmoji: season.emoji, time: time.key, timeEmoji: time.emoji, weather: rolled.name, weatherEmoji: rolled.emoji || weatherEmoji(rolled.name), startedAt: slotStart, endsAt: slotStart + weatherData.WEATHER_DURATION_MS }; saveState(state); } else { current.season = season.key; current.seasonEmoji = season.emoji; current.time = time.key; current.timeEmoji = time.emoji; current.weatherEmoji = current.weatherEmoji || weatherEmoji(current.weather); } return state.weather[LOCATION]; }

function container(accent, components, files = []) { return { flags: COMPONENTS_V2_FLAG, files, components: [{ type: 17, accent_color: accent, components: components.filter(Boolean) }] }; }
function row(components) { return { type: 1, components }; }
function sep() { return { type: 14, divider: true, spacing: 1 }; }
function button(customId, label, style = BUTTON_SECONDARY, disabled = false) { return { type: 2, custom_id: customId, label, style, disabled }; }
function fishButton(userId) { return row([button(`fish:start:${userId}`, 'Fish')]); }
function actionSelect(userId, placeholder = 'Select an action', values = ['equipment', 'location']) { const labels = { fishing: 'Fishing', equipment: 'Equipments', location: 'Change Location' }; return row([{ type: 3, custom_id: `fish:action:${userId}`, placeholder, min_values: 1, max_values: 1, options: values.map((value) => ({ label: labels[value], value })) }]); }
function componentEmoji(emoji) { const match = String(emoji || '').match(/^<a?:([A-Za-z0-9_]+):(\d+)>$/); return match ? { name: match[1], id: match[2], animated: String(emoji).startsWith('<a:') } : emoji ? { name: emoji } : null; }
function rarityLabel(rarity) { return RARITY_EMOJI[String(rarity || '').toLowerCase()] || ''; }
function rodDurability(user, rodId) { const item = getItemDefinition(rodId); const entry = user.inventory?.[rodId]; if (!item || item.durability === null) return 'Infinity'; return String(entry?.durabilities?.[0] ?? entry?.durability ?? item.durability); }
function getEquippedRod(user) { return getItemDefinition(user.equippedRodId) || ITEMS.wooden_fishing_rod; }
function getRodPower(rod) { return randomInt(Math.floor(rod.powerMin || 1), Math.floor(rod.powerMax || rod.powerMin || 1)); }
function equipFallbackRod(user, preferredRodId = null) { if (preferredRodId && getInventoryAmount(user, preferredRodId) > 0) user.equippedRodId = preferredRodId; else user.equippedRodId = 'wooden_fishing_rod'; }
function damageEquippedRod(user, amount) { const rodId = user.equippedRodId || 'wooden_fishing_rod'; const rod = getItemDefinition(rodId); if (!rod || rod.durability === null) return false; normalizeRodDurabilities(user, rodId); const entry = user.inventory[rodId]; entry.durabilities[0] = Math.max(0, Math.floor(Number(entry.durabilities[0] ?? rod.durability) - Math.max(0, Math.ceil(amount)))); entry.durability = entry.durabilities[0]; if (entry.durability > 0) return false; entry.durabilities.shift(); entry.amount = Math.max(0, Math.floor(Number(entry.amount) || 0) - 1); if (entry.amount <= 0) delete user.inventory[rodId]; else entry.durability = entry.durabilities[0] ?? rod.durability; equipFallbackRod(user, rodId); return true; }
function destroyOneItem(userId, itemId) { let result = '-# **Item not found.**'; updateUser(userId, (user) => { const item = getItemDefinition(itemId); const entry = user.inventory?.[itemId]; if (!item || !entry || getInventoryAmount(user, itemId) <= 0) return user; if (item.type === 'Gear/Tool') normalizeRodDurabilities(user, itemId); if (Array.isArray(entry.durabilities)) entry.durabilities.shift(); entry.amount = Math.max(0, Math.floor(Number(entry.amount) || 0) - 1); if (entry.amount <= 0) delete user.inventory[itemId]; else entry.durability = entry.durabilities?.[0] ?? entry.durability ?? item.durability ?? null; if (user.equippedRodId === itemId) equipFallbackRod(user, itemId); result = `-# **Destroyed 1 ${item.emoji} ${item.name}. No Fish Coins were given.**`; return user; }); return result; }
function pageItems(items, requestedPage, perPage = 5) { const maxPage = Math.max(1, Math.ceil(items.length / perPage)); const page = Math.max(1, Math.min(maxPage, Math.floor(Number(requestedPage) || 1))); return { page, maxPage, items: items.slice((page - 1) * perPage, page * perPage) }; }

function renderHome(userId) { const user = getUser(userId); return container(WHITE, [{ type: 10, content: `## You are in ${user.location || LOCATION}\n-# Ready to fish? Press the button below to start fishing` }, sep(), fishButton(userId), actionSelect(userId)]); }
function renderEquipment(userId, username) { const user = getUser(userId); const rod = getEquippedRod(user); const rodOptions = Object.entries(user.inventory).filter(([itemId]) => getItemDefinition(itemId)?.type === 'Gear/Tool' && getInventoryAmount(user, itemId) > 0).map(([itemId]) => { const item = getItemDefinition(itemId); const emoji = componentEmoji(item.emoji); return { label: item.name, value: item.id, ...(emoji ? { emoji } : {}), default: item.id === user.equippedRodId }; }); const content = [`## ${username}'s Equipments.`, '-# Fishing rod:', `* ${rod.emoji} ${rod.name}`, `* Power: ${rod.powerMin} - ${rod.powerMax} - Dur: ${rodDurability(user, user.equippedRodId)}`].join('\n'); return container(WHITE, [{ type: 10, content }, row([{ type: 3, custom_id: `fish:rod:${userId}`, placeholder: rod.name, min_values: 1, max_values: 1, disabled: rodOptions.length <= 1, options: rodOptions.length ? rodOptions : [{ label: rod.name, value: rod.id, default: true }] }]), actionSelect(userId, 'Select an action', ['fishing', 'location'])]); }
function renderLocationComingSoon(userId) { return container(WHITE, [{ type: 10, content: '## coming soon...' }, actionSelect(userId, 'Select an action', ['fishing', 'equipment'])]); }
function renderFishBarrelFull(userId, username = 'Your') { const user = getUser(userId); return container(WHITE, [{ type: 10, content: `## ${username}'s Fish Barrel is full!\n-# Capacity: ${user.fishBarrel.length} / ${user.fishCapacity}\n-# Sell some fish in /fishy-market or manage your barrel before fishing again.` }, sep(), actionSelect(userId)]); }
function renderInventory(userId, username, requestedPage = 1) { const user = getUser(userId); const records = Object.entries(user.inventory).map(([itemId, entry]) => ({ item: getItemDefinition(itemId), itemId, entry })).filter((record) => record.item && Number(record.entry.amount) > 0); const paged = pageItems(records, requestedPage); const rows = [{ type: 10, content: `## ${username}'s inventory` }]; for (const { item, itemId, entry } of paged.items) { const using = user.equippedRodId === itemId ? `\n-# You are using a ${item.emoji} ${item.name} - Durability: ${rodDurability(user, itemId)}` : ''; const dur = item.type === 'Gear/Tool' ? `\n-# Durability: ${rodDurability(user, itemId)}` : ''; const content = `### x${entry.amount} ${item.name} ${item.emoji} \`${item.type}\`${dur}${using}\n-# Rarity: ${rarityLabel(item.rarity)}\n-# Value: ${item.value}`; rows.push({ type: 9, components: [{ type: 10, content }], accessory: button(`fish:destroyitem:${userId}:${itemId}:${paged.page}`, 'Destroy', BUTTON_DANGER) }); } if (!paged.items.length) rows.push({ type: 10, content: '-# No items found.' }); rows.push(sep(), row([button(`fish:invpage:${userId}:${paged.page}:${paged.maxPage}`, 'Switch page', BUTTON_SECONDARY, paged.maxPage <= 1)])); return container(WHITE, rows); }
function renderFishBarrel(userId, username, requestedPage = 1) { const user = getUser(userId); const records = user.fishBarrel.map((entry) => ({ entry, fish: FISH_BY_ID.get(entry.fishId) })).filter((record) => record.fish); const paged = pageItems(records, requestedPage); const lines = paged.items.map(({ entry, fish }) => `### x1 ${fish.displayName || fish.name} ${fish.emoji}\n-# Rarity: ${rarityLabel(fish.rarity)}\n-# Weigh: ${entry.weight} kg\n-# Variant / Mutation: ${entry.variant} ${entry.variantEmoji} / ${entry.mutation || 'None'}`); return container(WHITE, [{ type: 10, content: [`## ${username}'s inventory`, `-# Capacity: ${user.fishBarrel.length} / ${user.fishCapacity}`, lines.join('\n') || '-# No fish found.'].join('\n') }]); }
function renderCaught(userId, caught) { const fish = FISH_BY_ID.get(caught.fishId); const mutation = caught.mutation ? `${caught.mutation} ${caught.mutationEmoji || ''}`.trim() : 'None'; return container(GREEN, [{ type: 10, content: `## ${fish.emoji} ${fish.displayName || fish.name} has been caught!\n-# * Variant: ${caught.variant} ${caught.variantEmoji}\n-# * Mutation: ${mutation}\n-# * Weigh: ${caught.weight} kg\n-# * Rarity: ${rarityLabel(fish.rarity)}` }, sep(), fishButton(userId), actionSelect(userId)]); }
function renderEscaped(userId, fish, reason = '') { const title = reason === 'broken' || reason === 'lightning' ? `## ${fish.emoji} ${fish.displayName || fish.name} has escaped! Your fishing rod broke!` : `## ${fish.emoji} ${fish.displayName || fish.name} has escaped!`; return container(RED, [{ type: 10, content: `${title}\n-# Better luck next time` }, sep(), fishButton(userId), actionSelect(userId)]); }

function formatDuration(ms) { const sec = Math.max(0, Math.ceil(ms / 1000)); const h = Math.floor(sec / 3600); const m = Math.floor((sec % 3600) / 60); const s = sec % 60; return h ? `${h}h ${m}m` : m ? `${m}m ${s}s` : `${s}s`; }
function formatForecast(weather) { const effects = ADMIN_WEATHER[weather.weather]?.text || weatherData.WEATHER_TEXT[weather.weather] || weatherData.WEATHER_TEXT.Sunny; return ['## Fishy Weather Forecast', `* Season: ${weather.season} ${weather.seasonEmoji}`, `* Time: ${weather.time} ${weather.timeEmoji}`, `* Todays weather: ${weather.weather} ${weather.weatherEmoji || weatherEmoji(weather.weather)}`, '', '-# Effects:', effects.map((effect) => `- ${effect}`).join('\n')].join('\n'); }
function emojiImageUrl(emoji) { const match = String(emoji || '').match(/<a?:([A-Za-z0-9_]+):(\d+)>/); return match ? `https://cdn.discordapp.com/emojis/${match[2]}.${String(emoji).startsWith('<a:') ? 'gif' : 'png'}?quality=lossless` : null; }
function forecastPayload(weather, state) { cleanupEvents(state); const components = [{ type: 17, accent_color: WHITE, components: [{ type: 10, content: formatForecast(weather) }] }]; const now = Date.now(); for (const [eventId, active] of Object.entries(state.events.active || {})) { const event = FISH_EVENTS[eventId]; if (!event) continue; const media = emojiImageUrl(event.emoji); components.push({ type: 17, accent_color: YELLOW, components: [{ type: 9, components: [{ type: 10, content: `### ${event.name} has started!\n-# Duration: ${formatDuration(Number(active.endsAt) - now)}\n-# ${event.description}` }], accessory: media ? { type: 11, media: { url: media } } : undefined }] }); } return { flags: COMPONENTS_V2_FLAG, components }; }
async function findForecastMessage(channel) { const messages = await channel.messages?.fetch?.({ limit: 50 }).catch(() => null); if (!messages) return null; return messages.find((message) => message.author?.id === channel.client?.user?.id && JSON.stringify(message.components || []).includes('Fishy Weather Forecast')) || null; }
async function maybeEditWeatherForecast(client) { const state = loadState(); const weather = getCurrentWeather(state); cleanupEvents(state); state.forecasts = state.forecasts && typeof state.forecasts === 'object' ? state.forecasts : {}; const key = `${weather.location}:${weather.startedAt}:${weather.weather}:${Object.keys(state.events.active || {}).join(',')}:${Math.floor(Date.now() / 60000)}`; const channel = await client.channels.fetch(FISHING_CHANNEL_ID).catch(() => null); if (!channel?.isTextBased?.()) { saveState(state); return; } let message = state.forecasts.forecastMessageId ? await channel.messages.fetch(state.forecasts.forecastMessageId).catch(() => null) : null; if (!message) message = await findForecastMessage(channel); if (message && state.forecasts.lastForecastKey === key) { saveState(state); return; } message = message ? await message.edit(forecastPayload(weather, state)).catch(() => null) : await channel.send(forecastPayload(weather, state)).catch(() => null); if (message?.id) { state.forecasts.forecastMessageId = message.id; state.forecasts.lastForecastKey = key; } saveState(state); }
function startWeatherTimer(client) { if (weatherTimerStarted) return; weatherTimerStarted = true; maybeEditWeatherForecast(client).catch(() => null); setInterval(() => maybeEditWeatherForecast(client).catch(() => null), 60000); }

function chooseFish() { const rarity = weightedPick(Object.entries(RARITY_WEIGHTS).map(([key, weight]) => ({ value: key, weight }))) || 'common'; const candidates = FISH.filter((fish) => fish.rarity === rarity); return candidates[randomInt(0, candidates.length - 1)] || FISH[0]; }
function pickVariant(weatherName) { const bonus = Number(weatherEffects(weatherName).goldenBonus) || 0; if (bonus > 0 && Math.random() < bonus) return VARIANTS.find((variant) => variant.key === 'Golden') || VARIANTS[1]; return weightedPick(VARIANTS.map((variant) => ({ value: variant, weight: variant.chance }))) || VARIANTS[0]; }
function rememberMutation(user, caught) { if (!caught.mutation) return; const key = normalizeId(caught.mutation); const previous = user.mutationIndex[key] && typeof user.mutationIndex[key] === 'object' ? user.mutationIndex[key] : {}; user.mutationIndex[key] = { discoveredAt: previous.discoveredAt || Date.now(), count: Math.max(0, Math.floor(Number(previous.count) || 0)) + 1, lastCaughtAt: Date.now() }; }
function applyMutation(user, caught, weatherName, state) { let mutation = weatherData.rollMutation(weatherName); if (!mutation && hasEvent(state, 'attack_of_fish') && Math.random() < FISH_EVENTS.attack_of_fish.giantChance) mutation = GIANT_MUTATION; if (!mutation) { caught.mutation = null; caught.mutationMultiplier = 1; return; } caught.mutation = mutation.name; caught.mutationEmoji = mutation.emoji || null; caught.mutationMultiplier = Number(mutation.multiplier) || 1; caught.mutationMultiplierType = mutation.multiplierType || (mutation.weightMultiplier ? 'weigh' : 'value'); if (mutation.weightMultiplier) { caught.weight = Number((Number(caught.weight || 0) * mutation.weightMultiplier).toFixed(2)); caught.weightMultiplier = mutation.weightMultiplier; } rememberMutation(user, caught); }
function createSession(userId, messageId, fish, weather, state) { const effect = weatherEffects(weather.weather); const eventPower = hasEvent(state, 'strength_blessing') ? FISH_EVENTS.strength_blessing.powerMultiplier : 1; const totalPower = Math.max(1, Math.ceil(fish.powerReq * (effect.powerMultiplier || 1) / eventPower)); const id = `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`; const buttons = [...REEL_EMOJIS].sort(() => Math.random() - 0.5).slice(0, RARITY_BUTTONS[fish.rarity] || 2); const session = { id, ownerId: userId, messageId, fishId: fish.id, totalPower, remainingPower: totalPower, correctEmoji: buttons[randomInt(0, buttons.length - 1)], buttons, weatherName: weather.weather }; activeGames.set(id, session); activeGameByUser.set(userId, id); return session; }
function finishSession(session) { if (!session) return; activeGames.delete(session.id); if (activeGameByUser.get(session.ownerId) === session.id) activeGameByUser.delete(session.ownerId); }
function renderBite(session) { const fish = FISH_BY_ID.get(session.fishId); const percent = Math.floor(((session.totalPower - session.remainingPower) / session.totalPower) * 100); const rows = []; for (let index = 0; index < session.buttons.length; index += 5) rows.push(row(session.buttons.slice(index, index + 5).map((emoji, buttonIndex) => ({ type: 2, custom_id: `fish:reel:${session.id}:${index + buttonIndex}`, emoji: { name: emoji }, style: BUTTON_SECONDARY })))); return container(WHITE, [{ type: 10, content: `## ${fish.emoji} ${fish.displayName || fish.name} have bitten your hook!\n${percent}%\n\n-# Select the correct button: ${session.correctEmoji}` }, sep(), ...rows]); }
async function startFishing(interaction) { const userId = interaction.user.id; const state = loadState(); const currentUser = ensureUser(state, userId); const existingId = activeGameByUser.get(userId); if (existingId && activeGames.has(existingId)) { await interaction.reply({ content: 'You already have a fishing minigame active. Finish it before starting another one.', flags: EPHEMERAL_FLAG }).catch(() => null); return; } if (currentUser.fishBarrel.length >= currentUser.fishCapacity) { await interaction.update(renderFishBarrelFull(userId, interaction.user.username)); return; } const weather = getCurrentWeather(state); const effect = weatherEffects(weather.weather); const begin = async () => { const fish = chooseFish(); const session = createSession(userId, interaction.message.id, fish, weather, state); if (weather.weather === 'Thunderstorm' && effect.lightningBreakChance && Math.random() < effect.lightningBreakChance) { const broke = updateUser(userId, (user) => damageEquippedRod(user, Number.MAX_SAFE_INTEGER)); finishSession(session); await interaction.message.edit(renderEscaped(userId, fish, broke ? 'lightning' : '')).catch(() => null); return; } await interaction.message.edit(renderBite(session)).catch(() => finishSession(session)); }; if (hasEvent(state, 'fish_hotspot')) { await interaction.update(container(WHITE, [{ type: 10, content: `## Fish instantly bite the hook! ${SPIN_FISH}` }])); await begin(); return; } await interaction.update(container(WHITE, [{ type: 10, content: `## You've cast your hook, waiting for fish... ${SPIN_FISH}` }])); setTimeout(() => begin().catch(() => null), Math.max(1000, (randomInt(5, 8) + (effect.lureSeconds || 0)) * 1000)); }
async function handleReel(interaction, sessionId, buttonIndex) { const session = activeGames.get(sessionId); if (!session) { await interaction.reply({ content: 'This fishing attempt already ended.', flags: EPHEMERAL_FLAG }).catch(() => null); return true; } if (interaction.user.id !== session.ownerId) { await interaction.reply({ content: 'This is not your fishing attempt.', flags: EPHEMERAL_FLAG }).catch(() => null); return true; } const fish = FISH_BY_ID.get(session.fishId); const selectedEmoji = session.buttons[Number(buttonIndex)]; const effect = weatherEffects(session.weatherName); let broke = false; updateUser(session.ownerId, (user) => { const rod = getEquippedRod(user); const damage = Math.max(1, Math.ceil(fish.durDamage * (effect.durMultiplier || 1))); if (selectedEmoji === session.correctEmoji) { session.remainingPower = Math.max(0, session.remainingPower - getRodPower(rod)); broke = damageEquippedRod(user, Math.max(1, Math.ceil(damage / 4))); } else { session.remainingPower = Math.min(session.totalPower, session.remainingPower + Math.ceil(session.totalPower / 5)); broke = damageEquippedRod(user, damage); } return user; }); if (broke) { finishSession(session); await interaction.update(renderEscaped(session.ownerId, fish, 'broken')); return true; } if (session.remainingPower <= 0) { const variant = pickVariant(session.weatherName); const caught = { id: `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`, fishId: fish.id, weight: Number(randomFloat(fish.minWeight, fish.maxWeight).toFixed(2)), variant: variant.key, variantEmoji: variant.emoji, mutation: null, sellValue: fish.sellValue * variant.multiplier, caughtAt: Date.now() }; let stored = false; updateUser(session.ownerId, (user, state) => { const previous = user.fishIndex[fish.id] && typeof user.fishIndex[fish.id] === 'object' ? user.fishIndex[fish.id] : {}; user.fishIndex[fish.id] = { discoveredAt: previous.discoveredAt || Date.now(), count: Math.max(0, Math.floor(Number(previous.count) || 0)) + 1, lastCaughtAt: Date.now() }; applyMutation(user, caught, session.weatherName, state); if (user.fishBarrel.length < user.fishCapacity) { user.fishBarrel.push(caught); stored = true; } return user; }); finishSession(session); await interaction.update(stored ? renderCaught(session.ownerId, caught) : renderFishBarrelFull(session.ownerId, interaction.user.username)); return true; } session.correctEmoji = session.buttons[randomInt(0, session.buttons.length - 1)]; await interaction.update(renderBite(session)); return true; }

function isOwner(interaction, userId) { if (interaction.user.id === userId) return true; interaction.reply({ content: 'Only the command owner can use this control.', flags: EPHEMERAL_FLAG }).catch(() => null); return false; }
async function handleFishingInteraction(interaction) { const id = interaction.customId || ''; if (!id.startsWith('fish:')) return false; const parts = id.split(':'); const action = parts[1]; if (action === 'action' && interaction.isStringSelectMenu?.()) { const userId = parts[2]; if (!isOwner(interaction, userId)) return true; const value = interaction.values?.[0]; if (value === 'equipment') await interaction.update(renderEquipment(userId, interaction.user.username)); else if (value === 'location') await interaction.update(renderLocationComingSoon(userId)); else await interaction.update(renderHome(userId)); return true; } if (action === 'rod' && interaction.isStringSelectMenu?.()) { const userId = parts[2]; if (!isOwner(interaction, userId)) return true; updateUser(userId, (user) => { const rodId = interaction.values?.[0]; if (getItemDefinition(rodId)?.type === 'Gear/Tool' && getInventoryAmount(user, rodId)) user.equippedRodId = rodId; return user; }); await interaction.update(renderEquipment(userId, interaction.user.username)); return true; } if (action === 'start' && interaction.isButton?.()) { const userId = parts[2]; if (!isOwner(interaction, userId)) return true; await startFishing(interaction); return true; } if (action === 'reel' && interaction.isButton?.()) return handleReel(interaction, parts[2], parts[3]); if (action === 'invpage' && interaction.isButton?.()) { const userId = parts[2]; if (!isOwner(interaction, userId)) return true; const maxPage = Math.max(1, Number(parts[4]) || 1); const nextPage = ((Number(parts[3]) || 1) % maxPage) + 1; await interaction.update(renderInventory(userId, interaction.user.username, nextPage)); return true; } if (action === 'destroyitem' && interaction.isButton?.()) { const userId = parts[2]; if (!isOwner(interaction, userId)) return true; const item = getItemDefinition(parts[3]); await interaction.reply({ content: `Destroy 1 ${item?.emoji || ''} ${item?.name || 'item'}? This gives no Fish Coins and cannot be undone.`, flags: EPHEMERAL_FLAG, components: [row([button(`fish:destroyconfirm:${userId}:${parts[3]}:${parts[4] || 1}`, 'Confirm Destroy', BUTTON_DANGER), button(`fish:destroycancel:${userId}`, 'Cancel', BUTTON_SECONDARY)])] }).catch(() => null); return true; } if (action === 'destroycancel' && interaction.isButton?.()) { await interaction.update({ content: 'Destroy cancelled.', components: [] }).catch(() => null); return true; } if (action === 'destroyconfirm' && interaction.isButton?.()) { const userId = parts[2]; if (!isOwner(interaction, userId)) return true; await interaction.update({ content: destroyOneItem(userId, parts[3]), components: [] }).catch(() => null); return true; } return false; }

const fishCommand = { data: new SlashCommandBuilder().setName('fish').setDescription('Go fishing'), suppressCommandLog: true, disableActionTimeout: true, init: startWeatherTimer, async execute(interaction) { await interaction.reply(renderHome(interaction.user.id)); }, async handleInteraction(interaction) { return handleFishingInteraction(interaction); } };
const inventoryCommand = { data: new SlashCommandBuilder().setName('inventory').setDescription('Show your inventory'), suppressCommandLog: true, disableActionTimeout: true, async execute(interaction) { await interaction.reply(renderInventory(interaction.user.id, interaction.user.username)); }, async handleInteraction(interaction) { return handleFishingInteraction(interaction); } };
const fishBarrelCommand = { data: new SlashCommandBuilder().setName('fish-barrel').setDescription('Show your Fish Barrel'), suppressCommandLog: true, disableActionTimeout: true, async execute(interaction) { await interaction.reply(renderFishBarrel(interaction.user.id, interaction.user.username)); }, async handleInteraction(interaction) { return handleFishingInteraction(interaction); } };
const fishBalanceCommand = { data: new SlashCommandBuilder().setName('fish-balance').setDescription('Show your Fish Coin balance'), suppressCommandLog: true, async execute(interaction) { const user = getUser(interaction.user.id); await interaction.reply(container(WHITE, [{ type: 10, content: [`### ${interaction.user.username}'s Fish Balance`, `* ${user.fishCoins.toLocaleString('en-US')} ${FISH_COIN}`].join('\n') }])); }, async handleInteraction(interaction) { return handleFishingInteraction(interaction); } };

module.exports = { ITEMS, FISH, FISH_BY_ID, ADMIN_WEATHER, FISH_EVENTS, activeEvents, cleanupEvents, getCurrentWeather, maybeEditWeatherForecast, getUser, updateUser, fishCommand, inventoryCommand, fishBarrelCommand, fishBalanceCommand };
