const fs = require('fs');
const path = require('path');
const { AttachmentBuilder, MessageFlags, SlashCommandBuilder } = require('discord.js');
const { createCanvas } = require('@napi-rs/canvas');
const fishing = require('./fishingFeature');

const { ITEMS, FISH, FISH_BY_ID, getUser, updateUser, inventoryCommand: featureInventoryCommand, fishBarrelCommand: featureFishBarrelCommand } = fishing;
const COMPONENTS_V2_FLAG = MessageFlags.IsComponentsV2 ?? 32768;
const EPHEMERAL_FLAG = MessageFlags.Ephemeral ?? 64;
const WHITE = 0xffffff;
const BUTTON_SECONDARY = 2;
const BUTTON_SUCCESS = 3;
const BUTTON_DANGER = 4;
const FISH_COIN = '<:CRFishCoin:1506701069990891751>';
const STORE_PATH = path.join(__dirname, '..', 'data', 'fishing-game.json');
const SYMBOL_DIR = path.join(__dirname, 'Symbol');
const CHART_DIR = path.join(__dirname, 'Value Charts');
const PAGE_SIZE = 5;
const TEXT_INPUT = 4;
const RARITY_EMOJI = { common: '<:SBCommon:1506965202585780274>', uncommon: '<:SBUncommon:1506965215743447040>', rare: '<:SBRare:1506965211607994461>', epic: '<:SBEpic:1506965204624474153>', legendary: '<:SBLegendary:1506965206197207131>', mythical: '<:SBMythical:1506965209271762954>', secret: '<:SBSecret:1506965213881307186>' };
const VARIANT_MULTIPLIER = { Normal: 1, Golden: 2, Rainbow: 5 };

function emptyState() { return { users: {}, weather: {}, forecasts: {}, events: { active: {} }, market: { entries: {}, lastUpdateAt: 0 } }; }
function ensureStoreFile() { const dir = path.dirname(STORE_PATH); if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true }); if (!fs.existsSync(STORE_PATH)) fs.writeFileSync(STORE_PATH, JSON.stringify(emptyState(), null, 2), 'utf8'); }
function loadState() { ensureStoreFile(); try { const state = JSON.parse(fs.readFileSync(STORE_PATH, 'utf8')); return { ...emptyState(), ...(state && typeof state === 'object' ? state : {}) }; } catch { return emptyState(); } }
function saveState(state) { ensureStoreFile(); state.market = state.market && typeof state.market === 'object' ? state.market : { entries: {}, lastUpdateAt: 0 }; state.market.entries = state.market.entries && typeof state.market.entries === 'object' ? state.market.entries : {}; fs.writeFileSync(STORE_PATH, JSON.stringify({ ...emptyState(), ...state }, null, 2), 'utf8'); }
function normalizeId(value) { return String(value || '').trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, ''); }
function rarityLabel(rarity) { return RARITY_EMOJI[String(rarity || '').toLowerCase()] || ''; }
function pageItems(items, page) { const maxPage = Math.max(1, Math.ceil(items.length / PAGE_SIZE)); const safePage = Math.max(1, Math.min(maxPage, Math.floor(Number(page) || 1))); return { page: safePage, maxPage, items: items.slice((safePage - 1) * PAGE_SIZE, safePage * PAGE_SIZE) }; }
function row(components) { return { type: 1, components }; }
function sep() { return { type: 14, divider: true, spacing: 1 }; }
function button(customId, label, style = BUTTON_SECONDARY, disabled = false) { return { type: 2, custom_id: customId, label, style, disabled }; }
function stripUndefined(value) { if (Array.isArray(value)) return value.map(stripUndefined).filter((entry) => entry !== undefined); if (!value || typeof value !== 'object') return value; const out = {}; for (const [key, entry] of Object.entries(value)) if (entry !== undefined) out[key] = stripUndefined(entry); return out; }
function symbolAttachment(fileName, files) { const imagePath = path.join(SYMBOL_DIR, fileName); if (!fs.existsSync(imagePath)) return null; files.push(new AttachmentBuilder(imagePath, { name: fileName })); return fileName; }
function withThumbnail(components, fileName) { if (!fileName || !components[0] || components[0].type !== 10) return components; const [first, ...rest] = components; return [{ type: 9, components: [first], accessory: { type: 11, media: { url: `attachment://${fileName}` } } }, ...rest]; }
function container(components, files = []) { return stripUndefined({ flags: COMPONENTS_V2_FLAG, files, components: [{ type: 17, accent_color: WHITE, components: components.filter(Boolean) }] }); }
function categorySelect(userId, selected = null) { const labels = { fish: 'Sell-fish', item: 'Sell-item', chart: 'Value-Chart' }; return row([{ type: 3, custom_id: `fm:category:${userId}`, placeholder: 'Select a category', min_values: 1, max_values: 1, options: Object.entries(labels).map(([value, label]) => ({ label, value, default: selected === value })) }]); }
function getItem(itemId) { return ITEMS[itemId] || null; }
function marketKey(type, id) { return `${type}:${id}`; }
function baseValue(type, id) { if (type === 'fish') return FISH_BY_ID.get(id)?.value || FISH_BY_ID.get(id)?.sellValue || 1; return Math.max(1, getItem(id)?.value || 1); }
function countExisting(state, type, id) { let total = 0; for (const user of Object.values(state.users || {})) { if (type === 'fish') total += (Array.isArray(user.fishBarrel) ? user.fishBarrel : []).filter((entry) => entry.fishId === id).length; else total += Math.max(0, Math.floor(Number(user.inventory?.[id]?.amount) || 0)); } return total; }
function ensureMarketEntry(state, type, id) { state.market = state.market && typeof state.market === 'object' ? state.market : { entries: {}, lastUpdateAt: 0 }; state.market.entries = state.market.entries && typeof state.market.entries === 'object' ? state.market.entries : {}; const key = marketKey(type, id); if (!state.market.entries[key]) { const base = baseValue(type, id); state.market.entries[key] = { type, id, baseValue: base, currentValue: base, history: [{ at: Date.now(), value: base }], lastExistAmount: countExisting(state, type, id) }; } return state.market.entries[key]; }
function updateMarketEntry(state, type, id, soldAmount = 0, boughtAmount = 0) { const entry = ensureMarketEntry(state, type, id); const existAmount = countExisting(state, type, id); const existChange = existAmount - (Number(entry.lastExistAmount) || 0); let next = Number(entry.currentValue) || entry.baseValue; next -= next * (soldAmount * 0.003); next += next * (boughtAmount * 0.004); if (existChange > 0) next -= next * (existChange * 0.001); if (existChange < 0) next += next * (Math.abs(existChange) * 0.0015); next = Math.max(entry.baseValue * 0.35, Math.min(entry.baseValue * 3, next)); entry.currentValue = Math.max(1, Math.round(next)); entry.lastExistAmount = existAmount; entry.history = Array.isArray(entry.history) ? entry.history : []; entry.history.push({ at: Date.now(), value: entry.currentValue }); entry.history = entry.history.slice(-36); return entry; }
function marketValue(state, type, id) { return ensureMarketEntry(state, type, id).currentValue; }
function weightMultiplier(fish, entry) { const weight = Number(entry.weight) || fish.minWeight; if (fish.maxWeight <= fish.minWeight) return 1; const progress = Math.max(0, Math.min(1, (weight - fish.minWeight) / (fish.maxWeight - fish.minWeight))); return 1 + progress * 0.5; }
function mutationMultiplier(entry) { return entry?.mutation && String(entry.mutation).toLowerCase() !== 'none' ? Number(entry.mutationMultiplier) || 1 : 1; }
function fishTotalValue(state, entry, fish) { return Math.max(1, Math.round(marketValue(state, 'fish', fish.id) * weightMultiplier(fish, entry) * (VARIANT_MULTIPLIER[entry.variant] || 1) * mutationMultiplier(entry))); }
function fishRecords(user) { return (Array.isArray(user.fishBarrel) ? user.fishBarrel : []).map((entry, index) => ({ entry, index, fish: FISH_BY_ID.get(entry.fishId) })).filter((record) => record.fish); }
function itemRecords(user) { return Object.entries(user.inventory || {}).map(([itemId, entry]) => ({ itemId, entry, item: ITEMS[itemId] })).filter((record) => record.item && Math.max(0, Math.floor(Number(record.entry?.amount) || 0)) > 0); }
function mutationName(entry) { return entry.mutation ? `${entry.mutation} ${entry.mutationEmoji || ''}`.trim() : 'None'; }
function renderFishLine(state, record) { const value = fishTotalValue(state, record.entry, record.fish); const mEmoji = record.entry.mutationEmoji ? ` ${record.entry.mutationEmoji}` : ''; return `### ${record.fish.emoji} ${record.fish.displayName || record.fish.name}${mEmoji}\n-# Rarity: ${rarityLabel(record.fish.rarity)} - Weight: ${Number(record.entry.weight || 0).toFixed(2)} kg\n-# Variant / Mutation: ${record.entry.variant || 'Normal'} ${record.entry.variantEmoji || ''} / ${mutationName(record.entry)}\n-# Value: **${value} ${FISH_COIN}**`; }
function renderItemLine(state, record) { const amount = Math.max(0, Math.floor(Number(record.entry.amount) || 0)); const value = Math.max(1, Math.floor(marketValue(state, 'item', record.itemId) * 0.25)); return `### x${amount} ${record.item.emoji} ${record.item.name}\n-# Rarity: ${rarityLabel(record.item.rarity)} - Type: ${record.item.type}\n-# Sell Value: **${value * amount} ${FISH_COIN}**`; }
function renderHome(userId) { const files = []; const thumb = symbolAttachment('SBFishSellMarket.png', files); return container(withThumbnail([{ type: 10, content: '## Welcome to Fishy Market!\n-# Select a category.' }, sep(), categorySelect(userId)], thumb), files); }
function renderFishMarket(userId, page = 1, message = '-# **Anything you sold will appear here**') { const state = loadState(); const user = getUser(userId); const files = []; const thumb = symbolAttachment('SBFishSellMarket.png', files); const paged = pageItems(fishRecords(user), page); const rows = [{ type: 10, content: '## Welcome to Fish Selling Market!' }]; for (const record of paged.items) rows.push({ type: 9, components: [{ type: 10, content: renderFishLine(state, record) }], accessory: button(`fm:sellfish:${userId}:${record.entry.id || record.index}:${paged.page}`, record.entry.locked ? 'Locked' : 'Sell', record.entry.locked ? BUTTON_SECONDARY : BUTTON_DANGER, Boolean(record.entry.locked)) }); if (!paged.items.length) rows.push({ type: 10, content: '-# No fish found.' }); rows.push(sep(), { type: 10, content: message }, row([button(`fm:fishpage:${userId}:${paged.page}:${paged.maxPage}`, 'Switch page', BUTTON_SECONDARY, paged.maxPage <= 1), button(`fm:sellfilter:${userId}`, 'Sell filter', BUTTON_SECONDARY, paged.items.length === 0)]), categorySelect(userId, 'fish')); saveState(state); return container(withThumbnail(rows, thumb), files); }
function renderItemMarket(userId, page = 1, message = '-# **Anything you sold will appear here**') { const state = loadState(); const user = getUser(userId); const files = []; const thumb = symbolAttachment('SBItemSellMarket.png', files); const paged = pageItems(itemRecords(user), page); const rows = [{ type: 10, content: '## Welcome to Item Selling Market!' }]; for (const record of paged.items) { const unsellable = record.item.unsellable || record.item.id === 'wooden_fishing_rod'; rows.push({ type: 9, components: [{ type: 10, content: renderItemLine(state, record) }], accessory: button(`fm:sellitem:${userId}:${record.itemId}:${paged.page}`, unsellable ? 'Unsellable' : 'Sell', unsellable ? BUTTON_SECONDARY : BUTTON_DANGER, unsellable) }); } if (!paged.items.length) rows.push({ type: 10, content: '-# No items found.' }); rows.push(sep(), { type: 10, content: message }, row([button(`fm:itempage:${userId}:${paged.page}:${paged.maxPage}`, 'Switch page', BUTTON_SECONDARY, paged.maxPage <= 1), button(`fm:itemfilter:${userId}`, 'Sell filter', BUTTON_SECONDARY, paged.items.length === 0)]), categorySelect(userId, 'item')); saveState(state); return container(withThumbnail(rows, thumb), files); }
function chartRecords(state, userId, type) { if (type === 'fish') return FISH.map((fish) => ({ id: fish.id, name: fish.displayName || fish.name, emoji: fish.emoji })); return itemRecords(getUser(userId)).map((record) => ({ id: record.itemId, name: record.item.name, emoji: record.item.emoji })); }
function chartPathFor(type, id) { if (!fs.existsSync(CHART_DIR)) fs.mkdirSync(CHART_DIR, { recursive: true }); return path.join(CHART_DIR, `${type}-${normalizeId(id)}.png`); }
function formatNumber(value) { const num = Number(value) || 0; if (Math.abs(num) >= 1000000) return (num / 1000000).toFixed(1).replace(/\.0$/, '') + 'm'; if (Math.abs(num) >= 1000) return (num / 1000).toFixed(1).replace(/\.0$/, '') + 'k'; return String(Math.round(num)); }
function renderChartImage(entry, title) { const canvas = createCanvas(900, 500); const ctx = canvas.getContext('2d'); const history = (entry.history?.length ? entry.history : [{ at: Date.now(), value: entry.currentValue }]).slice(-14); const values = history.map((point) => Math.max(1, Math.round(Number(point.value) || entry.baseValue || 1))); const min = Math.max(0, Math.min(...values, entry.baseValue) * 0.8); const max = Math.max(...values, entry.baseValue) * 1.2 || 10; const x0 = 90; const y0 = 355; const w = 760; const h = 220; ctx.fillStyle = '#0d1320'; ctx.fillRect(0, 0, 900, 500); ctx.fillStyle = '#151c2b'; ctx.roundRect(24, 24, 852, 452, 24); ctx.fill(); ctx.strokeStyle = '#33425f'; ctx.lineWidth = 2; ctx.stroke(); ctx.fillStyle = '#f6f8ff'; ctx.font = '800 30px Arial'; ctx.fillText(entry.type === 'fish' ? 'Fish Value Chart' : 'Item Value Chart', 54, 72); ctx.font = '700 20px Arial'; ctx.fillStyle = '#9fd4ff'; ctx.fillText(title, 54, 104); ctx.textAlign = 'right'; ctx.fillStyle = '#f7fbff'; ctx.font = '800 28px Arial'; ctx.fillText(formatNumber(entry.currentValue), 790, 82); ctx.textAlign = 'left'; ctx.strokeStyle = '#465a7d'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(x0, y0 - h); ctx.lineTo(x0, y0); ctx.lineTo(x0 + w, y0); ctx.stroke(); const points = values.map((value, index) => ({ x: x0 + ((values.length === 1 ? 0.5 : index / (values.length - 1)) * w), y: y0 - (((value - min) / Math.max(1, max - min)) * h), value })); ctx.strokeStyle = '#52f2c2'; ctx.lineWidth = 5; ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.beginPath(); points.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.stroke(); for (const point of points) { ctx.fillStyle = '#52f2c2'; ctx.beginPath(); ctx.arc(point.x, point.y, 5, 0, Math.PI * 2); ctx.fill(); } ctx.fillStyle = '#9aa9c2'; ctx.font = '700 14px Arial'; ctx.fillText('Base ' + formatNumber(entry.baseValue), 56, 430); ctx.fillText('High ' + formatNumber(Math.max(...values)), 190, 430); ctx.fillText('Low ' + formatNumber(Math.min(...values)), 320, 430); const chartPath = chartPathFor(entry.type, entry.id); fs.writeFileSync(chartPath, canvas.toBuffer('image/png')); entry.chartPath = chartPath; return chartPath; }
function renderValueChart(userId, type = 'fish', page = 1, selectedId = null) { const state = loadState(); const files = []; const thumb = symbolAttachment('SBValueChart.png', files); const paged = pageItems(chartRecords(state, userId, type), page); const rows = [{ type: 10, content: '## Welcome to Value Chart!' }]; for (const record of paged.items) { const entry = ensureMarketEntry(state, type, record.id); rows.push({ type: 9, components: [{ type: 10, content: `**${record.name} ${record.emoji}**\n-# Value: ${entry.currentValue} ${FISH_COIN}` }], accessory: button(`fm:chartcheck:${userId}:${type}:${record.id}:${paged.page}`, 'Check', BUTTON_SUCCESS) }); } if (!paged.items.length) rows.push({ type: 10, content: '-# No entries found.' }); rows.push(sep()); if (selectedId) { const entry = ensureMarketEntry(state, type, selectedId); const record = chartRecords(state, userId, type).find((item) => item.id === selectedId); const chartPath = renderChartImage(entry, record?.name || selectedId); files.push(new AttachmentBuilder(chartPath, { name: 'value-chart.png' })); rows.push({ type: 12, items: [{ media: { url: 'attachment://value-chart.png' } }] }); } else rows.push({ type: 10, content: '-# Select something to check its value' }); rows.push(sep(), row([button(`fm:chartpage:${userId}:${type}:${paged.page}:${paged.maxPage}`, 'Switch page', BUTTON_SECONDARY, paged.maxPage <= 1), button(`fm:charttoggle:${userId}:${type}`, `[Value: ${type.toUpperCase()}]`, BUTTON_SECONDARY)]), categorySelect(userId, 'chart')); saveState(state); return container(withThumbnail(rows, thumb), files); }
function findFishIndex(user, key) { return (Array.isArray(user.fishBarrel) ? user.fishBarrel : []).findIndex((entry, index) => String(entry.id || index) === String(key)); }
function sellFish(userId, fishKey) { let message = '-# **Fish not found**'; updateUser(userId, (user, state) => { const index = findFishIndex(user, fishKey); if (index < 0) return user; const entry = user.fishBarrel[index]; const fish = FISH_BY_ID.get(entry.fishId); if (!fish || entry.locked) { message = '-# **That fish is locked**'; return user; } state.market = state.market || { entries: {}, lastUpdateAt: 0 }; const value = fishTotalValue(state, entry, fish); user.fishCoins = Math.max(0, Math.floor(Number(user.fishCoins) || 0)) + value; user.fishBarrel.splice(index, 1); updateMarketEntry(state, 'fish', fish.id, 1, 0); message = `-# **You've sold ${fish.displayName || fish.name} ${fish.emoji} for ${value} ${FISH_COIN}**`; return user; }); return message; }
function sellItem(userId, itemId) { let message = '-# **Item not found**'; updateUser(userId, (user, state) => { const item = ITEMS[itemId]; const entry = user.inventory?.[itemId]; const amount = Math.max(0, Math.floor(Number(entry?.amount) || 0)); if (!item || !entry || amount <= 0) return user; if (item.unsellable || item.id === 'wooden_fishing_rod' || entry.locked) { message = '-# **That item cannot be sold**'; return user; } const value = Math.max(1, Math.floor(marketValue(state, 'item', itemId) * 0.25)) * amount; delete user.inventory[itemId]; user.fishCoins = Math.max(0, Math.floor(Number(user.fishCoins) || 0)) + value; updateMarketEntry(state, 'item', itemId, amount, 0); message = `-# **You've sold x${amount} ${item.name} ${item.emoji} for ${value} ${FISH_COIN}**`; return user; }); return message; }
const FILTER_RARITIES = [['all', 'All'], ['secret', 'Secret'], ['mythical', 'Mythical'], ['legendary', 'Legendary'], ['epic', 'Epic'], ['rare', 'Rare'], ['uncommon', 'Uncommon'], ['common', 'Common']];
function filterForm(kind, userId) { const isFish = kind === 'fish'; return { custom_id: `fm:${kind}filtersubmit:${userId}`, title: isFish ? 'Sell fish filter' : 'Sell item filter', components: [{ type: 18, label: isFish ? 'Select fish rarity to sell' : 'Select item rarity to sell', component: { type: 3, custom_id: `${kind}_rarities`, placeholder: 'Select rarity to sell', min_values: 1, max_values: FILTER_RARITIES.length, options: FILTER_RARITIES.map(([value, label]) => ({ value, label })) } }] }; }
function selectedValues(interaction, customId) { const found = []; const visit = (value) => { if (!value || typeof value !== 'object') return; if ((value.customId === customId || value.custom_id === customId) && Array.isArray(value.values)) found.push(...value.values); if (value.component) visit(value.component); if (Array.isArray(value.components)) value.components.forEach(visit); if (Array.isArray(value.data?.components)) value.data.components.forEach(visit); if (value.fields?.fields && typeof value.fields.fields.values === 'function') Array.from(value.fields.fields.values()).forEach(visit); }; if (Array.isArray(interaction.values)) found.push(...interaction.values); try { visit(interaction.toJSON?.()); } catch {} visit(interaction); return [...new Set(found.map((item) => String(item || '').trim()).filter(Boolean))]; }
function sellByRarity(userId, kind, rarities) { const wanted = new Set((Array.isArray(rarities) ? rarities : []).map((r) => String(r).toLowerCase())); const sellAll = wanted.has('all'); let sold = 0; let total = 0; updateUser(userId, (user, state) => { if (kind === 'fish') { user.fishBarrel = (user.fishBarrel || []).filter((entry) => { const fish = FISH_BY_ID.get(entry.fishId); if (!fish || entry.locked || (!sellAll && !wanted.has(String(fish.rarity).toLowerCase()))) return true; total += fishTotalValue(state, entry, fish); sold += 1; updateMarketEntry(state, 'fish', fish.id, 1, 0); return false; }); } else { for (const record of itemRecords(user)) { if (!record.item || record.item.unsellable || record.item.id === 'wooden_fishing_rod' || record.entry.locked || (!sellAll && !wanted.has(String(record.item.rarity).toLowerCase()))) continue; const amount = Math.max(0, Math.floor(Number(record.entry.amount) || 0)); total += Math.max(1, Math.floor(marketValue(state, 'item', record.itemId) * 0.25)) * amount; sold += amount; delete user.inventory[record.itemId]; updateMarketEntry(state, 'item', record.itemId, amount, 0); } } user.fishCoins = Math.max(0, Math.floor(Number(user.fishCoins) || 0)) + total; return user; }); return kind === 'fish' ? renderFishMarket(userId, 1, sold ? `-# **You've sold ${sold} fish - ${total} ${FISH_COIN}**` : '-# **No unlocked fish matched that filter**') : renderItemMarket(userId, 1, sold ? `-# **You've sold x${sold} items - ${total} ${FISH_COIN}**` : '-# **No unlocked sellable items matched that filter**'); }
function fieldValue(interaction, customId) { try { return interaction.fields.getTextInputValue(customId); } catch {} return ''; }
function pageModal(kind, userId, currentPage, maxPage, suffix = '') { return { custom_id: `fm:${kind}pagesubmit:${userId}${suffix}`, title: 'Switch page', components: [{ type: 1, components: [{ type: TEXT_INPUT, custom_id: `fm_${kind}_page`, label: `Page (1-${maxPage})`, style: 1, required: true, value: String(currentPage), max_length: String(maxPage).length }] }] }; }
function isOwner(interaction, userId) { if (interaction.user.id === userId) return true; interaction.reply({ content: 'Only the command owner can use this control.', flags: EPHEMERAL_FLAG }).catch(() => null); return false; }
async function updateInteraction(interaction, payload) { const clean = stripUndefined(payload); if (typeof interaction.update === 'function') return interaction.update(clean); if (typeof interaction.deferUpdate === 'function') { await interaction.deferUpdate(); return interaction.message?.edit(clean); } return interaction.reply(clean); }
async function handleMarketInteraction(interaction) { const id = interaction.customId || ''; if (!id.startsWith('fm:')) return false; const parts = id.split(':'); const action = parts[1]; const userId = parts[2]; if (!isOwner(interaction, userId)) return true; if (action === 'category' && interaction.isStringSelectMenu?.()) { const value = interaction.values?.[0]; return updateInteraction(interaction, value === 'item' ? renderItemMarket(userId) : value === 'chart' ? renderValueChart(userId) : renderFishMarket(userId)); } if (action === 'fishpage') { await interaction.showModal(pageModal('fish', userId, parts[3] || 1, parts[4] || 1)); return true; } if (action === 'itempage') { await interaction.showModal(pageModal('item', userId, parts[3] || 1, parts[4] || 1)); return true; } if (action === 'chartpage') { await interaction.showModal(pageModal('chart', userId, parts[4] || 1, parts[5] || 1, `:${parts[3] || 'fish'}`)); return true; } if (action === 'fishpagesubmit' && interaction.isModalSubmit?.()) return updateInteraction(interaction, renderFishMarket(userId, Number(fieldValue(interaction, 'fm_fish_page')))); if (action === 'itempagesubmit' && interaction.isModalSubmit?.()) return updateInteraction(interaction, renderItemMarket(userId, Number(fieldValue(interaction, 'fm_item_page')))); if (action === 'chartpagesubmit' && interaction.isModalSubmit?.()) return updateInteraction(interaction, renderValueChart(userId, parts[3] || 'fish', Number(fieldValue(interaction, 'fm_chart_page')))); if (action === 'sellfish') return updateInteraction(interaction, renderFishMarket(userId, parts[4] || 1, sellFish(userId, parts[3]))); if (action === 'sellitem') return updateInteraction(interaction, renderItemMarket(userId, parts[4] || 1, sellItem(userId, parts[3]))); if (action === 'sellfilter') { await interaction.showModal(filterForm('fish', userId)); return true; } if (action === 'itemfilter') { await interaction.showModal(filterForm('item', userId)); return true; } if (action === 'sellfiltersubmit' && interaction.isModalSubmit?.()) return updateInteraction(interaction, sellByRarity(userId, 'fish', selectedValues(interaction, 'fish_rarities'))); if (action === 'itemfiltersubmit' && interaction.isModalSubmit?.()) return updateInteraction(interaction, sellByRarity(userId, 'item', selectedValues(interaction, 'item_rarities'))); if (action === 'charttoggle') return updateInteraction(interaction, renderValueChart(userId, parts[3] === 'fish' ? 'item' : 'fish')); if (action === 'chartcheck') return updateInteraction(interaction, renderValueChart(userId, parts[3], parts[5], parts[4])); return false; }
const fishyMarketCommand = { data: new SlashCommandBuilder().setName('fishy-market').setDescription('Open the Fishy Market'), suppressCommandLog: true, disableActionTimeout: true, async execute(interaction) { await interaction.reply(renderHome(interaction.user.id)); }, async handleInteraction(interaction) { return handleMarketInteraction(interaction); } };
const inventoryCommand = { ...featureInventoryCommand, disableActionTimeout: false, async handleInteraction(interaction, client) { const handled = await handleMarketInteraction(interaction); if (handled) return true; return featureInventoryCommand.handleInteraction?.(interaction, client) || false; } };
const fishBarrelCommand = { ...featureFishBarrelCommand, disableActionTimeout: false, async execute(interaction) { await interaction.reply(renderFishMarket(interaction.user.id)); }, async handleInteraction(interaction, client) { const handled = await handleMarketInteraction(interaction); if (handled) return true; return featureFishBarrelCommand.handleInteraction?.(interaction, client) || false; } };
module.exports = { fishyMarketCommand, inventoryCommand, fishBarrelCommand };