const fs=require('fs'),path=require('path');
const{AttachmentBuilder,MessageFlags,SlashCommandBuilder}=require('discord.js');
const{createCanvas,loadImage}=require('@napi-rs/canvas');
const FLAGS=MessageFlags.IsComponentsV2??32768,EPH=MessageFlags.Ephemeral??64,WHITE=0xffffff,STORE=path.join(__dirname,'..','data','fishing-game.json'),DIR=path.join(__dirname,'Fish Png'),PER=6;
const R={common:'<:SBCommon:1506965202585780274>',uncommon:'<:SBUncommon:1506965215743447040>',rare:'<:SBRare:1506965211607994461>',epic:'<:SBEpic:1506965204624474153>',legendary:'<:SBLegendary:1506965206197207131>',mythical:'<:SBMythical:1506965209271762954>',secret:'<:SBSecret:1506965213881307186>'};
function nid(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')}function strip(v){return String(v||'').replace(/\bF[1-7]\s+(?=[A-Z])/g,'')}
const F=[['<:F1Bluegill:1506653228245455039>','F1 Bluegill','common'],['<:F1CommonCarp:1506653230376030318>','F1 Common Carp','common'],['<:F1FatheadMinnow:1506653232146022531>','F1 Fathead Minnow','common'],['<:F1YellowPerch:1506653234419466290>','F1 Yellow Perch','common'],['<:F2BlackCrappie:1506653236512166019>','F2 Black Crappie','uncommon'],['<:F2ChannelCatfish:1506653238605254798>','F2 Channel Catfish','uncommon'],['<:F2RainbowTrout:1506653240756801708>','F2 Rainbow Trout','uncommon'],['<:F3LargemouthBass:1506653242506088478>','F3 Largemouth Bass','rare'],['<:F3Walleye:1506653246255792198>','F3 Walleye','rare'],['<:F4NorthernPike:1506653248147292290>','F4 Northern Pike','epic'],['<:F5LakeSturgeon:1506653250621935827>','F5 Lake Sturgeon','legendary'],['<:F6GoldenMahseer:1506653252530212975>','F6 Golden Mahseer','mythical'],['<:F7AsianArowana:1506653254677954700>','F7 Asian Arowana','secret']].map(([emoji,name,rarity])=>({id:nid(name),emoji,name,displayName:strip(name),rarity,category:'Calm Fishing Lake'}));
const C=[{label:'All',value:'all'},{label:'Calm Fishing Lake',value:'calm_fishing_lake'}];
function empty(){return{users:{},weather:{},forecasts:{}}}function load(){const d=path.dirname(STORE);if(!fs.existsSync(d))fs.mkdirSync(d,{recursive:true});if(!fs.existsSync(STORE))fs.writeFileSync(STORE,JSON.stringify(empty(),null,2));try{return{...empty(),...JSON.parse(fs.readFileSync(STORE,'utf8'))}}catch{return empty()}}function user(s,id){if(!s.users[id])s.users[id]={fishCoins:0,inventory:{},fishBarrel:[],fishCapacity:10,fishIndex:{}};const u=s.users[id];u.fishBarrel=Array.isArray(u.fishBarrel)?u.fishBarrel:[];u.fishIndex=u.fishIndex&&typeof u.fishIndex==='object'?u.fishIndex:{};return u}
function list(cat){return cat==='calm_fishing_lake'?F.filter(f=>f.category==='Calm Fishing Lake'):F}function label(cat){return C.find(x=>x.value===cat)?.label||'All'}function discovered(u){const s=new Set(Object.keys(u.fishIndex||{}));for(const e of u.fishBarrel||[])if(e?.fishId)s.add(e.fishId);return s}function page(a,p){const m=Math.max(1,Math.ceil(a.length/PER)),n=Math.max(1,Math.min(m,Math.floor(Number(p)||1)));return{page:n,maxPage:m,items:a.slice((n-1)*PER,n*PER)}}
function sep(){return{type:14,divider:true,spacing:1}}function row(c){return{type:1,components:c}}function cont(cs,files=[]){return{flags:FLAGS,files,components:[{type:17,accent_color:WHITE,components:cs.filter(Boolean)}]}}function actions(id,p,cat){return row([{type:3,custom_id:`fishindex:action:${id}:${p}:${cat}`,placeholder:'Select an action',min_values:1,max_values:1,options:[{label:'Switch Page',value:'page'},{label:'Switch Category',value:'category'}]}])}
function txt(id,label,ph){return{type:1,components:[{type:4,custom_id:id,label,style:1,required:true,placeholder:ph,max_length:100}]}}function pageModal(id,p,m,cat){return{custom_id:`fishindex:pagesubmit:${id}:${cat}`,title:'Switch page',components:[txt('fish_index_page','Which page?',`1 - ${m}: Current page ${p}`)]}}function catModal(id,p,cat){return{custom_id:`fishindex:categorysubmit:${id}:${p}`,title:'Switch category',components:[{type:18,label:'Select a category',component:{type:3,custom_id:'fish_index_category',placeholder:'Select a category',min_values:1,max_values:1,options:C.map(o=>({...o,default:o.value===cat}))}}]}}
function imgPath(name){if(!fs.existsSync(DIR))return null;const n=nid(name).replace(/_/g,'');for(const f of fs.readdirSync(DIR)){if(path.extname(f).toLowerCase()!=='.png')continue;if(nid(path.basename(f,'.png')).replace(/_/g,'')===n)return path.join(DIR,f)}return null}function emojiUrl(e){const m=String(e||'').match(/<a?:([a-zA-Z0-9_]+):(\d+)>/);return m?`https://cdn.discordapp.com/emojis/${m[2]}.${String(e).startsWith('<a:')?'gif':'png'}?quality=lossless`:null}async function drawEmoji(ctx,e,x,y,s){try{const u=emojiUrl(e);if(!u)return false;const im=await loadImage(u);ctx.drawImage(im,x,y,s,s);return true}catch{return false}}
function rr(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}function fit(ctx,t,w,sz,wt='800'){for(let s=sz;s>=14;s--){ctx.font=`${wt} ${s}px sans-serif`;if(ctx.measureText(t).width<=w)return s}return 14}
async function gallery(items,seen){const cv=createCanvas(900,600),ctx=cv.getContext('2d');ctx.fillStyle='#181820';ctx.fillRect(0,0,900,600);const gap=24,cw=(900-gap*4)/3,ch=(600-gap*3)/2;for(let i=0;i<items.length;i++){const f=items[i],ok=seen.has(f.id),x=gap+(i%3)*(cw+gap),y=gap+Math.floor(i/3)*(ch+gap);ctx.fillStyle=ok?'#292936':'#22222c';rr(ctx,x,y,cw,ch,18);ctx.fill();ctx.strokeStyle=ok?'#5a5a70':'#444454';ctx.lineWidth=3;ctx.stroke();const g=ctx.createLinearGradient(x,y,x,y+ch);g.addColorStop(0,'rgba(255,255,255,.08)');g.addColorStop(1,'rgba(0,0,0,.12)');ctx.fillStyle=g;rr(ctx,x+3,y+3,cw-6,ch-6,15);ctx.fill();ctx.fillStyle='#1e1e29';rr(ctx,x+cw-52,y+12,36,36,12);ctx.fill();if(!await drawEmoji(ctx,R[f.rarity],x+cw-46,y+18,24)){ctx.font='22px sans-serif';ctx.textAlign='center';ctx.fillStyle='#fff';ctx.fillText('★',x+cw-34,y+39)}const title=ok?f.displayName:'Undiscovered';ctx.font=`800 ${fit(ctx,title,cw-76,25)}px sans-serif`;ctx.textAlign='center';ctx.fillStyle=ok?'#f6f6ff':'#8c8c9a';ctx.fillText(title,x+cw/2-10,y+38);if(ok){try{const p=imgPath(f.name);if(p){const im=await loadImage(p);ctx.drawImage(im,x+cw/2-58,y+66,116,116)}else await drawEmoji(ctx,f.emoji,x+cw/2-38,y+78,76)}catch{ctx.font='56px sans-serif';ctx.fillText('🐟',x+cw/2,y+140)}}else{ctx.font='900 78px sans-serif';ctx.fillStyle='#5f6070';ctx.fillText('?',x+cw/2,y+148)}ctx.font='700 18px sans-serif';ctx.fillStyle=ok?'#aeb0bd':'#6f7080';ctx.fillText(ok?'Discovered':'Not discovered',x+cw/2,y+ch-28)}return cv.toBuffer('image/png')}
async function render(id,name,p=1,cat='all'){const s=load(),u=user(s,id),fish=list(cat),seen=discovered(u),pg=page(fish,p),buf=await gallery(pg.items,seen),att=new AttachmentBuilder(buf,{name:'fish-index.png'}),count=fish.filter(f=>seen.has(f.id)).length;return cont([{type:10,content:`## ${name}'s Fish Index\n-# Fish discovered: ${count} / ${fish.length}\n-# Category: ${label(cat)}`},sep(),{type:12,items:[{media:{url:'attachment://fish-index.png'}}]},sep(),actions(id,pg.page,cat)],[att])}
function val(inter,id){try{return inter.fields?.getTextInputValue?.(id)||''}catch{}const stack=[...(inter.components??inter.data?.components??[])];while(stack.length){const it=stack.shift(),c=it?.component??it;if(c?.customId===id||c?.custom_id===id){const v=c.values??c.value;return Array.isArray(v)?v[0]:(v||'')}if(Array.isArray(it?.components))stack.push(...it.components);if(Array.isArray(c?.components))stack.push(...c.components)}return''}function owner(i,id){if(i.user.id===id)return true;i.reply({content:'Only the command owner can use this control.',flags:EPH}).catch(()=>null);return false}async function upd(i,p){if(typeof i.update==='function')return i.update(p);if(typeof i.deferUpdate==='function'){await i.deferUpdate();return i.message?.edit(p)}return i.reply(p)}
async function handle(i){const id=i.customId||'';if(!id.startsWith('fishindex:'))return false;const parts=id.split(':'),a=parts[1],uid=parts[2];if(!owner(i,uid))return true;if(a==='action'&&i.isStringSelectMenu?.()){const p=Number(parts[3])||1,cat=parts[4]||'all',m=page(list(cat),p).maxPage;if(i.values?.[0]==='page')await i.showModal(pageModal(uid,p,m,cat));else await i.showModal(catModal(uid,p,cat));return true}if(a==='pagesubmit'&&i.isModalSubmit?.())return upd(i,await render(uid,i.user.username,Number(val(i,'fish_index_page'))||1,parts[3]||'all'));if(a==='categorysubmit'&&i.isModalSubmit?.()){const selected=val(i,'fish_index_category')||'all';return upd(i,await render(uid,i.user.username,1,C.some(o=>o.value===selected)?selected:'all'))}return false}
const fishIndexCommand={data:new SlashCommandBuilder().setName('fish-index').setDescription('Show your discovered fish index'),suppressCommandLog:true,disableActionTimeout:true,async execute(i){await i.reply(await render(i.user.id,i.user.username))},async handleInteraction(i){return handle(i)}};
module.exports={fishIndexCommand};
