const fs = require('node:fs');
const https = require('node:https');
const path = require('node:path');

const EMOJI_VERSION = '17.0';
const SOURCE_URL = 'https://unicode.org/Public/emoji/latest/emoji-test.txt';
const OUTPUT_PATH = path.join(__dirname, '..', 'admin', 'emojiData.js');
const CATEGORIES = Object.freeze([
  { id: 'smileys-people', name: 'Smileys & People', icon: '😀', sourceGroups: ['Smileys & Emotion', 'People & Body'] },
  { id: 'animals-nature', name: 'Animals & Nature', icon: '🌿', sourceGroups: ['Animals & Nature'] },
  { id: 'food-drink', name: 'Food & Drink', icon: '🍜', sourceGroups: ['Food & Drink'] },
  { id: 'activities', name: 'Activities', icon: '🎮', sourceGroups: ['Activities'] },
  { id: 'travel-places', name: 'Travel & Places', icon: '🚲', sourceGroups: ['Travel & Places'] },
  { id: 'objects', name: 'Objects', icon: '💡', sourceGroups: ['Objects'] },
  { id: 'symbols', name: 'Symbols', icon: '♥️', sourceGroups: ['Symbols'] },
  { id: 'flags', name: 'Flags', icon: '⚑', sourceGroups: ['Flags'] },
]);

function fetchText(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (response) => {
      if (response.statusCode >= 300 && response.statusCode < 400 && response.headers.location) {
        response.resume();
        fetchText(new URL(response.headers.location, url).href).then(resolve, reject);
        return;
      }
      if (response.statusCode !== 200) {
        response.resume();
        reject(new Error(`Unicode data request failed with HTTP ${response.statusCode}.`));
        return;
      }
      response.setEncoding('utf8');
      let body = '';
      response.on('data', (chunk) => { body += chunk; });
      response.on('end', () => resolve(body));
    }).on('error', reject);
  });
}

function parseEmojiTest(source) {
  const versionMatch = source.match(/^# Version: (.+)$/m);
  if (versionMatch?.[1] !== EMOJI_VERSION) {
    throw new Error(`Expected Unicode Emoji ${EMOJI_VERSION}, received ${versionMatch?.[1] || 'an unknown version'}.`);
  }
  const groups = CATEGORIES.map(({ sourceGroups, ...category }) => ({ ...category, emojis: [] }));
  let activeGroup = null;
  for (const line of source.split(/\r?\n/)) {
    const groupMatch = line.match(/^# group: (.+)$/);
    if (groupMatch) {
      const category = CATEGORIES.find((entry) => entry.sourceGroups.includes(groupMatch[1]));
      activeGroup = category ? groups.find((entry) => entry.id === category.id) : null;
      continue;
    }
    if (!activeGroup || !line.includes('; fully-qualified')) continue;
    const emojiMatch = line.match(/^([0-9A-F ]+)\s*;\s*fully-qualified\s*#\s*(\S+)\s+E[\d.]+\s+(.+)$/u);
    if (!emojiMatch) continue;
    activeGroup.emojis.push([emojiMatch[2], emojiMatch[3]]);
  }
  const emojiCount = groups.reduce((total, group) => total + group.emojis.length, 0);
  if (groups.length !== CATEGORIES.length || emojiCount < 3000) {
    throw new Error(`Unexpected Unicode emoji data: ${groups.length} groups and ${emojiCount} emojis.`);
  }
  return { version: EMOJI_VERSION, emojiCount, groups };
}

async function main() {
  const source = await fetchText(SOURCE_URL);
  const data = parseEmojiTest(source);
  const serialized = JSON.stringify(data).replaceAll('\u2028', '\\u2028').replaceAll('\u2029', '\\u2029');
  const output = `/* Generated by scripts/generateEmojiData.js from Unicode Emoji ${EMOJI_VERSION} emoji-test.txt.\n`
    + ' * Unicode data terms: https://www.unicode.org/terms_of_use.html\n'
    + ' */\n(() => {\n  \'use strict\';\n  window.COINSPRITE_EMOJI_DATA = '
    + `${serialized};\n})();\n`;
  fs.writeFileSync(OUTPUT_PATH, output, 'utf8');
  console.log(`Wrote ${data.emojiCount} emojis across ${data.groups.length} groups to ${OUTPUT_PATH}.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
