const MAX_LUCK_MULTIPLIER = 50;
const MAX_LUCK_TIER = MAX_LUCK_MULTIPLIER - 1;
const BIG_CROP_CHANCE_PER_TIER = 0.001;
const BIG_CROP_CHANCE_UNITS_PER_TIER = 1;
const BIG_CROP_CHANCE_DENOMINATOR = 1_000;
const MAX_BIG_CROP_CHANCE = 0.05;
const MAX_BIG_CROP_TIER = 50;

module.exports = Object.freeze({
  BIG_CROP_CHANCE_DENOMINATOR,
  BIG_CROP_CHANCE_PER_TIER,
  BIG_CROP_CHANCE_UNITS_PER_TIER,
  MAX_BIG_CROP_CHANCE,
  MAX_BIG_CROP_TIER,
  MAX_LUCK_MULTIPLIER,
  MAX_LUCK_TIER,
});
