function extractEmojiName(emoji) {
  const match = emoji?.match(/^<a?:([^:]+):\d+>$/);
  return match?.[1] ?? null;
}

const ITEMS = [
  {
    id: 'ITFist',
    name: 'Fist',
    emoji: '<:ITFist:1449009707355476069>',
    image: 'https://i.ibb.co/WNkCYjCT/ITFist.png',
    rarity: 'Common',
    type: 'Tool/Gear',
    activityTags: ['hunt', 'dig'],
    value: 0,
    sellPrice: 0,
    tradable: false,
    durability: Infinity,
    maxDurability: Infinity,
    damage: { min: 1, max: 5 },
    info: 'Useable as a gear in Hunt, deal 1 - 5 damages per hit.',
    obtainment: 'Obtainment: Starter gear that is always available when you have no weapon equipped.',
    usage: 'Usage: Equip as basic hunt gear to strike for 1-5 damage without consuming durability.',
  },
  {
    id: 'ITWoodenSword',
    name: 'Wooden Sword',
    emoji: '<:ITWoodenSword:1448987035363704955>',
    image: 'https://i.ibb.co/CpQxNy3t/ITWooden-Sword.png',
    rarity: 'Common',
    type: 'Tool/Gear',
    activityTags: ['hunt', 'dig'],
    value: 13,
    sellPrice: 100,
    tradable: true,
    durability: 50,
    maxDurability: 50,
    damage: { min: 3, max: 8 },
    info: 'Useable as a gear in Hunt, deal 3 - 8 damages per hit. Lose 1 durability per hit.',
    obtainment: 'Obtainment: Unknown.',
    usage: 'Usage: Equip as hunt gear to hit for 3-8 damage per action while consuming 1 durability each swing.',
  },
  {
    id: 'ITHuntUpgradeToken',
    name: 'Hunt Upgrade Token',
    emoji: '<:ITHuntUpgradeToken:1452674049984430141>',
    image: 'https://i.ibb.co/GQqmgRP1/ITHunt-Upgrade-Token.png',
    rarity: 'Rare',
    type: 'Material',
    value: 0,
    sellPrice: null,
    tradable: false,
    durability: null,
    info: 'Earned from hunt leveling.',
    obtainment:
      'Obtainment: Earn 1 Hunt Upgrade Token automatically each time your Hunt level increases (granted when profiles are refreshed).',
    usage:
      'Usage: Spend in the /my-upgrades hunt menu to unlock Hunt XP, item luck, creature luck, dungeon token chance, crit chance, and crit damage tiers.',
  },
  {
    id: 'ITChatUpgradeToken',
    name: 'Chat Upgrade Token',
    emoji: '<:ITChatUpgradeToken:1452674047304532102>',
    image: 'https://i.ibb.co/jZZ1sbRh/ITChat-Upgrade-Token.png',
    rarity: 'Rare',
    type: 'Material',
    value: 0,
    sellPrice: null,
    tradable: false,
    durability: null,
    info: 'Earned from chat leveling.',
    obtainment:
      'Obtainment: Earn 1 Chat Upgrade Token automatically each time your Chat level increases (synced when user stats are refreshed).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITDungeonToken',
    name: 'Dungeon Token',
    emoji: '<:ITDungeonToken:1451523217511677963>',
    image: 'https://i.ibb.co/CKkPCJq0/ITDungeon-Token.png',
    rarity: 'Legendary',
    type: 'Material',
    value: 1500,
    sellPrice: null,
    tradable: true,
    durability: null,
    info: 'A token required to enter a dungeon.',
    obtainment:
      'Obtainment: Drops from all hunt creatures with three rolls: 1 token at 1% chance, 2 tokens at 0.2% chance, and 3 tokens at 0.06% chance.',
    usage: 'Usage: Spend 1 token to enter Dungeon Stage 1-1; consumed when starting the stage.',
  },
  {
    id: 'ITBeastMeat',
    name: 'Beast Meat',
    emoji: '<:ITBeastMeat:1449725581217501340>',
    image: 'https://i.ibb.co/bRKyFZhj/ITBeast-Meat.png',
    rarity: 'Common',
    type: 'Material',
    value: 8,
    sellPrice: 8,
    tradable: true,
    durability: null,
    info: 'A chunk of raw beast meat dropped from jungle beetles.',
    obtainment:
      'Obtainment: Hunt drops—55% (Mossback Monkey, Mudscale Lizard), 60% (Thornback Boar, Bristle Jaguar, Sporeback Tortoise, Rooted Ape, Thunderfang Panther, Ancient Horned Gorilla), 40% (Jungle Beetle), 45% (Leaf Frog), 65% (Solar Jaguar), and 100% from Corrupted Cube (15-30 meat). First-clear dungeon reward grants 20 from Stage 1-1.',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITMossyShavings',
    name: 'Mossy Shavings',
    emoji: '<:ITMossyShavings:1449725583884812338>',
    image: 'https://i.ibb.co/DDzv6T79/ITMossy-Shavings.png',
    rarity: 'Common',
    type: 'Material',
    value: 23,
    sellPrice: 23,
    tradable: true,
    durability: null,
    info: 'Damp moss scraps collected from jungle beetles.',
    obtainment:
      'Obtainment: Hunt drops—40% (Mossback Monkey), 25% (Jungle Beetle), 50% (Sporeback Tortoise), 55% (Vine Titan). First-clear dungeon reward grants 10 from Stage 1-1.',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITVineFiber',
    name: 'Vine Fiber',
    emoji: '<:ITVineFiber:1450771201097207871>',
    image: 'https://i.ibb.co/Jwp73BSp/ITVine-Fiber.png',
    rarity: 'Common',
    type: 'Material',
    value: 6,
    sellPrice: 150,
    tradable: true,
    durability: null,
    info: 'A fibrous strand pulled from a vine snake.',
    obtainment:
      'Obtainment: Hunt drops—50% (Vine Snake), 45% (Rooted Ape), 60% (Bloom Serpent), 60% (Vine Titan). First-clear dungeon reward grants 8 from Stage 1-1.',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITSharpFang',
    name: 'Sharp Fang',
    emoji: '<:ITSharpFang:1450765103250149448>',
    image: 'https://i.ibb.co/zWCTPNwV/ITSharp-Fang.png',
    rarity: 'Common',
    type: 'Material',
    value: 35,
    sellPrice: 500,
    tradable: true,
    durability: null,
    info: 'A razor-edged fang harvested from dangerous predators.',
    obtainment:
      'Obtainment: Hunt drops—10% (Vine Snake), 35% (Bristle Jaguar), 40% (Thunderfang Panther), 25% (Bloom Serpent), 40% (Emerald Stalker), 45% (Solar Jaguar).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITWeakVenomGland',
    name: 'Weak Venom Gland',
    emoji: '<:ITWeakVenomGland:1450771203823370260>',
    image: 'https://i.ibb.co/B5sZJyS3/ITWeak-Venom-Gland.png',
    rarity: 'Common',
    type: 'Material',
    value: 12,
    sellPrice: 300,
    tradable: true,
    durability: null,
    info: 'A venom sac still brimming with diluted toxins.',
    obtainment:
      'Obtainment: Hunt drops—45% (Vine Snake), 40% (Leaf Frog), 45% (Mudscale Lizard).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITJungleFeather',
    name: 'Jungle Feather',
    emoji: '<:ITJungleFeather:1451102919003865108>',
    image: 'https://i.ibb.co/cKBpGXvF/ITJungle-Feather.png',
    rarity: 'Common',
    type: 'Material',
    value: 20,
    sellPrice: 100,
    tradable: true,
    durability: null,
    info: 'A glossy feather shed by birds in the jungle canopy.',
    obtainment:
      'Obtainment: Hunt drops—50% (Clawfoot Bird), 65% (Razorwing Parrot), 65% (Storm Canopy Eagle).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITRazorTalon',
    name: 'Razor Talon',
    emoji: '<:ITRazorTalon:1451102921323450532>',
    image: 'https://i.ibb.co/7NpMM86N/ITRazor-Talon.png',
    rarity: 'Common',
    type: 'Material',
    value: 50,
    sellPrice: 300,
    tradable: true,
    durability: null,
    info: 'A razor-sharp talon prized for crafting.',
    obtainment:
      'Obtainment: Hunt drops—35% (Clawfoot Bird), 45% (Razorwing Parrot), 45% (Storm Canopy Eagle).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITHeavyHornFragment',
    name: 'Heavy Horn Fragment',
    emoji: '<:ITHeavyHornFragment:1451103660099637320>',
    image: 'https://i.ibb.co/TM2KXF4n/ITHeavy-Horn-Fragment.png',
    rarity: 'Common',
    type: 'Material',
    value: 120,
    sellPrice: 900,
    tradable: true,
    durability: null,
    info: 'A heavy shard chipped from a thornback boar horn.',
    obtainment:
      'Obtainment: Hunt drops—8% (Thornback Boar), 30% (Ancient Horned Gorilla).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITToughHideScrap',
    name: 'Tough Hide Scrap',
    emoji: '<:ITToughHideScrap:1451103661991268416>',
    image: 'https://i.ibb.co/231kDHJy/ITTouch-Hide-Scrap.png',
    rarity: 'Common',
    type: 'Material',
    value: 40,
    sellPrice: 250,
    tradable: true,
    durability: null,
    info: 'A tough hide scrap used for rugged gear.',
    obtainment:
      'Obtainment: Hunt drops—50% (Thornback Boar), 55% (Bristle Jaguar), 50% (Rooted Ape), 55% (Thunderfang Panther), 55% (Ancient Horned Gorilla).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITWorldrootFragment',
    name: 'Worldroot Fragment',
    emoji: '<:ITWorldrootFragment:1451534950498046033>',
    image: 'https://i.ibb.co/JR5QjG3c/ITWorldroot-Fragment.png',
    rarity: 'Rare',
    type: 'Material',
    value: 206,
    sellPrice: 206,
    tradable: true,
    durability: null,
    info: 'A rare fragment pulsing with primal root energy.',
    obtainment:
      'Obtainment: Hunt drops—3% (Rooted Ape), 25% (Totem Guardian), 15% (Vine Titan).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITAncientJungleTablet',
    name: 'Ancient Jungle Tablet',
    emoji: '<:ITAncientJungleTablet:1452295245098182336>',
    image: 'https://i.ibb.co/qMxm7QdT/ITAncient-Jungle-Tablet.png',
    rarity: 'Epic',
    type: 'Material',
    value: 900,
    sellPrice: 900,
    tradable: true,
    durability: null,
    info: 'A moss-laced tablet etched with ancient jungle runes.',
    obtainment: 'Obtainment: Unknown.',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITResinLump',
    name: 'Resin Lump',
    emoji: '<:ITResinLump:1451534945939099789>',
    image: 'https://i.ibb.co/jZgMyJb2/ITResin-Lump.png',
    rarity: 'Common',
    type: 'Material',
    value: 80,
    sellPrice: 80,
    tradable: true,
    durability: null,
    info: 'A sticky lump of hardened jungle resin.',
    obtainment: 'Obtainment: Hunt drop—40% (Mudscale Lizard); 45% (Vine Titan).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITBurrowerScale',
    name: 'Burrower Scale',
    emoji: '<:ITBurrowerScale:1451532823470014515>',
    image: 'https://i.ibb.co/GKtqymk/ITBurrower-Scale.png',
    rarity: 'Common',
    type: 'Material',
    value: 150,
    sellPrice: 150,
    tradable: true,
    durability: null,
    info: 'A rough scale shed by burrowing reptiles.',
    obtainment: 'Obtainment: Hunt drops—18% (Mudscale Lizard), 20% (Emerald Stalker).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITRazorfeatherQuill',
    name: 'Razorfeather Quill',
    emoji: '<:ITRazorfeatherQuill:1451532989036232804>',
    image: 'https://i.ibb.co/S79MQ7CB/ITRazorfeather-Quill.png',
    rarity: 'Common',
    type: 'Material',
    value: 120,
    sellPrice: 120,
    tradable: true,
    durability: null,
    info: 'A razor-edged quill prized by fletchers.',
    obtainment:
      'Obtainment: Hunt drops—20% (Razorwing Parrot), 28% (Storm Canopy Eagle).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITHunterPeltStrip',
    name: 'Hunter Pelt Strip',
    emoji: '<:ITHunterPeltStrip:1451533239050178621>',
    image: 'https://i.ibb.co/Tqm0VCnL/ITHunter-Pelt-Strip.png',
    rarity: 'Common',
    type: 'Material',
    value: 123,
    sellPrice: 123,
    tradable: true,
    durability: null,
    info: 'A sturdy pelt strip used for field gear.',
    obtainment:
      'Obtainment: Hunt drops—18% (Bristle Jaguar), 25% (Thunderfang Panther), 25% (Emerald Stalker).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITJaguarSoulFang',
    name: 'Jaguar Soul Fang',
    emoji: '<:ITJaguarSoulFang:1451534939609628692>',
    image: 'https://i.ibb.co/m5Thm8pj/ITJaguar-Soul-Fang.png',
    rarity: 'Common',
    type: 'Material',
    value: 188,
    sellPrice: 188,
    tradable: true,
    durability: null,
    info: 'A spiritual fang humming with jaguar power.',
    obtainment: 'Obtainment: Hunt drops—5% (Bristle Jaguar), 18% (Solar Jaguar).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITBeetleCarapaceShard',
    name: 'Beetle Carapace Shard',
    emoji: '<:ITBeetleCarapaceShard:1451533534345822228>',
    image: 'https://i.ibb.co/Kx3292jS/ITBeetle-Carapace-Shard.png',
    rarity: 'Common',
    type: 'Material',
    value: 100,
    sellPrice: 100,
    tradable: true,
    durability: null,
    info: 'A glossy shard chipped from a beetle shell.',
    obtainment:
      'Obtainment: Hunt drops—55% (Jungle Beetle), 60% (Sporeback Tortoise).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITPoisonSporeCluster',
    name: 'Poison Spore Cluster',
    emoji: '<:ITPoisonSporeCluster:1451534943455809679>',
    image: 'https://i.ibb.co/FbsvgQfX/ITPoison-Spore-Cluster.png',
    rarity: 'Common',
    type: 'Material',
    value: 127,
    sellPrice: 127,
    tradable: true,
    durability: null,
    info: 'A toxic spore cluster harvested from fungus shells.',
    obtainment:
      'Obtainment: Hunt drops—35% (Sporeback Tortoise), 45% (Bloom Serpent).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITShellguardPlate',
    name: 'Shellguard Plate',
    emoji: '<:ITShellguardPlate:1451533859773485139>',
    image: 'https://i.ibb.co/nNntF4JW/ITShellguard-Plate.png',
    rarity: 'Common',
    type: 'Material',
    value: 153,
    sellPrice: 153,
    tradable: true,
    durability: null,
    info: 'A dense plate taken from a hardened shell.',
    obtainment: 'Obtainment: Hunt drops—18% (Sporeback Tortoise), 25% (Vine Titan).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITRootbindingSplinter',
    name: 'Rootbinding Splinter',
    emoji: '<:ITRootbindingSplinter:1451534948304687166>',
    image: 'https://i.ibb.co/xtpNq6Xn/ITRootbinding-Splinter.png',
    rarity: 'Common',
    type: 'Material',
    value: 169,
    sellPrice: 169,
    tradable: true,
    durability: null,
    info: 'A splinter that still pulses with binding roots.',
    obtainment: 'Obtainment: Hunt drops—15% (Rooted Ape), 50% (Totem Guardian), 35% (Vine Titan).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITStormCoreShard',
    name: 'Storm Core Shard',
    emoji: '<:ITStormCoreShard:1452566937904349304>',
    image: 'https://i.ibb.co/5WR9bK7f/ITStorm-Core-Shard.png',
    rarity: 'Epic',
    type: 'Material',
    value: 735,
    sellPrice: 735,
    tradable: true,
    durability: null,
    info: 'A crackling shard humming with storm energy.',
    obtainment:
      'Obtainment: Hunt drops—18% (Thunderfang Panther), 22% (Storm Canopy Eagle).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITThundertraceClawband',
    name: 'Thundertrace Clawband',
    emoji: '<:ITThundertraceClawband:1452566940005695638>',
    image: 'https://i.ibb.co/99fqqML0/ITThundertrace-Clawband.png',
    rarity: 'Rare',
    type: 'Material',
    value: 240,
    sellPrice: 240,
    tradable: true,
    durability: null,
    info: 'A braided clawband that tingles with static power.',
    obtainment:
      'Obtainment: Hunt drops—7% (Thunderfang Panther), 10% (Storm Canopy Eagle), 15% (Solar Jaguar).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITBloomPetalCluster',
    name: 'Bloom Petal Cluster',
    emoji: '<:ITBloomPetalCluster:1452566931046400024>',
    image: 'https://i.ibb.co/QvRLmjxk/ITBloom-Petal-Cluster.png',
    rarity: 'Epic',
    type: 'Material',
    value: 815,
    sellPrice: 815,
    tradable: true,
    durability: null,
    info: 'A fragrant bundle of petals that still drips with sap.',
    obtainment: 'Obtainment: Hunt drops—22% (Bloom Serpent), 45% (Phantom Orchid Warden).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITSpiritMistEssence',
    name: 'Spirit Mist Essence',
    emoji: '<:ITSpiritMistEssence:1452567913965027509>',
    image: 'https://i.ibb.co/gL0gtDC1/ITSpirit-Mist-Essence.png',
    rarity: 'Epic',
    type: 'Material',
    value: 894,
    sellPrice: 894,
    tradable: true,
    durability: null,
    info: 'A vial of misty essence gathered from spectral groves.',
    obtainment: 'Obtainment: Hunt drops—20% (Emerald Stalker), 30% (Phantom Orchid Warden).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITWardenVeilShard',
    name: "Warden's Veil Shard",
    emoji: '<:ITWardenVeilShard:1452567920520462460>',
    image: 'https://i.ibb.co/6cNrxfn7/ITWarden-Veil-Shard.png',
    rarity: 'Legendary',
    type: 'Material',
    value: 1125,
    sellPrice: 1125,
    tradable: true,
    durability: null,
    info: 'A rare shard that still echoes with warding power.',
    obtainment:
      "Obtainment: Hunt drops—0.5% (Emerald Stalker), 1% (Phantom Orchid Warden).",
    usage: "Usage: Unknown.",
  },
  {
    id: 'ITTotemStoneChip',
    name: 'Totem Stone Chip',
    emoji: '<:ITTotemStoneChip:1452567916565369004>',
    image: 'https://i.ibb.co/LdSpGX8n/ITTotem-Stone-Chip.png',
    rarity: 'Rare',
    type: 'Material',
    value: 415,
    sellPrice: 415,
    tradable: true,
    durability: null,
    info: 'A chipped piece of totem stone, worn smooth by time.',
    obtainment: 'Obtainment: Hunt drops—40% (Totem Guardian), 35% (Ancient Horned Gorilla), 22% (Vine Titan).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITGuardianCore',
    name: 'Guardian Core',
    emoji: '<:ITGuardianCore:1452567911683326032>',
    image: 'https://i.ibb.co/3y9gnhb5/ITGuardian-Core.png',
    rarity: 'Epic',
    type: 'Material',
    value: 535,
    sellPrice: 535,
    tradable: true,
    durability: null,
    info: 'A condensed core of guardian energy.',
    obtainment: 'Obtainment: Hunt drops—18% (Totem Guardian), 20% (Ancient Horned Gorilla).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITSunfirePelt',
    name: 'Sunfire Pelt',
    emoji: '<:ITSunfirePelt:1452294850169929789>',
    image: 'https://i.ibb.co/SwNc4JhF/ITSunfire-Pelt.png',
    rarity: 'Rare',
    type: 'Material',
    value: 360,
    sellPrice: 360,
    tradable: true,
    durability: null,
    info: 'A radiant pelt that still feels warm to the touch.',
    obtainment: 'Obtainment: Hunt drop—4% (Solar Jaguar).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITSolarCore',
    name: 'Solar Core',
    emoji: '<:ITSolarCore:1452566935328784488>',
    image: 'https://i.ibb.co/jZhGwQmw/ITSolar-Core.png',
    rarity: 'Epic',
    type: 'Material',
    value: 600,
    sellPrice: 600,
    tradable: true,
    durability: null,
    info: 'A brilliant core pulsing with concentrated sunlight.',
    obtainment: 'Obtainment: Hunt drop—0.2% (Solar Jaguar).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITPhantomOrchidPetal',
    name: 'Phantom Orchid Petal',
    emoji: '<:ITPhantomOrchidPetal:1452566933437419662>',
    image: 'https://i.ibb.co/0pLcyjpv/ITPhantom-Orchid-Petal.png',
    rarity: 'Legendary',
    type: 'Material',
    value: 1300,
    sellPrice: 1300,
    tradable: true,
    durability: null,
    info: 'A pale orchid petal that feels cool to the touch.',
    obtainment: 'Obtainment: Hunt drop—4% (Phantom Orchid Warden).',
    usage: 'Usage: Unknown.',
  },
  {
    id: 'ITDirt',
    name: 'Dirt',
    emoji: '<:ITDirt:1453266098823757926>',
    image: 'https://i.ibb.co/mrty1V68/ITDirt.png',
    rarity: 'Common',
    type: 'Material',
    value: 5,
    sellPrice: 5,
    tradable: true,
    durability: null,
    info: 'Loose soil scooped up while digging.',
    obtainment: 'Obtainment: Guaranteed base drop from every dig action.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITBone',
    name: 'Bone',
    emoji: '<:ITBone:1453266094373601492>',
    image: 'https://i.ibb.co/LDsmg7Jn/ITBone.png',
    rarity: 'Common',
    type: 'Material',
    value: 25,
    sellPrice: 25,
    tradable: true,
    durability: null,
    info: 'A weathered bone uncovered underground.',
    obtainment: 'Obtainment: Dig drop—10% chance per dig roll.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITLeaf',
    name: 'Leaf',
    emoji: '<:ITLeaf:1453266100803469362>',
    image: 'https://i.ibb.co/xtY2k456/ITLeaf.png',
    rarity: 'Common',
    type: 'Material',
    value: 8,
    sellPrice: 8,
    tradable: true,
    durability: null,
    info: 'Fresh leaf scraps gathered while digging.',
    obtainment: 'Obtainment: Dig drop—55% chance per dig roll.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITFeather',
    name: 'Feathers',
    emoji: '<:ITFeather:1453266401585266789>',
    image: 'https://i.ibb.co/sdHM1Hf6/ITFeather.png',
    rarity: 'Common',
    type: 'Material',
    value: 10,
    sellPrice: 10,
    tradable: true,
    durability: null,
    info: 'Light feathers brushed up from the earth.',
    obtainment: 'Obtainment: Dig drop—35% chance per dig roll.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITClay',
    name: 'Clay',
    emoji: '<:ITClay:1453266096688992287>',
    image: 'https://i.ibb.co/1G9xvMKH/ITClay.png',
    rarity: 'Common',
    type: 'Material',
    value: 80,
    sellPrice: 80,
    tradable: true,
    durability: null,
    info: 'Dense clay packed tightly beneath the layers.',
    obtainment: 'Obtainment: Dig drop—8% chance per dig roll.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITPebbles',
    name: 'Pebbles',
    emoji: '<:ITPebbles:1453266102942564494>',
    image: 'https://i.ibb.co/nMsbY5ZL/ITPebbles.png',
    rarity: 'Common',
    type: 'Material',
    value: 50,
    sellPrice: 50,
    tradable: true,
    durability: null,
    info: 'Small, smooth stones uncovered while digging.',
    obtainment: 'Obtainment: Dig drop—25% chance per dig roll.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITTwigs',
    name: 'Twigs',
    emoji: '<:ITTwigs:1453266403321708616>',
    image: 'https://i.ibb.co/PGLCdpBP/ITTwigs.png',
    rarity: 'Common',
    type: 'Material',
    value: 35,
    sellPrice: 35,
    tradable: true,
    durability: null,
    info: 'Broken twigs tangled in the soil.',
    obtainment: 'Obtainment: Dig drop—25% chance per dig roll.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITStone',
    name: 'Stone',
    emoji: '<:ITStone:1453266104972742716>',
    image: 'https://i.ibb.co/kVmKCDx6/ITStone.png',
    rarity: 'Common',
    type: 'Material',
    value: 45,
    sellPrice: 45,
    tradable: true,
    durability: null,
    info: 'A rough stone fragment pried from the dirt.',
    obtainment: 'Obtainment: Dig drop—35% chance per dig roll.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITCoal',
    name: 'Coal',
    emoji: '<:ITCoal:1456945823302787013>',
    image: 'https://i.ibb.co/qYCh06W4/ITCoal.png',
    rarity: 'Common',
    type: 'Material',
    value: 35,
    sellPrice: 35,
    tradable: true,
    durability: null,
    info: 'A lump of coal mined from early stone layers.',
    obtainment: 'Obtainment: Found while mining stone layers 0-100.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITFossil',
    name: 'Fossil',
    emoji: '<:ITFossil:1456946059495640202>',
    image: 'https://i.ibb.co/k2rvZJgP/ITFossil.png',
    rarity: 'Common',
    type: 'Material',
    value: 50,
    sellPrice: 50,
    tradable: true,
    durability: null,
    info: 'Ancient remains preserved within the stone.',
    obtainment: 'Obtainment: Unearthed while mining stone layers 0-100.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITCopperOre',
    name: 'Copper Ore',
    emoji: '<:ITCopperOre:1456946823303278013>',
    image: 'https://i.ibb.co/rWmPvzC/ITCopper-Ore.png',
    rarity: 'Common',
    type: 'Material',
    value: 80,
    sellPrice: 80,
    tradable: true,
    durability: null,
    info: 'Unrefined copper ore ready for smelting.',
    obtainment: 'Obtainment: Discovered while mining stone layers 0-100.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITIronOre',
    name: 'Iron Ore',
    emoji: '<:ITIronOre:145694695713079382>',
    image: 'https://i.ibb.co/tMgL6ftX/ITIron-Ore.png',
    rarity: 'Common',
    type: 'Material',
    value: 120,
    sellPrice: 120,
    tradable: true,
    durability: null,
    info: 'Dense iron ore mined from stone.',
    obtainment: 'Obtainment: Found while mining stone layers 0-100.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITGoldOre',
    name: 'Gold Ore',
    emoji: '<:ITGoldOre:1456946937019709973>',
    image: 'https://i.ibb.co/chGv7Ch9/ITGold-Ore.png',
    rarity: 'Rare',
    type: 'Material',
    value: 250,
    sellPrice: 250,
    tradable: true,
    durability: null,
    info: 'A precious chunk of raw gold.',
    obtainment: 'Obtainment: Found while mining stone layers 0-100.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITAmethyst',
    name: 'Amethyst Ore',
    emoji: '<:ITAmethyst:1456946881091878754>',
    image: 'https://i.ibb.co/5hFjJpZg/ITAmethyst.png',
    rarity: 'Rare',
    type: 'Material',
    value: 300,
    sellPrice: 300,
    tradable: true,
    durability: null,
    info: 'A shimmering purple amethyst crystal.',
    obtainment: 'Obtainment: Discovered in deeper stone layers 51-100.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITSapphire',
    name: 'Sapphire Ore',
    emoji: '<:ITSapphire:1456946653562207787>',
    image: 'https://i.ibb.co/93djdBp3/ITSapphire.png',
    rarity: 'Rare',
    type: 'Material',
    value: 325,
    sellPrice: 325,
    tradable: true,
    durability: null,
    info: 'A deep-blue sapphire gemstone.',
    obtainment: 'Obtainment: Discovered in deeper stone layers 51-100.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITEmerald',
    name: 'Emerald Ore',
    emoji: '<:ITEmerald:1456946954599146555>',
    image: 'https://i.ibb.co/20TP3Qr9/ITEmerald.png',
    rarity: 'Epic',
    type: 'Material',
    value: 650,
    sellPrice: 650,
    tradable: true,
    durability: null,
    info: 'A vivid emerald gemstone pulled from the rock.',
    obtainment: 'Obtainment: Discovered in deeper stone layers 51-100.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITRuby',
    name: 'Ruby Ore',
    emoji: '<:ITRuby:1456946779497907333>',
    image: 'https://i.ibb.co/ds7Nvcwd/ITRuby.png',
    rarity: 'Epic',
    type: 'Material',
    value: 750,
    sellPrice: 750,
    tradable: true,
    durability: null,
    info: 'A fiery ruby gemstone.',
    obtainment: 'Obtainment: Discovered in deeper stone layers 51-100.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITDiamond',
    name: 'Diamond Ore',
    emoji: '<:ITDiamond:1456945887991669770>',
    image: 'https://i.ibb.co/sJ6bddRL/ITDiamond.png',
    rarity: 'Legendary',
    type: 'Material',
    value: 1500,
    sellPrice: 1500,
    tradable: true,
    durability: null,
    info: 'A rare, uncut diamond.',
    obtainment: 'Obtainment: Discovered in deeper stone layers 51-100.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITTreeBark',
    name: 'Tree Bark',
    emoji: '<:ITTreeBark:1453266107187200150>',
    image: 'https://i.ibb.co/CRZsHjB/ITTree-Bark.png',
    rarity: 'Common',
    type: 'Material',
    value: 15,
    sellPrice: 15,
    tradable: true,
    durability: null,
    info: 'Bits of bark shaken loose underground.',
    obtainment: 'Obtainment: Dig drop—30% chance per dig roll.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITAcorn',
    name: 'Acorn',
    emoji: '<:ITAcorn:1453266091739709471>',
    image: 'https://i.ibb.co/NdpGPBfY/ITAcorn.png',
    rarity: 'Common',
    type: 'Material/Consumable',
    value: 60,
    sellPrice: 60,
    tradable: true,
    durability: null,
    info: 'A lucky acorn found below the surface.',
    obtainment: 'Obtainment: Dig drop—28% chance per dig roll.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITCommonChest',
    name: 'Common Treasure Chest',
    emoji: '<:ITCommonChest:1453267925417988157>',
    image: 'https://i.ibb.co/KjhctFsF/ITCommon-Chest.png',
    rarity: 'Common',
    type: 'Container',
    value: 150,
    sellPrice: null,
    tradable: true,
    durability: null,
    info: 'A common chest uncovered while digging.',
    obtainment:
      'Obtainment: Treasure chest from digging—5% chance on early layers, scaling up to 12% at 200+ layers.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITRareChest',
    name: 'Rare Treasure Chest',
    emoji: '<:ITRareChest:1453267934045671475>',
    image: 'https://i.ibb.co/0yL5DmrX/ITRare-Chest.png',
    rarity: 'Rare',
    type: 'Container',
    value: 400,
    sellPrice: null,
    tradable: true,
    durability: null,
    info: 'A rare chest brimming with surprises.',
    obtainment: 'Obtainment: Treasure chest from digging—2.5% to 6% chance depending on depth (unlocks at layer 26+).',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITEpicChest',
    name: 'Epic Treasure Chest',
    emoji: '<:ITEpicChest:1453267927464677377>',
    image: 'https://i.ibb.co/rKZbK9Qx/ITEpic-Chest.png',
    rarity: 'Epic',
    type: 'Container',
    value: 850,
    sellPrice: null,
    tradable: true,
    durability: null,
    info: 'An epic chest found deep beneath the layers.',
    obtainment: 'Obtainment: Treasure chest from digging—0.5% to 1.5% chance at higher layers (available from layer 71+).',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITLegendaryChest',
    name: 'Legendary Treasure Chest',
    emoji: '<:ITLegendaryChest:1453267929477939321>',
    image: 'https://i.ibb.co/sd94Cfrm/ITLegendary-Chest.png',
    rarity: 'Legendary',
    type: 'Container',
    value: 2250,
    sellPrice: null,
    tradable: true,
    durability: null,
    info: 'A legendary trove hidden underground.',
    obtainment: 'Obtainment: Treasure chest from digging—0.24% to 0.45% chance on deep layers (available from layer 136+).',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITMythicalChest',
    name: 'Mythical Treasure Chest',
    emoji: '<:ITMythicalChest:1453267931982201032>',
    image: 'https://i.ibb.co/9kQLzrGW/ITMythical-Chest.png',
    rarity: 'Mythical',
    type: 'Container',
    value: 4000,
    sellPrice: null,
    tradable: true,
    durability: null,
    info: 'A mythical chest discovered in the depths.',
    obtainment: 'Obtainment: Treasure chest from digging—0.01% to 0.049% chance on the deepest layers (available from layer 136+).',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITSecretChest',
    name: 'Secret Treasure Chest',
    emoji: '<:ITSecretChest:1453267936234967100>',
    image: 'https://i.ibb.co/yBRSsDhr/ITSecret-Chest.png',
    rarity: 'Secret',
    type: 'Container',
    value: 9999,
    sellPrice: null,
    tradable: true,
    durability: null,
    info: 'A secret chest containing unimaginable loot.',
    obtainment: 'Obtainment: Treasure chest from digging—0.001% chance, only at 200+ layers.',
    usage: 'Usage: Currently no special function beyond collection and trading.',
  },
  {
    id: 'ITDigUpgradeToken',
    name: 'Dig Upgrade Token',
    emoji: '<:ITDigUpgradeToken:1453270353013899438>',
    image: 'https://i.ibb.co/VpTNPNx3/ITDig-Upgrade-Token.png',
    rarity: 'Rare',
    type: 'Material',
    value: 250,
    sellPrice: null,
    tradable: false,
    durability: null,
    info: 'Earned from increasing dig level.',
    obtainment: 'Obtainment: Granted automatically whenever your dig level increases.',
    usage: 'Usage: Spend on future dig upgrades (coming soon).',
  },
  {
    id: 'ITMineUpgradeToken',
    name: 'Mine Upgrade Token',
    emoji: '<:ITMineUpgradeToken:1456947070018650288>',
    image: 'https://i.ibb.co/5hFjJpZg/ITAmethyst.png',
    rarity: 'Rare',
    type: 'Material',
    value: 250,
    sellPrice: null,
    tradable: false,
    durability: null,
    info: 'Earned from increasing mine level.',
    obtainment: 'Obtainment: Granted automatically whenever your mine level increases.',
    usage: 'Usage: Spend on future mining upgrades (coming soon).',
  },
];

for (const item of ITEMS) {
  const emojiName = extractEmojiName(item.emoji);
  if (emojiName) {
    item.id = emojiName;
  }
}

const GEAR_ITEMS = ITEMS.filter((item) => item.type === 'Tool/Gear');
const KNOWN_GEAR = Object.fromEntries(GEAR_ITEMS.map((item) => [item.name, item]));
const ITEMS_BY_ID = Object.fromEntries(ITEMS.map((item) => [item.id, item]));

const FIST_GEAR = KNOWN_GEAR['Fist'];
const WOODEN_SWORD_GEAR = KNOWN_GEAR['Wooden Sword'];
const HUNT_UPGRADE_TOKEN_ITEM = ITEMS.find((item) => item.id === 'ITHuntUpgradeToken');
const CHAT_UPGRADE_TOKEN_ITEM = ITEMS.find((item) => item.id === 'ITChatUpgradeToken');

module.exports = {
  ITEMS,
  GEAR_ITEMS,
  KNOWN_GEAR,
  ITEMS_BY_ID,
  FIST_GEAR,
  WOODEN_SWORD_GEAR,
  HUNT_UPGRADE_TOKEN_ITEM,
  CHAT_UPGRADE_TOKEN_ITEM,
};
