function extractEmojiName(emoji) {
  const match = emoji?.match(/^<a?:([^:]+):\d+>$/);
  return match?.[1] ?? null;
}

const ITEMS = [
  {
    id: 'ITFist',
    name: 'Fist',
    emoji: '<:ITFist:1449009707355476069>',
    rarity: 'Common',
    type: 'Tool/Gear',
    value: 0,
    sellPrice: 0,
    tradable: false,
    durability: Infinity,
    maxDurability: Infinity,
    damage: { min: 1, max: 5 },
    info: 'Useable as a gear in Hunt, deal 1 - 5 damages per hit.',
  },
  {
    id: 'ITWoodenSword',
    name: 'Wooden Sword',
    emoji: '<:ITWoodenSword:1448987035363704955>',
    rarity: 'Common',
    type: 'Tool/Gear',
    value: 13,
    sellPrice: 100,
    tradable: true,
    durability: 50,
    maxDurability: 50,
    damage: { min: 3, max: 8 },
    info: 'Useable as a gear in Hunt, deal 3 - 8 damages per hit. Lose 1 durability per hit.',
  },
  {
    id: 'ITUpgradeToken',
    name: 'Upgrade Token',
    emoji: '<:ITUpgradeToken:1447502158059540481>',
    rarity: 'Rare',
    type: 'Material',
    value: 300,
    sellPrice: null,
    tradable: false,
    durability: null,
    info: 'Coming soon',
  },
  {
    id: 'ITDungeonToken',
    name: 'Dungeon Token',
    emoji: '<:ITDungeonToken:1451523217511677963>',
    rarity: 'Rare',
    type: 'Material',
    value: 0,
    sellPrice: null,
    tradable: true,
    durability: null,
    info: 'A token required to enter a dungeon.',
  },
  {
    id: 'ITBeastMeat',
    name: 'Beast Meat',
    emoji: '<:ITBeastMeat:1449725581217501340>',
    rarity: 'Common',
    type: 'Material',
    value: 8,
    sellPrice: 8,
    tradable: true,
    durability: null,
    info: 'A chunk of raw beast meat dropped from jungle beetles.',
  },
  {
    id: 'ITMossyShavings',
    name: 'Mossy Shavings',
    emoji: '<:ITMossyShavings:1449725583884812338>',
    rarity: 'Common',
    type: 'Material',
    value: 23,
    sellPrice: 23,
    tradable: true,
    durability: null,
    info: 'Damp moss scraps collected from jungle beetles.',
  },
  {
    id: 'ITVineFiber',
    name: 'Vine Fiber',
    emoji: '<:ITVineFiber:1450771201097207871>',
    rarity: 'Common',
    type: 'Material',
    value: 6,
    sellPrice: 150,
    tradable: true,
    durability: null,
    info: 'A fibrous strand pulled from a vine snake.',
  },
  {
    id: 'ITSharpFang',
    name: 'Sharp Fang',
    emoji: '<:ITSharpFang:1450765103250149448>',
    rarity: 'Common',
    type: 'Material',
    value: 35,
    sellPrice: 500,
    tradable: true,
    durability: null,
    info: 'A razor-edged fang harvested from dangerous predators.',
  },
  {
    id: 'ITWeakVenomGland',
    name: 'Weak Venom Gland',
    emoji: '<:ITWeakVenomGland:1450771203823370260>',
    rarity: 'Common',
    type: 'Material',
    value: 12,
    sellPrice: 300,
    tradable: true,
    durability: null,
    info: 'A venom sac still brimming with diluted toxins.',
  },
  {
    id: 'ITJungleFeather',
    name: 'Jungle Feather',
    emoji: '<:ITJungleFeather:1451102919003865108>',
    rarity: 'Common',
    type: 'Material',
    value: 20,
    sellPrice: 100,
    tradable: true,
    durability: null,
    info: 'A glossy feather shed by birds in the jungle canopy.',
  },
  {
    id: 'ITRazorTalon',
    name: 'Razor Talon',
    emoji: '<:ITRazorTalon:1451102921323450532>',
    rarity: 'Common',
    type: 'Material',
    value: 50,
    sellPrice: 300,
    tradable: true,
    durability: null,
    info: 'A razor-sharp talon prized for crafting.',
  },
  {
    id: 'ITHeavyHornFragment',
    name: 'Heavy Horn Fragment',
    emoji: '<:ITHeavyHornFragment:1451103660099637320>',
    rarity: 'Common',
    type: 'Material',
    value: 120,
    sellPrice: 900,
    tradable: true,
    durability: null,
    info: 'A heavy shard chipped from a thornback boar horn.',
  },
  {
    id: 'ITToughHideScrap',
    name: 'Tough Hide Scrap',
    emoji: '<:ITToughHideScrap:1451103661991268416>',
    rarity: 'Common',
    type: 'Material',
    value: 40,
    sellPrice: 250,
    tradable: true,
    durability: null,
    info: 'A tough hide scrap used for rugged gear.',
  },
  {
    id: 'ITWorldrootFragment',
    name: 'Worldroot Fragment',
    emoji: '<:ITWorldrootFragment:1451534950498046033>',
    rarity: 'Rare',
    type: 'Material',
    value: 206,
    sellPrice: 206,
    tradable: true,
    durability: null,
    info: 'A rare fragment pulsing with primal root energy.',
  },
  {
    id: 'ITAncientJungleTablet',
    name: 'Ancient Jungle Tablet',
    emoji: null,
    rarity: 'Epic',
    type: 'Material',
    value: 900,
    sellPrice: 900,
    tradable: true,
    durability: null,
    info: 'A moss-laced tablet etched with ancient jungle runes.',
  },
  {
    id: 'ITResinLump',
    name: 'Resin Lump',
    emoji: '<:ITResinLump:1451534945939099789>',
    rarity: 'Common',
    type: 'Material',
    value: 80,
    sellPrice: 80,
    tradable: true,
    durability: null,
    info: 'A sticky lump of hardened jungle resin.',
  },
  {
    id: 'ITBurrowerScale',
    name: 'Burrower Scale',
    emoji: '<:ITBurrowerScale:1451532823470014515>',
    rarity: 'Common',
    type: 'Material',
    value: 150,
    sellPrice: 150,
    tradable: true,
    durability: null,
    info: 'A rough scale shed by burrowing reptiles.',
  },
  {
    id: 'ITRazorfeatherQuill',
    name: 'Razorfeather Quill',
    emoji: '<:ITRazorfeatherQuill:1451532989036232804>',
    rarity: 'Common',
    type: 'Material',
    value: 120,
    sellPrice: 120,
    tradable: true,
    durability: null,
    info: 'A razor-edged quill prized by fletchers.',
  },
  {
    id: 'ITHunterPeltStrip',
    name: 'Hunter Pelt Strip',
    emoji: '<:ITHunterPeltStrip:1451533239050178621>',
    rarity: 'Common',
    type: 'Material',
    value: 123,
    sellPrice: 123,
    tradable: true,
    durability: null,
    info: 'A sturdy pelt strip used for field gear.',
  },
  {
    id: 'ITJaguarSoulFang',
    name: 'Jaguar Soul Fang',
    emoji: '<:ITJaguarSoulFang:1451534939609628692>',
    rarity: 'Common',
    type: 'Material',
    value: 188,
    sellPrice: 188,
    tradable: true,
    durability: null,
    info: 'A spiritual fang humming with jaguar power.',
  },
  {
    id: 'ITBeetleCarapaceShard',
    name: 'Beetle Carapace Shard',
    emoji: '<:ITBeetleCarapaceShard:1451533534345822228>',
    rarity: 'Common',
    type: 'Material',
    value: 100,
    sellPrice: 100,
    tradable: true,
    durability: null,
    info: 'A glossy shard chipped from a beetle shell.',
  },
  {
    id: 'ITPoisonSporeCluster',
    name: 'Poison Spore Cluster',
    emoji: '<:ITPoisonSporeCluster:1451534943455809679>',
    rarity: 'Common',
    type: 'Material',
    value: 127,
    sellPrice: 127,
    tradable: true,
    durability: null,
    info: 'A toxic spore cluster harvested from fungus shells.',
  },
  {
    id: 'ITShellguardPlate',
    name: 'Shellguard Plate',
    emoji: '<:ITShellguardPlate:1451533859773485139>',
    rarity: 'Common',
    type: 'Material',
    value: 153,
    sellPrice: 153,
    tradable: true,
    durability: null,
    info: 'A dense plate taken from a hardened shell.',
  },
  {
    id: 'ITRootbindingSplinter',
    name: 'Rootbinding Splinter',
    emoji: '<:ITRootbindingSplinter:1451534948304687166>',
    rarity: 'Common',
    type: 'Material',
    value: 169,
    sellPrice: 169,
    tradable: true,
    durability: null,
    info: 'A splinter that still pulses with binding roots.',
  },
  {
    id: 'ITStormCoreShard',
    name: 'Storm Core Shard',
    emoji: '<:ITStormCoreShard:1452300317281616013>',
    rarity: 'Epic',
    type: 'Material',
    value: 735,
    sellPrice: 735,
    tradable: true,
    durability: null,
    info: 'A crackling shard humming with storm energy.',
  },
  {
    id: 'ITThundertraceClawband',
    name: 'Thundertrace Clawband',
    emoji: '<:ITThundertraceClawband:1452294720104693811>',
    rarity: 'Rare',
    type: 'Material',
    value: 240,
    sellPrice: 240,
    tradable: true,
    durability: null,
    info: 'A braided clawband that tingles with static power.',
  },
  {
    id: 'ITBloomPetalCluster',
    name: 'Bloom Petal Cluster',
    emoji: '<:ITBloomPetalCluster:1452300135802605638>',
    rarity: 'Epic',
    type: 'Material',
    value: 815,
    sellPrice: 815,
    tradable: true,
    durability: null,
    info: 'A fragrant bundle of petals that still drips with sap.',
  },
  {
    id: 'ITSpiritMistEssence',
    name: 'Spirit Mist Essence',
    emoji: '<:ITSpiritMistEssence:1452299841232310284>',
    rarity: 'Epic',
    type: 'Material',
    value: 894,
    sellPrice: 894,
    tradable: true,
    durability: null,
    info: 'A vial of misty essence gathered from spectral groves.',
  },
  {
    id: 'ITWardenVeilShard',
    name: "Warden's Veil Shard",
    emoji: '<:ITWardenVeilShard:1452299406467534889>',
    rarity: 'Legendary',
    type: 'Material',
    value: 1125,
    sellPrice: 1125,
    tradable: true,
    durability: null,
    info: 'A rare shard that still echoes with warding power.',
  },
  {
    id: 'ITTotemStoneChip',
    name: 'Totem Stone Chip',
    emoji: '<:ITTotemStoneChip:1452299152485777509>',
    rarity: 'Rare',
    type: 'Material',
    value: 415,
    sellPrice: 415,
    tradable: true,
    durability: null,
    info: 'A chipped piece of totem stone, worn smooth by time.',
  },
  {
    id: 'ITGuardianCore',
    name: 'Guardian Core',
    emoji: '<:ITGuardianCore:1452298696132657443>',
    rarity: 'Epic',
    type: 'Material',
    value: 535,
    sellPrice: 535,
    tradable: true,
    durability: null,
    info: 'A condensed core of guardian energy.',
  },
  {
    id: 'ITSunfirePelt',
    name: 'Sunfire Pelt',
    emoji: '<:ITSunfirePelt:1452294850169929789>',
    rarity: 'Rare',
    type: 'Material',
    value: 360,
    sellPrice: 360,
    tradable: true,
    durability: null,
    info: 'A radiant pelt that still feels warm to the touch.',
  },
  {
    id: 'ITSolarCore',
    name: 'Solar Core',
    emoji: '<:ITSolarCore:1452297980068630589>',
    rarity: 'Epic',
    type: 'Material',
    value: 600,
    sellPrice: 600,
    tradable: true,
    durability: null,
    info: 'A brilliant core pulsing with concentrated sunlight.',
  },
  {
    id: 'ITPhantomOrchidPetal',
    name: 'Phantom Orchid Petal',
    emoji: '<:ITPhantomOrchidPetal:1452532471114498069>',
    rarity: 'Epic',
    type: 'Material',
    value: 709,
    sellPrice: 709,
    tradable: true,
    durability: null,
    info: 'A pale orchid petal that feels cool to the touch.',
  },
];

for (const item of ITEMS) {
  const emojiName = extractEmojiName(item.emoji);
  if (emojiName) {
    item.id = emojiName;
  }
}

const GEAR_ITEMS = ITEMS.filter((item) => item.type === 'Tool/Gear');
const KNOWN_GEAR = Object.fromEntries(GEAR_ITEMS.map((item) => [item.name, item]));
const ITEMS_BY_ID = Object.fromEntries(ITEMS.map((item) => [item.id, item]));

const FIST_GEAR = KNOWN_GEAR['Fist'];
const WOODEN_SWORD_GEAR = KNOWN_GEAR['Wooden Sword'];
const UPGRADE_TOKEN_ITEM = ITEMS.find((item) => item.id === 'ITUpgradeToken');

module.exports = {
  ITEMS,
  GEAR_ITEMS,
  KNOWN_GEAR,
  ITEMS_BY_ID,
  FIST_GEAR,
  WOODEN_SWORD_GEAR,
  UPGRADE_TOKEN_ITEM,
};
