const rawTriviaQuestions = {
  easy: [
    ["What color is a ripe banana usually?", ["Yellow", "Black", "Blue", "Purple"], 0],
    ["How many days are in one week?", ["5", "12", "7", "10"], 2],
    ["Which animal says “meow”?", ["Cat", "Dog", "Duck", "Cow"], 0],
    ["What do bees make?", ["Milk", "Rice", "Bread", "Honey"], 3],
    ["Which planet do we live on?", ["Mars", "Jupiter", "Earth", "Venus"], 2],
    ["How many wheels does a standard bicycle have?", ["4", "1", "2", "3"], 2],
    ["What is H2O commonly called?", ["Sugar", "Water", "Salt", "Oxygen"], 1],
    ["Which fruit is known for keeping doctors away in a saying?", ["Mango", "Apple", "Pear", "Lemon"], 1],
    ["What do you use to write on paper?", ["Plate", "Spoon", "Pillow", "Pencil"], 3],
    ["Which season is usually the coldest?", ["Winter", "Autumn", "Spring", "Summer"], 0],
    ["How many months are in a year?", ["10", "12", "8", "14"], 1],
    ["What shape has three sides?", ["Hexagon", "Square", "Triangle", "Circle"], 2],
    ["Which animal is known as man's best friend?", ["Fish", "Dog", "Tiger", "Eagle"], 1],
    ["What is the opposite of hot?", ["Bright", "Cold", "Fast", "Tall"], 1],
    ["Which meal is usually eaten in the morning?", ["Supper", "Dessert", "Dinner", "Breakfast"], 3],
    ["What do plants need from the sun?", ["Glass", "Sand", "Light", "Metal"], 2],
    ["Which device is used to call people?", ["Bottle", "Toaster", "Chair", "Phone"], 3],
    ["What color do you get by mixing red and white?", ["Pink", "Orange", "Green", "Brown"], 0],
    ["How many legs does a spider have?", ["4", "10", "6", "8"], 3],
    ["Which object tells time?", ["Clock", "Key", "Brush", "Cup"], 0],
    ["What is frozen water called?", ["Ice", "Cloud", "Dust", "Steam"], 0],
    ["Which bird is often associated with delivering babies in cartoons?", ["Peacock", "Penguin", "Stork", "Ostrich"], 2],
    ["What is the main ingredient in bread?", ["Flour", "Stone", "Oil", "Cheese"], 0],
    ["How many letters are in the English alphabet?", ["18", "20", "26", "30"], 2],
    ["Which animal gives milk?", ["Frog", "Shark", "Cow", "Lion"], 2],
    ["What is the color of grass in most places?", ["Red", "Pink", "White", "Green"], 3],
    ["Which tool is used to cut paper?", ["Fork", "Scissors", "Hammer", "Sponge"], 1],
    ["Where do fish usually live?", ["Tree", "Water", "Desert", "Sky"], 1],
    ["What do you wear on your feet?", ["Gloves", "Hat", "Scarf", "Shoes"], 3],
    ["Which food is made from milk?", ["Cheese", "Potato", "Popcorn", "Pasta"], 0],
    ["What number comes after 9?", ["11", "8", "10", "7"], 2],
    ["Which sport uses a soccer ball?", ["Football", "Golf", "Baseball", "Tennis"], 0],
    ["What do you drink when you are thirsty?", ["Soap", "Sand", "Water", "Paper"], 2],
    ["Which animal has a long trunk?", ["Bear", "Rabbit", "Horse", "Elephant"], 3],
    ["What do you use to unlock a door?", ["Leaf", "Coin", "Key", "Pen"], 2],
    ["Which day usually comes after Friday?", ["Thursday", "Saturday", "Wednesday", "Monday"], 1],
    ["What is the opposite of up?", ["Down", "Wide", "Near", "Left"], 0],
    ["Which fruit is long and yellow?", ["Plum", "Banana", "Grape", "Cherry"], 1],
    ["What do you use to see in the dark?", ["Ruler", "Bowl", "Blanket", "Flashlight"], 3],
    ["Which animal hops and has long ears?", ["Snake", "Chicken", "Whale", "Rabbit"], 3],
    ["How many fingers are on one normal human hand?", ["8", "6", "4", "5"], 3],
    ["What is the color of the sky on a clear day?", ["Black", "Green", "Blue", "Orange"], 2],
    ["Which drink is made from oranges?", ["Coffee", "Tea", "Milkshake", "Orange juice"], 3],
    ["What do you call a young cat?", ["Foal", "Kitten", "Puppy", "Calf"], 1],
    ["Which room is used for cooking?", ["Garage", "Kitchen", "Bedroom", "Bathroom"], 1],
    ["What is the opposite of fast?", ["Soft", "Loud", "Slow", "Round"], 2],
    ["Which item keeps rain off your head?", ["Spoon", "Umbrella", "Sock", "Book"], 1],
    ["What do chickens lay?", ["Coins", "Eggs", "Leaves", "Rocks"], 1],
    ["Which animal is black and white and eats bamboo?", ["Panda", "Giraffe", "Fox", "Koala"], 0],
    ["What do you use to brush your teeth?", ["Paintbrush", "Toothbrush", "Comb", "Fork"], 1],
    ["Which food is commonly sliced and put on pizza?", ["Candy cane", "Rice", "Ice", "Cheese"], 3],
    ["How many sides does a square have?", ["5", "6", "4", "3"], 2],
    ["What animal is known for having stripes and looking like a horse?", ["Moose", "Camel", "Zebra", "Deer"], 2],
    ["Which vehicle travels on rails?", ["Boat", "Plane", "Train", "Scooter"], 2],
    ["What does a thermometer measure?", ["Weight", "Color", "Temperature", "Speed"], 2],
    ["Which fruit is red and often used in ketchup?", ["Coconut", "Blueberry", "Tomato", "Lemon"], 2],
    ["What do you use to eat soup?", ["Straw", "Knife", "Spoon", "Chopstick only"], 2],
    ["Which place has many books you can borrow?", ["Stadium", "Bakery", "Library", "Airport"], 2],
    ["What do you call water falling from clouds?", ["Steam", "Rain", "Smoke", "Snow only"], 1],
    ["Which animal is famous for roaring?", ["Mouse", "Goat", "Duck", "Lion"], 3],
    ["What is the first letter of the English alphabet?", ["Z", "Y", "B", "A"], 3],
    ["Which object is used to take photos?", ["Blanket", "Keyboard", "Camera", "Cup"], 2],
    ["What do you call a baby dog?", ["Puppy", "Kitten", "Chick", "Calf"], 0],
    ["Which game piece is used in chess and can move like an L?", ["Bishop", "Pawn", "King", "Knight"], 3],
    ["What do you sleep on?", ["Table", "Sink", "Bed", "Shelf"], 2],
    ["Which fruit has a hard shell and white inside?", ["Peach", "Apple", "Coconut", "Strawberry"], 2],
    ["What is the opposite of day?", ["Night", "Light", "Noon", "Morning"], 0],
    ["Which animal is known for making webs?", ["Butterfly", "Bee", "Spider", "Ant"], 2],
    ["What do you use to clean your hands?", ["Soap", "Glue", "Paint", "Salt"], 0],
    ["Which food is made by popping corn kernels?", ["Cake", "Popcorn", "Bread", "Noodles"], 1],
    ["What do you call the place where airplanes land?", ["Library", "Farm", "Airport", "Harbor"], 2],
    ["Which animal swims and has fins?", ["Cat", "Horse", "Fish", "Dog"], 2],
    ["How many cents are in one US dollar?", ["25", "10", "50", "100"], 3],
    ["Which object is used to measure length?", ["Lamp", "Bowl", "Brush", "Ruler"], 3],
    ["What do you call a group of stars forming a pattern?", ["Island", "Recipe", "Keyboard", "Constellation"], 3],
    ["Which dessert is cold and creamy?", ["Ice cream", "Toast", "Soup", "Rice"], 0],
    ["What do you wear on your head?", ["Belt", "Shoes", "Hat", "Gloves"], 2],
    ["Which animal is known for carrying a shell?", ["Rabbit", "Fox", "Bear", "Turtle"], 3],
    ["What is the opposite of big?", ["Tall", "Bright", "Small", "Heavy"], 2],
    ["Which food is commonly made from potatoes?", ["Yogurt", "Sushi", "Fries", "Pancakes"], 2],
    ["What do you use to open a can?", ["Can opener", "Pencil", "Pillow", "Mirror"], 0],
    ["Which insect has colorful wings and starts as a caterpillar?", ["Ant", "Butterfly", "Mosquito", "Beetle"], 1],
    ["What does a baker usually make?", ["Shoes", "Bread", "Jewelry", "Furniture"], 1],
    ["How many sides does a hexagon have?", ["7", "5", "6", "8"], 2],
    ["Which ocean animal is known for being very large?", ["Lizard", "Ant", "Whale", "Rabbit"], 2],
    ["What do you call cooked rice wrapped with seaweed and fillings?", ["Sushi", "Curry", "Pizza", "Taco"], 0],
    ["Which item is used to carry school supplies?", ["Plate", "Teacup", "Remote", "Backpack"], 3],
    ["What color are most lemons?", ["Brown", "Purple", "Blue", "Yellow"], 3],
    ["Which animal is known for climbing trees and liking bananas?", ["Shark", "Penguin", "Camel", "Monkey"], 3],
    ["What does a keyboard help you do?", ["Paint walls", "Type", "Cook", "Swim"], 1],
    ["Which month comes after January?", ["December", "April", "March", "February"], 3],
    ["What do you call a person who teaches students?", ["Chef", "Pilot", "Teacher", "Artist"], 2],
    ["Which sport uses a hoop and a ball?", ["Basketball", "Skiing", "Golf", "Cricket"], 0],
    ["What is the opposite of left?", ["Under", "Thin", "Over", "Right"], 3],
    ["Which vegetable is orange and loved by rabbits in cartoons?", ["Pea", "Onion", "Cabbage", "Carrot"], 3],
    ["What do you use to cut wood?", ["Comb", "Spoon", "Saw", "Needle"], 2],
    ["Which animal is known for its long neck?", ["Giraffe", "Panda", "Duck", "Pig"], 0],
    ["What do you call the star at the center of our solar system?", ["Venus", "Earth", "Moon", "Sun"], 3],
    ["Which snack is made from cocoa and sugar?", ["Cheese", "Chocolate", "Bread", "Pickle"], 1],
    ["Which object do you use to erase pencil marks?", ["Eraser", "Spoon", "Rope", "Bottle"], 0]
  ,
    ["Which movie series features a wizard named Harry Potter?", ["Star Wars", "Harry Potter", "Jurassic Park", "Toy Story"], 1],
    ["Which animated movie has a cowboy toy named Woody?", ["Shrek", "Toy Story", "Frozen", "Cars"], 1],
    ["Which movie features a blue alien species called the Na'vi?", ["Avatar", "Titanic", "Jumanji", "The Matrix"], 0],
    ["In The Lion King, what kind of animal is Simba?", ["Tiger", "Lion", "Cheetah", "Bear"], 1],
    ["Which superhero is also known as Peter Parker?", ["Batman", "Spider-Man", "Iron Man", "Aquaman"], 1],
    ["Which superhero uses a shield with a star on it?", ["Thor", "Captain America", "Hulk", "Doctor Strange"], 1],
    ["Which movie franchise includes lightsabers and Jedi?", ["Star Wars", "Fast & Furious", "Rocky", "Men in Black"], 0],
    ["What is the name of the snowman in Frozen?", ["Olaf", "Sven", "Kristoff", "Hans"], 0],
    ["Which film features a giant ship that hits an iceberg?", ["Titanic", "Jaws", "Speed", "Twister"], 0],
    ["Which green ogre lives in a swamp?", ["Shrek", "Hulk", "Yoda", "Kermit"], 0],
    ["Which sitcom is set around a group of friends in New York coffee shop Central Perk?", ["Friends", "The Office", "Modern Family", "Seinfeld"], 0],
    ["Which TV show features the workplace Dunder Mifflin?", ["Parks and Recreation", "The Office", "Brooklyn Nine-Nine", "Cheers"], 1],
    ["Which cartoon family lives in Springfield?", ["The Griffins", "The Simpsons", "The Flintstones", "The Jetsons"], 1],
    ["Which character often says 'D'oh!'?", ["Homer Simpson", "SpongeBob", "Scooby-Doo", "Garfield"], 0],
    ["Which sea sponge lives in a pineapple under the sea?", ["Patrick", "SpongeBob SquarePants", "Squidward", "Plankton"], 1],
    ["Which singer is known as the King of Pop?", ["Elvis Presley", "Michael Jackson", "Bruno Mars", "Ed Sheeran"], 1],
    ["Which band released the song 'Yellow Submarine'?", ["Queen", "The Beatles", "ABBA", "Coldplay"], 1],
    ["Which instrument is most associated with rock guitar solos?", ["Flute", "Electric guitar", "Tuba", "Harp"], 1],
    ["Which music award uses a gramophone trophy?", ["Oscar", "Grammy", "Emmy", "Tony"], 1],
    ["Which award show is mainly for movies?", ["Oscars", "Grammys", "Tonys", "Emmys"], 0],
    ["Which meme phrase is often paired with a distracted boyfriend stock photo?", ["Distracted boyfriend", "Keyboard cat", "Nyan cat", "Doge"], 0],
    ["Which internet meme features a Shiba Inu dog and broken English captions?", ["Doge", "Grumpy Cat", "Pepe", "Bad Luck Brian"], 0],
    ["Which platform made short looping dance trends especially popular in the 2020s?", ["TikTok", "Wikipedia", "LinkedIn", "Pinterest"], 0],
    ["Which Pixar movie stars a rat who cooks in Paris?", ["Cars", "Ratatouille", "Brave", "Up"], 1],
    ["Which Pixar movie features emotions named Joy and Sadness?", ["Inside Out", "Coco", "WALL-E", "Soul"], 0],
    ["Which Broadway musical tells the story of Alexander Hamilton through hip-hop style songs?", ["Hamilton", "Cats", "Wicked", "Chicago"], 0],
    ["Which musical features a green-skinned witch named Elphaba?", ["Wicked", "Annie", "Hairspray", "Rent"], 0],
    ["Which comic book company created Spider-Man and the X-Men?", ["Marvel", "DC", "Archie", "Dark Horse"], 0],
    ["Which comic book company is home to Batman and Superman?", ["Marvel", "DC", "Image", "VIZ"], 1],
    ["Which manga series follows a ninja named Naruto Uzumaki?", ["One Piece", "Naruto", "Bleach", "Dragon Ball"], 1],
    ["Which reality show is known for contestants being voted off an island?", ["Survivor", "The Voice", "Shark Tank", "Top Chef"], 0],
    ["Which singing competition uses spinning red chairs?", ["The Voice", "Survivor", "Jeopardy!", "Project Runway"], 0],
    ["What is the name of Mickey Mouse's pet dog?", ["Pluto", "Goofy", "Scooby", "Odie"], 0],
    ["Which fictional dog solves mysteries with Shaggy?", ["Snoopy", "Scooby-Doo", "Clifford", "Blue"], 1],
    ["In Monopoly, what do players collect when passing Go?", ["$200", "$50", "$500", "$10"], 0],
    ["Which board game uses letter tiles to make words?", ["Risk", "Scrabble", "Clue", "Sorry!"], 1],
    ["Which board game asks players to solve a murder in a mansion?", ["Clue", "Candy Land", "Chess", "Battleship"], 0],
    ["Which video game character is a plumber who wears red?", ["Sonic", "Mario", "Link", "Kirby"], 1],
    ["Which video game character is a blue hedgehog?", ["Mario", "Sonic", "Pikachu", "Donkey Kong"], 1],
    ["Which Nintendo series includes Pikachu?", ["Zelda", "Pokémon", "Metroid", "Animal Crossing"], 1],
    ["Which card game uses wild Draw Four cards?", ["Uno", "Poker", "Bridge", "Solitaire"], 0],
    ["In a standard deck, how many suits are there?", ["2", "3", "4", "5"], 2],
    ["Which puzzle toy has colored squares on a cube?", ["Yo-yo", "Rubik's Cube", "Slinky", "Frisbee"], 1],
    ["Which tabletop game often uses a 20-sided die?", ["Dungeons & Dragons", "Monopoly", "Uno", "Jenga"], 0],
    ["Which arcade game features a yellow character eating dots and ghosts?", ["Pac-Man", "Tetris", "Frogger", "Donkey Kong"], 0],
    ["Which toy line became famous for small plush animals with heart-shaped tags?", ["Beanie Babies", "LEGO", "Hot Wheels", "Barbie"], 0],
    ["Which cuisine is strongly associated with sushi?", ["Japanese", "French", "Mexican", "Greek"], 0],
    ["Which country is strongly associated with tacos?", ["Mexico", "Italy", "India", "Germany"], 0],
    ["Which spice is commonly used to make food taste sweet and warm, especially in cinnamon rolls?", ["Cinnamon", "Cumin", "Pepper", "Oregano"], 0],
    ["Which drink is made by steeping leaves in hot water?", ["Tea", "Smoothie", "Soda", "Milk"], 0],
    ["Which dessert is made with layers of pasta-like sheets, cream, and cocoa in Italy?", ["Tiramisu", "Brownie", "Mochi", "Churro"], 0],
    ["Which fast food mascot is a clown?", ["Ronald McDonald", "Tony the Tiger", "Mr. Peanut", "Chester Cheetah"], 0],
    ["Which kitchen tool is used to flip pancakes?", ["Spatula", "Whisk", "Colander", "Rolling pin"], 0],
    ["Which cheese is commonly used on pizza?", ["Mozzarella", "Blue cheese", "Feta", "Brie"], 0],
    ["Which pasta shape is long and thin?", ["Spaghetti", "Penne", "Farfalle", "Ravioli"], 0],
    ["Which global sports event is held every four years and awards gold medals?", ["Olympics", "World Series", "NBA Finals", "Wimbledon"], 0],
    ["Which sport is played in the Super Bowl?", ["American football", "Baseball", "Tennis", "Golf"], 0],
    ["Which sport uses a broom on ice?", ["Curling", "Surfing", "Cricket", "Boxing"], 0],
    ["Which athlete is famous for the nickname 'Air Jordan'?", ["Michael Jordan", "Tom Brady", "Lionel Messi", "Usain Bolt"], 0],
    ["Which martial art is known for colored belts and originated in Japan?", ["Karate", "Curling", "Baseball", "Archery"], 0],
    ["Which outdoor item is used for sleeping while camping?", ["Sleeping bag", "Skateboard", "Tennis racket", "Paintbrush"], 0],
    ["Which judged sport includes routines on a balance beam?", ["Gymnastics", "Soccer", "Bowling", "Cycling"], 0],
    ["Which artist painted the Mona Lisa?", ["Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Claude Monet"], 0],
    ["Which novel features a young wizard named Harry?", ["Harry Potter and the Sorcerer's Stone", "Moby-Dick", "The Hobbit", "Little Women"], 0],
    ["Which language uses the Cyrillic alphabet in Russian writing?", ["Russian", "Spanish", "Arabic", "Korean"], 0],
    ["What does the idiom 'break the ice' mean?", ["Start a conversation", "Freeze water", "Win a race", "Cook dinner"], 0],
    ["In Greek mythology, who is the king of the gods?", ["Zeus", "Hades", "Ares", "Hermes"], 0],
    ["Which building is famous for leaning in Italy?", ["Leaning Tower of Pisa", "Eiffel Tower", "Big Ben", "Colosseum"], 0],
    ["Which clothing item is worn on your head for style or sun protection?", ["Hat", "Belt", "Sock", "Scarf only"], 0],
    ["Which currency is used in Japan?", ["Yen", "Dollar", "Euro", "Peso"], 0],
    ["Which company logo is a bitten apple?", ["Apple", "Google", "Nike", "Samsung"], 0],
    ["Which product fastens clothes with interlocking teeth?", ["Zipper", "Stapler", "Compass", "Whisk"], 0],
    ["Which vehicle flies passengers between airports?", ["Airplane", "Submarine", "Tractor", "Scooter"], 0],
    ["Which holiday is associated with carving pumpkins?", ["Halloween", "Valentine's Day", "Easter", "New Year's Day"], 0],
    ["Which city is the capital of France?", ["Paris", "Madrid", "Rome", "Berlin"], 0],
    ["Which tool is used to hit nails?", ["Hammer", "Screwdriver", "Wrench", "Level"], 0],
    ["Which plant is known for needing little water and having spines?", ["Cactus", "Rose", "Fern", "Tulip"], 0],
    ["Which zodiac sign is represented by a lion?", ["Leo", "Cancer", "Virgo", "Libra"], 0],
    ["Which fabric is made from the fiber of cotton plants?", ["Cotton", "Silk", "Wool", "Nylon"], 0]
  ],
  medium: [
    ["Which gas do plants absorb during photosynthesis?", ["Oxygen", "Neon", "Carbon dioxide", "Helium"], 2],
    ["What is the largest planet in our solar system?", ["Jupiter", "Earth", "Mars", "Saturn"], 0],
    ["Which instrument has keys, pedals, and strings inside?", ["Flute", "Trumpet", "Piano", "Drum"], 2],
    ["What is the process of liquid water becoming vapor called?", ["Condensation", "Melting", "Evaporation", "Freezing"], 2],
    ["Which country is famous for sushi as a traditional food?", ["Italy", "Egypt", "Japan", "Mexico"], 2],
    ["What is the square root of 144?", ["16", "10", "12", "14"], 2],
    ["Which organ pumps blood through the body?", ["Liver", "Heart", "Lung", "Kidney"], 1],
    ["Which metal is commonly used in electric wires?", ["Silver only", "Copper", "Tin", "Lead"], 1],
    ["What is the main language used to style web pages?", ["SQL", "CSS", "HTML", "Python"], 1],
    ["In chess, which piece can move diagonally any distance?", ["Pawn", "Bishop", "Knight", "Rook"], 1],
    ["Which layer of Earth is liquid outer metal?", ["Outer core", "Mantle", "Inner core", "Crust"], 0],
    ["What is the freezing point of water in Celsius?", ["32°C", "10°C", "100°C", "0°C"], 3],
    ["Which vitamin is commonly produced by skin in sunlight?", ["Vitamin D", "Vitamin A", "Vitamin B12", "Vitamin K"], 0],
    ["What is the hardest natural substance?", ["Iron", "Quartz", "Gold", "Diamond"], 3],
    ["Which sport is played at Wimbledon?", ["Table tennis", "Basketball", "Rugby", "Tennis"], 3],
    ["What is the chemical symbol for gold?", ["Au", "Gd", "Go", "Ag"], 0],
    ["Which planet is known for its rings?", ["Mars", "Venus", "Saturn", "Mercury"], 2],
    ["What do you call animals that eat both plants and meat?", ["Omnivores", "Carnivores", "Insectivores", "Herbivores"], 0],
    ["Which data structure uses first-in, first-out behavior?", ["Queue", "Graph", "Stack", "Tree"], 0],
    ["Which famous scientist proposed the laws of motion?", ["Nikola Tesla", "Albert Einstein", "Isaac Newton", "Marie Curie"], 2],
    ["What is the largest ocean on Earth?", ["Indian Ocean", "Atlantic Ocean", "Arctic Ocean", "Pacific Ocean"], 3],
    ["Which part of a plant absorbs water from soil?", ["Fruit", "Petals", "Roots", "Stem only"], 2],
    ["What is the smallest prime number?", ["1", "5", "3", "2"], 3],
    ["Which programming language is often used with Node.js?", ["C", "Swift", "Ruby", "JavaScript"], 3],
    ["What is the main ingredient in guacamole?", ["Cucumber", "Potato", "Avocado", "Tomato"], 2],
    ["Which type of energy is stored in a stretched spring?", ["Potential energy", "Thermal energy", "Kinetic energy", "Light energy"], 0],
    ["What is the capital city of France?", ["Lyon", "Nice", "Paris", "Marseille"], 2],
    ["Which animal is a marsupial?", ["Tiger", "Penguin", "Elephant", "Kangaroo"], 3],
    ["How many degrees are in a right angle?", ["45", "360", "180", "90"], 3],
    ["Which blood cells help carry oxygen?", ["Platelets", "Red blood cells", "White blood cells", "Plasma"], 1],
    ["What does CPU stand for?", ["Central Processing Unit", "Core Program Unit", "Computer Power Utility", "Central Pixel Unit"], 0],
    ["Which continent is the Sahara Desert located in?", ["South America", "Europe", "Asia", "Africa"], 3],
    ["Which food is made by fermenting milk?", ["Bread crumbs", "Pasta", "Yogurt", "Jam"], 2],
    ["What is the chemical symbol for sodium?", ["So", "N", "Sd", "Na"], 3],
    ["Which unit measures electrical resistance?", ["Ampere", "Volt", "Ohm", "Watt"], 2],
    ["What is the study of weather called?", ["Botany", "Geology", "Meteorology", "Astronomy"], 2],
    ["Which polygon has eight sides?", ["Heptagon", "Octagon", "Pentagon", "Hexagon"], 1],
    ["Which bone protects the brain?", ["Tibia", "Skull", "Rib", "Femur"], 1],
    ["What is the main gas in Earth's atmosphere?", ["Hydrogen", "Oxygen", "Nitrogen", "Carbon dioxide"], 2],
    ["Which musical term means to play softly?", ["Piano", "Allegro", "Forte", "Presto"], 0],
    ["What is the largest land animal alive today?", ["Hippopotamus", "Rhino", "African elephant", "Giraffe"], 2],
    ["Which web protocol is used for secure websites?", ["FTP", "SMTP", "HTTPS", "DNS"], 2],
    ["Which part of speech describes an action?", ["Preposition", "Adjective", "Noun", "Verb"], 3],
    ["What is the formula for the area of a rectangle?", ["π × radius", "base + height", "side × side × side", "length × width"], 3],
    ["Which planet is closest to the Sun?", ["Mars", "Mercury", "Venus", "Earth"], 1],
    ["What is the name of the galaxy that contains Earth?", ["Triangulum", "Sombrero", "Andromeda", "Milky Way"], 3],
    ["Which cooking method uses hot oil?", ["Steaming", "Freezing", "Drying", "Frying"], 3],
    ["What is the main function of leaves?", ["Protect bark", "Make food", "Store seeds", "Anchor roots"], 1],
    ["Which SI unit measures force?", ["Pascal", "Newton", "Joule", "Tesla"], 1],
    ["Which animal is known for echolocation?", ["Horse", "Bat", "Panda", "Rabbit"], 1],
    ["What is the decimal form of 1/4?", ["0.25", "0.2", "0.75", "0.5"], 0],
    ["Which element has the chemical symbol O?", ["Oxygen", "Osmium", "Opal", "Gold"], 0],
    ["Which game genre focuses on building and managing resources?", ["Rhythm", "Fighting", "Simulation", "Platformer"], 2],
    ["What is the common name for NaCl?", ["Sugar", "Baking soda", "Salt", "Vinegar"], 2],
    ["Which planet is called the Red Planet?", ["Neptune", "Venus", "Mars", "Jupiter"], 2],
    ["What do you call the force that pulls objects toward Earth?", ["Gravity", "Friction", "Buoyancy", "Magnetism"], 0],
    ["Which device stores electrical energy chemically?", ["Router", "Speaker", "Monitor", "Battery"], 3],
    ["What is a group of wolves called?", ["Pack", "School", "Flock", "Herd"], 0],
    ["Which famous board game uses properties and rent?", ["Monopoly", "Clue", "Risk", "Scrabble"], 0],
    ["Which number is represented by the Roman numeral X?", ["100", "5", "10", "50"], 2],
    ["Which part of a computer displays images?", ["Printer", "Mouse", "Monitor", "Keyboard"], 2],
    ["What is the pH of pure water at room temperature?", ["14", "1", "10", "7"], 3],
    ["Which animal is the fastest land animal?", ["Horse", "Cheetah", "Lion", "Deer"], 1],
    ["What is the main ingredient of tofu?", ["Rice", "Soybeans", "Wheat", "Corn"], 1],
    ["Which branch of science studies living things?", ["Biology", "Geology", "Astronomy", "Physics"], 0],
    ["What is the value of 9 × 8?", ["68", "81", "72", "64"], 2],
    ["Which cloud type is fluffy and often seen in fair weather?", ["Nimbus", "Cirrus", "Cumulus", "Stratus"], 2],
    ["Which country is known for inventing pizza in its modern form?", ["Italy", "Brazil", "India", "Canada"], 0],
    ["What is the name of the fictional wizard school in Harry Potter?", ["Hogwarts", "Narnia", "Mordor", "Gotham"], 0],
    ["Which organ helps humans breathe?", ["Stomach", "Spleen", "Lungs", "Pancreas"], 2],
    ["What is the term for animals active at night?", ["Migratory", "Domestic", "Nocturnal", "Aquatic"], 2],
    ["Which mathematical constant is approximately 3.14159?", ["Phi", "Pi", "Euler's number", "Tau only"], 1],
    ["Which programming concept repeats code while a condition is true?", ["Array", "Class", "Comment", "Loop"], 3],
    ["What is the largest mammal?", ["Blue whale", "Orca", "Giraffe", "Elephant"], 0],
    ["Which material is made by heating sand and other minerals?", ["Rubber", "Cotton", "Glass", "Plastic"], 2],
    ["What is a baby frog called?", ["Foal", "Cub", "Larva only", "Tadpole"], 3],
    ["Which gas do humans breathe in to survive?", ["Argon", "Nitrogen only", "Methane", "Oxygen"], 3],
    ["What is the center of an atom called?", ["Molecule", "Electron cloud", "Shell", "Nucleus"], 3],
    ["Which country is associated with tacos as a traditional food?", ["Greece", "Norway", "Thailand", "Mexico"], 3],
    ["What is 15% of 200?", ["25", "30", "35", "20"], 1],
    ["Which star is closest to Earth?", ["The Sun", "Sirius", "Polaris", "Vega"], 0],
    ["What is the name of the force opposing motion between surfaces?", ["Gravity", "Friction", "Tension", "Lift"], 1],
    ["Which sea creature has eight arms?", ["Octopus", "Seal", "Crab", "Dolphin"], 0],
    ["Which kind of triangle has all sides equal?", ["Right", "Equilateral", "Scalene", "Isosceles only"], 1],
    ["Which file extension is commonly used for JavaScript files?", [".html", ".css", ".py", ".js"], 3],
    ["What is the edible part of broccoli called?", ["Roots", "Seeds", "Bark", "Flower buds"], 3],
    ["Which instrument measures air pressure?", ["Thermometer", "Barometer", "Hygrometer", "Compass"], 1],
    ["What is the main function of the skeleton?", ["Pump blood", "Filter air", "Digest food", "Support the body"], 3],
    ["Which planet has the Great Red Spot?", ["Saturn", "Neptune", "Jupiter", "Mars"], 2],
    ["Which HTML tag is commonly used for a paragraph?", ["<table>", "<script>", "<p>", "<img>"], 2],
    ["What is the process of a caterpillar becoming a butterfly called?", ["Metamorphosis", "Fermentation", "Photosynthesis", "Evaporation"], 0],
    ["Which sport uses a shuttlecock?", ["Badminton", "Volleyball", "Squash", "Tennis"], 0],
    ["What is the main ingredient in hummus?", ["Potatoes", "Chickpeas", "Eggs", "Apples"], 1],
    ["Which machine is used to print documents?", ["Scanner", "Printer", "Projector", "Router"], 1],
    ["What is the name for a word that has the opposite meaning?", ["Suffix", "Prefix", "Synonym", "Antonym"], 3],
    ["Which part of Earth do tectonic plates belong to?", ["Biosphere", "Hydrosphere", "Atmosphere", "Lithosphere"], 3],
    ["How many players are on a standard soccer team on the field?", ["9", "10", "11", "12"], 2],
    ["Which sense uses the tongue?", ["Sight", "Taste", "Touch", "Hearing"], 1],
    ["Which shape is the base of most traffic stop signs?", ["Triangle", "Octagon", "Circle", "Pentagon"], 1],
    ["What type of animal is a salmon?", ["Reptile", "Mammal", "Fish", "Bird"], 2]
  ,
    ["Which actor voiced Woody in the Toy Story films?", ["Tom Hanks", "Tim Allen", "Robin Williams", "Billy Crystal"], 0],
    ["Which actor voiced Buzz Lightyear in the original Toy Story films?", ["Tom Hanks", "Tim Allen", "John Goodman", "Mike Myers"], 1],
    ["Which film won the first Academy Award for Best Animated Feature?", ["Toy Story", "Shrek", "Finding Nemo", "Spirited Away"], 1],
    ["Which movie features the fictional metal vibranium?", ["Black Panther", "The Matrix", "Jaws", "Top Gun"], 0],
    ["Which director is closely associated with the movie Jaws?", ["Steven Spielberg", "James Cameron", "George Lucas", "Ridley Scott"], 0],
    ["Which movie franchise features the character Dominic Toretto?", ["Fast & Furious", "Mission: Impossible", "Indiana Jones", "The Hunger Games"], 0],
    ["Which film popularized the quote 'I'll be back'?", ["The Terminator", "Rocky", "Ghostbusters", "Die Hard"], 0],
    ["Which movie features a DeLorean time machine?", ["Back to the Future", "Blade Runner", "E.T.", "Tron"], 0],
    ["Which fictional country is ruled by King T'Challa?", ["Wakanda", "Narnia", "Genovia", "Latveria"], 0],
    ["Which monster movie features a giant ape on Skull Island?", ["King Kong", "Godzilla", "Cloverfield", "Pacific Rim"], 0],
    ["Which sitcom catchphrase is associated with Joey Tribbiani?", ["How you doin'?", "Bazinga!", "D'oh!", "Did I do that?"], 0],
    ["Which sitcom character often says 'Bazinga!'?", ["Sheldon Cooper", "Michael Scott", "Ross Geller", "Frasier Crane"], 0],
    ["Which TV bar is the main setting of Cheers?", ["Cheers", "Moe's Tavern", "Central Perk", "The Max"], 0],
    ["Which sitcom follows the Pritchett-Dunphy-Tucker family?", ["Modern Family", "Friends", "Seinfeld", "Community"], 0],
    ["Which mockumentary sitcom is set in Pawnee, Indiana?", ["Parks and Recreation", "The Office", "30 Rock", "Arrested Development"], 0],
    ["Which artist is known as the Queen of Pop?", ["Madonna", "Adele", "Billie Eilish", "Dua Lipa"], 0],
    ["Which British band released the album Abbey Road?", ["The Beatles", "The Rolling Stones", "Oasis", "Queen"], 0],
    ["Which genre is most associated with DJs, turntables, and MCs?", ["Hip-hop", "Opera", "Bluegrass", "Baroque"], 0],
    ["Which singer released the album 1989?", ["Taylor Swift", "Ariana Grande", "Beyoncé", "Lady Gaga"], 0],
    ["Which band performed the song 'Bohemian Rhapsody'?", ["Queen", "ABBA", "Nirvana", "The Police"], 0],
    ["Which award is given for excellence in television?", ["Emmy", "Oscar", "Grammy", "Tony"], 0],
    ["Which award is given for excellence in Broadway theater?", ["Tony", "Oscar", "Grammy", "Pulitzer only"], 0],
    ["Which organization presents the Academy Awards?", ["Academy of Motion Picture Arts and Sciences", "Recording Academy", "Hollywood Foreign Press only", "Tony Committee"], 0],
    ["Which internet meme features a rainbow cat flying through space?", ["Nyan Cat", "Doge", "Keyboard Cat", "Success Kid"], 0],
    ["Which meme is based on a cat with a famously unhappy expression?", ["Grumpy Cat", "Ceiling Cat", "Longcat", "Pusheen"], 0],
    ["Which term describes a video or post spreading quickly online?", ["Viral", "Analog", "Offline", "Private"], 0],
    ["Which actor voiced Genie in Disney's Aladdin?", ["Robin Williams", "Eddie Murphy", "Will Ferrell", "Steve Carell"], 0],
    ["Which actor voiced Donkey in Shrek?", ["Eddie Murphy", "Mike Myers", "Antonio Banderas", "Chris Rock"], 0],
    ["Which Broadway musical is based on songs by ABBA?", ["Mamma Mia!", "Wicked", "Rent", "Cats"], 0],
    ["Which stage musical features the Phantom and Christine Daaé?", ["The Phantom of the Opera", "Hamilton", "Chicago", "Annie"], 0],
    ["Which manga series follows Monkey D. Luffy?", ["One Piece", "Naruto", "Death Note", "Sailor Moon"], 0],
    ["Which graphic novel by Art Spiegelman uses mice and cats to depict history?", ["Maus", "Watchmen", "Persepolis", "Blankets"], 0],
    ["Which superhero is known as the Dark Knight?", ["Batman", "Superman", "Green Lantern", "Flash"], 0],
    ["Which reality competition features designers making outfits under time limits?", ["Project Runway", "Survivor", "The Amazing Race", "The Bachelor"], 0],
    ["Which reality show features entrepreneurs pitching to investors?", ["Shark Tank", "Big Brother", "Top Chef", "American Idol"], 0],
    ["Which fictional pet belongs to Charlie Brown?", ["Snoopy", "Garfield", "Odie", "Pluto"], 0],
    ["Which fictional orange cat loves lasagna?", ["Garfield", "Heathcliff", "Salem", "Tom"], 0],
    ["In chess, which piece can move any number of squares diagonally?", ["Bishop", "Rook", "Knight", "Pawn"], 0],
    ["In Risk, what is the main goal?", ["World domination", "Build words", "Solve a murder", "Buy properties"], 0],
    ["Which board game uses a pop-o-matic dice bubble?", ["Trouble", "Scrabble", "Risk", "Clue"], 0],
    ["Which console introduced Wii motion controls?", ["Nintendo Wii", "PlayStation 2", "Xbox 360", "Sega Dreamcast"], 0],
    ["Which video game series features Master Chief?", ["Halo", "Metroid", "Doom", "Mass Effect"], 0],
    ["Which Zelda game popularized the phrase 'It's dangerous to go alone!'?", ["The Legend of Zelda", "Ocarina of Time", "Breath of the Wild", "Majora's Mask"], 0],
    ["Which card hand beats a flush in standard poker?", ["Full house", "Straight", "Three of a kind", "Two pair"], 0],
    ["In Uno, what does a Reverse card do?", ["Changes play direction", "Skips everyone", "Draws four cards", "Ends the game instantly"], 0],
    ["Which solitaire game is also commonly called Patience?", ["Klondike", "Bridge", "Hearts", "Rummy"], 0],
    ["What is the minimum number of moves needed to solve a standard 3x3 Rubik's Cube from any position, known informally as God's number?", ["20", "10", "30", "50"], 0],
    ["In Dungeons & Dragons, what does AC usually stand for?", ["Armor Class", "Action Charge", "Arcane Chance", "Attack Count"], 0],
    ["Which arcade classic has a frog crossing roads and rivers?", ["Frogger", "Galaga", "Centipede", "Asteroids"], 0],
    ["Which toy uses interlocking plastic bricks?", ["LEGO", "Slinky", "Etch A Sketch", "Nerf"], 0],
    ["Which cuisine is strongly associated with kimchi?", ["Korean", "Italian", "Brazilian", "Moroccan"], 0],
    ["Which cuisine is strongly associated with pad thai?", ["Thai", "Greek", "German", "Peruvian"], 0],
    ["Which herb is a key ingredient in traditional pesto?", ["Basil", "Dill", "Sage", "Mint"], 0],
    ["Which spice is made from dried flower buds and has a strong warm flavor?", ["Clove", "Coriander", "Paprika", "Parsley"], 0],
    ["Which coffee drink is espresso with steamed milk and foam?", ["Cappuccino", "Lemonade", "Matcha", "Kombucha"], 0],
    ["Which tea is traditionally used in a Japanese tea ceremony?", ["Matcha", "Earl Grey", "Chai", "Iced tea"], 0],
    ["Which dessert is made by baking a custard in a caramel-lined mold?", ["Flan", "Baklava", "Macaron", "Gelato"], 0],
    ["Which baking technique gently folds beaten egg whites into batter to keep air?", ["Folding", "Deep-frying", "Searing", "Pickling"], 0],
    ["Which fast food chain is known for the slogan 'Have it your way'?", ["Burger King", "KFC", "Subway", "Taco Bell"], 0],
    ["Which regional American sandwich is associated with Philadelphia?", ["Cheesesteak", "Po' boy", "Lobster roll", "Cuban sandwich"], 0],
    ["Which knife is commonly used as an all-purpose kitchen knife?", ["Chef's knife", "Butter knife", "Palette knife", "Letter opener"], 0],
    ["Which cheese is traditionally used in Greek salad?", ["Feta", "Cheddar", "Gouda", "Camembert"], 0],
    ["Which pasta shape is shaped like little butterflies or bow ties?", ["Farfalle", "Rigatoni", "Linguine", "Orzo"], 0],
    ["Which country has won the FIFA World Cup multiple times and wears a famous yellow jersey?", ["Brazil", "Canada", "Japan", "Egypt"], 0],
    ["Which sport uses the term 'love' for zero?", ["Tennis", "Baseball", "Basketball", "Curling"], 0],
    ["In curling, what is the target area called?", ["House", "Goal", "Nest", "Diamond"], 0],
    ["Which Southeast Asian sport uses a rattan ball and feet over a net?", ["Sepak takraw", "Cricket", "Lacrosse", "Polo"], 0],
    ["Which athlete is known as 'The Great One' in ice hockey?", ["Wayne Gretzky", "Michael Phelps", "Babe Ruth", "Pelé"], 0],
    ["Which jersey number is famously associated with Michael Jordan on the Chicago Bulls?", ["23", "7", "99", "10"], 0],
    ["Which stadium is known as 'The Theatre of Dreams'?", ["Old Trafford", "Wembley Stadium", "Madison Square Garden", "Camp Nou"], 0],
    ["Which martial art emphasizes throws and pins and originated in Japan?", ["Judo", "Taekwondo", "Capoeira", "Muay Thai"], 0],
    ["Which camping item is used to start a fire by striking sparks?", ["Flint and steel", "Compass", "Tarp", "Carabiner"], 0],
    ["Which figure skating jump takes off from the forward outside edge?", ["Axel", "Loop", "Lutz", "Salchow"], 0],
    ["Which art movement is associated with Pablo Picasso and fragmented geometric forms?", ["Cubism", "Impressionism", "Romanticism", "Baroque"], 0],
    ["Which artist painted Starry Night?", ["Vincent van Gogh", "Claude Monet", "Frida Kahlo", "Salvador Dalí"], 0],
    ["Which novel begins with the line 'Call me Ishmael'?", ["Moby-Dick", "Pride and Prejudice", "1984", "Dracula"], 0],
    ["Which fictional land is reached through a wardrobe in a C. S. Lewis novel?", ["Narnia", "Oz", "Middle-earth", "Neverland"], 0],
    ["Which alphabet is used for modern Greek?", ["Greek alphabet", "Latin alphabet only", "Hangul", "Cyrillic only"], 0],
    ["What does the idiom 'spill the beans' mean?", ["Reveal a secret", "Cook soup", "Drop groceries", "Win easily"], 0],
    ["In Norse mythology, what is Thor's hammer called?", ["Mjölnir", "Excalibur", "Aegis", "Gungnir"], 0],
    ["Which architectural style is known for pointed arches and flying buttresses?", ["Gothic", "Brutalist", "Bauhaus", "Art Deco"], 0],
    ["Which fashion designer is strongly associated with the little black dress?", ["Coco Chanel", "Ralph Lauren", "Virgil Abloh", "Giorgio Armani"], 0],
    ["What does supply and demand mainly help explain?", ["Prices", "Weather", "Blood types", "Planet orbits"], 0],
    ["Which company uses the swoosh logo?", ["Nike", "Adidas", "Puma", "Reebok"], 0],
    ["Which currency is used by many countries in the European Union?", ["Euro", "Yen", "Rupee", "Peso"], 0],
    ["What does IPO stand for in the stock market?", ["Initial Public Offering", "Internal Price Order", "Instant Profit Option", "International Product Office"], 0],
    ["Which invention lets clothes open and close with sliding interlocking teeth?", ["Zipper", "Ballpoint pen", "Toaster", "Thermos"], 0],
    ["Which car company makes the Mustang model?", ["Ford", "Toyota", "Honda", "BMW"], 0],
    ["Which advertising mascot says 'They're grrreat!'?", ["Tony the Tiger", "Mr. Clean", "Michelin Man", "Pillsbury Doughboy"], 0],
    ["Which crop is commonly used to make tofu and soy sauce?", ["Soybean", "Barley", "Cassava", "Oat"], 0],
    ["Which festival is known as the Festival of Lights in India?", ["Diwali", "Oktoberfest", "Carnival", "Hanami"], 0],
    ["Which country has a red maple leaf on its flag?", ["Canada", "Switzerland", "Denmark", "Vietnam"], 0],
    ["Which time zone term means Coordinated Universal Time?", ["UTC", "CPU", "GPS", "HTML"], 0],
    ["Which DIY tool checks whether a surface is horizontal?", ["Level", "Wrench", "Drill bit", "Pliers"], 0],
    ["Which houseplant is known for heart-shaped leaves and trailing vines?", ["Pothos", "Cactus", "Bonsai pine", "Venus flytrap"], 0],
    ["In many cultures, what is a polite thing to say after receiving help?", ["Thank you", "Move aside", "Hurry up", "Give me more"], 0],
    ["Which zodiac sign is represented by scales?", ["Libra", "Aries", "Scorpio", "Pisces"], 0],
    ["Which birthstone is commonly associated with April?", ["Diamond", "Ruby", "Emerald", "Opal"], 0],
    ["Which fabric is made from silkworm cocoons?", ["Silk", "Denim", "Linen", "Fleece"], 0]
  ],
  hard: [
    ["Which sorting algorithm has average-case time complexity O(n log n) and commonly uses partitioning?", ["Bubble sort", "Insertion sort", "Quicksort", "Linear search"], 2],
    ["What is the approximate speed of light in vacuum?", ["300,000 km/s", "3,000,000 km/s", "3,000 km/s", "30,000 km/s"], 0],
    ["Which element has atomic number 6?", ["Carbon", "Silicon", "Oxygen", "Nitrogen"], 0],
    ["In music theory, how many semitones are in an octave?", ["8", "7", "10", "12"], 3],
    ["Which mathematical sequence begins 0, 1, 1, 2, 3, 5?", ["Fibonacci", "Prime", "Geometric", "Triangular"], 0],
    ["What is the powerhouse organelle of the cell?", ["Mitochondrion", "Ribosome", "Golgi apparatus", "Nucleus"], 0],
    ["Which database language is commonly used for querying relational databases?", ["CSS", "Bash", "HTML", "SQL"], 3],
    ["What is the derivative of x²?", ["2x", "x³", "2", "x"], 0],
    ["Which planet has the shortest day among the planets?", ["Mercury", "Jupiter", "Earth", "Neptune"], 1],
    ["What is the main structural protein found in hair and nails?", ["Collagen", "Keratin", "Elastin", "Casein"], 1],
    ["Which algorithm finds shortest paths from one source in a weighted graph with nonnegative edges?", ["K-means", "Merge sort", "A* without heuristic", "Dijkstra's algorithm"], 3],
    ["What is the SI unit of electric capacitance?", ["Weber", "Farad", "Henry", "Ohm"], 1],
    ["Which number system uses base 16?", ["Octal", "Binary", "Decimal", "Hexadecimal"], 3],
    ["What is the term for the fear of long words?", ["Hippopotomonstrosesquipedaliophobia", "Claustrophobia", "Arachnophobia", "Acrophobia"], 0],
    ["Which amino acid is often represented by the one-letter code W?", ["Tryptophan", "Threonine", "Tyrosine", "Valine"], 0],
    ["Which protocol translates domain names into IP addresses?", ["HTTP", "DNS", "SMTP", "SSH"], 1],
    ["What is the value of 2⁸?", ["128", "256", "64", "512"], 1],
    ["Which moon is the largest moon of Saturn?", ["Europa", "Io", "Ganymede", "Titan"], 3],
    ["What is the term for a word spelled the same backward and forward?", ["Anagram", "Acronym", "Palindrome", "Homonym"], 2],
    ["Which type of bond involves shared electron pairs?", ["Metallic bond", "Hydrogen bond only", "Covalent bond", "Ionic bond"], 2],
    ["What is the normal form targeted by eliminating transitive dependency in relational design?", ["Boyce-Codd only", "Zero normal form", "Third normal form", "First normal form"], 2],
    ["Which lens type is thicker in the center and converges light?", ["Concave lens", "Flat lens", "Convex lens", "Cylindrical lens"], 2],
    ["What is the term for animals that maintain constant internal body temperature?", ["Autotrophs", "Decomposers", "Endotherms", "Ectotherms"], 2],
    ["Which compression format is commonly lossless for images?", ["JPEG", "PNG", "MP4", "AAC"], 1],
    ["What is the result of 7 factorial?", ["720", "5040", "40320", "840"], 1],
    ["Which compound is commonly known as baking soda?", ["Sodium bicarbonate", "Sodium chloride", "Calcium carbonate", "Acetic acid"], 0],
    ["Which programming paradigm treats computation as evaluating functions?", ["Object storage", "Functional programming", "Procedural programming", "Markup programming"], 1],
    ["What is the longest side of a right triangle called?", ["Base only", "Hypotenuse", "Median", "Altitude"], 1],
    ["Which biological molecule stores genetic information?", ["Cellulose", "Lipid", "DNA", "Starch"], 2],
    ["What is the name for molten rock beneath Earth's surface?", ["Lava", "Pumice", "Basalt", "Magma"], 3],
    ["Which HTTP status code means Not Found?", ["500", "301", "200", "404"], 3],
    ["What is the integral of 1/x with respect to x?", ["1/x² + C", "x² + C", "eˣ + C", "ln|x| + C"], 3],
    ["Which constellation contains the star Betelgeuse?", ["Scorpius", "Cygnus", "Orion", "Ursa Major"], 2],
    ["What is the chemical formula of glucose?", ["H2SO4", "NaOH", "C6H12O6", "CO2"], 2],
    ["Which term describes light bending as it passes between media?", ["Absorption", "Refraction", "Diffusion", "Reflection"], 1],
    ["What is the base unit of luminous intensity in SI?", ["Watt", "Lumen", "Candela", "Lux"], 2],
    ["Which software design principle says classes should have one reason to change?", ["Factory Rule", "Single Responsibility Principle", "Singleton Rule", "Open Loop Principle"], 1],
    ["Which enzyme starts starch digestion in the mouth?", ["Pepsin", "Amylase", "Lactase", "Lipase"], 1],
    ["What is the approximate value of Euler's number e?", ["3.142", "2.718", "1.618", "0.577"], 1],
    ["Which data structure is typically used for recursion call management?", ["Queue", "Hash table", "Stack", "Heap"], 2],
    ["Which planet has the most confirmed moons as of recent astronomy counts?", ["Saturn", "Venus", "Earth", "Mars"], 0],
    ["What is the term for a triangle with two equal sides?", ["Equilateral only", "Isosceles", "Scalene", "Obtuse"], 1],
    ["Which mineral scale measures scratch hardness?", ["Mohs scale", "pH scale", "Richter scale", "Beaufort scale"], 0],
    ["What is the smallest unit of sound in a spoken language?", ["Morpheme", "Clause", "Phoneme", "Syllable"], 2],
    ["Which computer memory is volatile?", ["SSD", "Blu-ray", "RAM", "ROM"], 2],
    ["What is the common name for ascorbic acid?", ["Vitamin D", "Vitamin C", "Vitamin B1", "Vitamin K"], 1],
    ["Which law states pressure and volume are inversely related at constant temperature?", ["Charles's law", "Boyle's law", "Ohm's law", "Hooke's law"], 1],
    ["What is the center of mass of a triangle called?", ["Incenter", "Orthocenter", "Centroid", "Circumcenter"], 2],
    ["Which language is primarily used with the Unity game engine for scripting?", ["C#", "Perl", "R", "PHP"], 0],
    ["What is the process of converting sugar into acids or alcohol by microorganisms?", ["Fermentation", "Pasteurization", "Caramelization", "Crystallization"], 0],
    ["Which star type is the Sun classified as?", ["G-type main-sequence star", "White dwarf", "Neutron star", "Red giant"], 0],
    ["What does API stand for?", ["Advanced Packet Input", "Applied Program Internet", "Application Programming Interface", "Automated Page Index"], 2],
    ["Which equation relates voltage, current, and resistance?", ["Ohm's law", "Bernoulli's principle", "Newton's second law", "Snell's law"], 0],
    ["What is the term for a market with one dominant seller?", ["Perfect competition", "Duopoly only", "Oligopsony", "Monopoly"], 3],
    ["Which molecule is the primary energy currency of cells?", ["Chlorophyll", "DNA", "ATP", "RNA"], 2],
    ["Which graph traversal uses a queue?", ["Depth-first search", "Breadth-first search", "Heap sort", "Binary search"], 1],
    ["What is the value of log10(1000)?", ["3", "10", "100", "2"], 0],
    ["Which spice gives curry its bright yellow color?", ["Nutmeg", "Paprika", "Turmeric", "Cinnamon"], 2],
    ["Which number is the additive identity?", ["1", "0", "-1", "10"], 1],
    ["What is the term for the boundary where two air masses meet?", ["Isobar", "Cyclone", "Jet stream", "Front"], 3],
    ["Which HTML attribute provides alternative text for images?", ["alt", "href", "class", "src"], 0],
    ["What is the primary pigment involved in photosynthesis?", ["Keratin", "Hemoglobin", "Chlorophyll", "Melanin"], 2],
    ["Which regular polygon has internal angles of 120 degrees?", ["Octagon", "Hexagon", "Square", "Pentagon"], 1],
    ["What is the name of the statistical value in the middle of ordered data?", ["Range", "Mode", "Median", "Mean"], 2],
    ["Which concept describes resistance to changes in motion?", ["Inertia", "Impulse", "Momentum only", "Torque"], 0],
    ["Which food science process browns sugars and proteins together?", ["Caramelization", "Sublimation", "Osmosis", "Maillard reaction"], 3],
    ["What is the unit of frequency?", ["Pascal", "Newton", "Joule", "Hertz"], 3],
    ["Which command-line system is commonly used to track code versions?", ["Docker", "Node", "Git", "NPM"], 2],
    ["What is the name of a 3D shape with six square faces?", ["Cylinder", "Sphere", "Cone", "Cube"], 3],
    ["Which gas is commonly used by balloons to float?", ["Nitrogen", "Helium", "Carbon dioxide", "Oxygen"], 1],
    ["What is the term for the study of fungi?", ["Ichthyology", "Ornithology", "Mycology", "Entomology"], 2],
    ["Which part of the eye controls the amount of light entering?", ["Retina", "Cornea", "Iris", "Lens only"], 2],
    ["What is the value of sin(90°)?", ["-1", "0", "0.5", "1"], 3],
    ["Which CSS layout system is one-dimensional?", ["SVG", "Grid", "Canvas", "Flexbox"], 3],
    ["What is the hardest part of the human tooth?", ["Cementum", "Pulp", "Dentin", "Enamel"], 3],
    ["Which state of matter has a fixed volume but no fixed shape?", ["Gas", "Solid", "Liquid", "Plasma"], 2],
    ["Which cloud service model provides virtualized computing resources?", ["DNS", "PaaS only", "SaaS", "IaaS"], 3],
    ["What is the term for a sentence that asks a question?", ["Exclamatory", "Imperative", "Declarative", "Interrogative"], 3],
    ["Which molecule carries amino acids to ribosomes?", ["DNA", "mRNA", "tRNA", "ATP"], 2],
    ["What is the binary representation of decimal 10?", ["1001", "1010", "1110", "1100"], 1],
    ["Which statistical chart is best for showing parts of a whole?", ["Pie chart", "Line chart", "Box plot", "Scatter plot"], 0],
    ["What is the name of the point where two axes meet on a coordinate plane?", ["Vertex", "Origin", "Focus", "Centroid"], 1],
    ["Which ecosystem is dominated by grasses and few trees?", ["Tundra", "Coral reef", "Grassland", "Rainforest"], 2],
    ["Which term means a word formed from the first letters of a phrase?", ["Synonym", "Acronym", "Prefix", "Homophone"], 1],
    ["What is the common unit for measuring computer file size?", ["Meter", "Byte", "Gram", "Volt"], 1],
    ["Which geometry term describes lines that never meet?", ["Parallel", "Skew only", "Perpendicular", "Intersecting"], 0],
    ["What is the name for heat transfer through fluid motion?", ["Convection", "Radiation", "Reflection", "Conduction"], 0],
    ["Which nutrient is the body's main quick energy source?", ["Water", "Mineral", "Vitamin", "Carbohydrate"], 3],
    ["Which JavaScript method converts JSON text into an object?", ["Object.keys", "Array.map", "JSON.parse", "JSON.stringify"], 2],
    ["What is the solution to x in 3x = 21?", ["9", "6", "7", "8"], 2],
    ["Which ocean zone receives enough sunlight for photosynthesis?", ["Hadal zone", "Photic zone", "Benthic zone only", "Abyssal zone"], 1],
    ["Which term describes a reusable block of code?", ["Variable", "Literal", "Function", "Operator"], 2],
    ["What is the name of the imaginary line around Earth's middle?", ["Axis", "Meridian", "Tropic", "Equator"], 3],
    ["Which probability value is impossible?", ["1.5", "0", "0.5", "1"], 0],
    ["Which astronomical object is made mostly of ice, dust, and rock and can show a tail near the Sun?", ["Planet", "Comet", "Meteorite", "Asteroid only"], 1],
    ["What is the unit of work and energy?", ["Watt", "Ampere", "Joule", "Volt"], 2],
    ["Which cooking term means to briefly cook food in boiling water?", ["Grill", "Bake", "Blanch", "Roast"], 2],
    ["Which 1972 film became the first movie in The Godfather trilogy?", ["The Godfather", "Goodfellas", "Scarface", "Casino"], 0],
    ["Which movie won all five major Oscars: Picture, Director, Actor, Actress, and Screenplay?", ["The Silence of the Lambs", "Titanic", "La La Land", "Avatar"], 0],
    ["Which film introduced the line 'May the Force be with you' to mainstream cinema?", ["Star Wars: A New Hope", "The Empire Strikes Back", "Return of the Jedi", "The Phantom Menace"], 0],
    ["Which director made Spirited Away?", ["Hayao Miyazaki", "Akira Kurosawa", "Makoto Shinkai", "Satoshi Kon"], 0],
    ["Which film features the character Keyser Söze?", ["The Usual Suspects", "Se7en", "Heat", "Memento"], 0],
    ["Which sitcom's finale was watched by over 100 million viewers in the United States in 1983?", ["M*A*S*H", "Friends", "Cheers", "Seinfeld"], 0],
    ["Which sitcom character was known for the dance called 'The Carlton'?", ["Carlton Banks", "Joey Tribbiani", "George Costanza", "Niles Crane"], 0],
    ["Which sitcom created by Larry David and Jerry Seinfeld is famously described as a show about nothing?", ["Seinfeld", "Frasier", "Friends", "Scrubs"], 0],
    ["Which music genre originated in Jamaica and is associated with offbeat rhythms?", ["Reggae", "Disco", "Grunge", "Bluegrass"], 0],
    ["Which artist's album Thriller became one of the best-selling albums of all time?", ["Michael Jackson", "Prince", "Elton John", "Stevie Wonder"], 0],
    ["Which group released the disco hit 'Dancing Queen'?", ["ABBA", "Bee Gees", "Fleetwood Mac", "The Supremes"], 0],
    ["Which composer wrote the musical The Phantom of the Opera?", ["Andrew Lloyd Webber", "Stephen Sondheim", "Lin-Manuel Miranda", "Leonard Bernstein"], 0],
    ["Which awards are represented by the EGOT acronym?", ["Emmy, Grammy, Oscar, Tony", "Emmy, Globe, Oscar, Tony", "ESPY, Grammy, Olivier, Tony", "Emmy, Grammy, Obie, Tony"], 0],
    ["Which Grammy category honors a full album rather than a single song?", ["Album of the Year", "Song of the Year", "Record of the Year", "Best New Artist"], 0],
    ["Which internet term originally described intentionally inflammatory online posts meant to provoke reactions?", ["Trolling", "Streaming", "Bookmarking", "Buffering"], 0],
    ["Which early viral video featured a baby dancing to 'Hooked on a Feeling'?", ["Dancing Baby", "Charlie Bit My Finger", "Evolution of Dance", "Numa Numa"], 0],
    ["Which actor voiced Marlin in Finding Nemo?", ["Albert Brooks", "John Ratzenberger", "Billy Crystal", "Craig T. Nelson"], 0],
    ["Which actor voiced Elastigirl in The Incredibles?", ["Holly Hunter", "Amy Poehler", "Ellen DeGeneres", "Ming-Na Wen"], 0],
    ["Which musical is inspired by Puccini's opera La Bohème?", ["Rent", "Cats", "A Chorus Line", "Hadestown"], 0],
    ["Which musical retells Greek mythology with Orpheus and Eurydice in a folk-jazz style?", ["Hadestown", "Les Misérables", "The Producers", "Sweeney Todd"], 0],
    ["Which graphic novel deconstructs superheroes and features Rorschach?", ["Watchmen", "Maus", "V for Vendetta", "Sandman"], 0],
    ["Which manga artist created Dragon Ball?", ["Akira Toriyama", "Eiichiro Oda", "Masashi Kishimoto", "Naoko Takeuchi"], 0],
    ["Which reality show format traps contestants in a house under constant camera surveillance?", ["Big Brother", "The Amazing Race", "Top Chef", "The Masked Singer"], 0],
    ["Which competition show uses the phrase 'sashay away'?", ["RuPaul's Drag Race", "Project Runway", "Survivor", "The Voice"], 0],
    ["Which fictional dragon is Hiccup's companion in How to Train Your Dragon?", ["Toothless", "Falkor", "Smaug", "Mushu"], 0],
    ["Which board game was originally patented as The Landlord's Game?", ["Monopoly", "Risk", "Clue", "Sorry!"], 0],
    ["In Settlers of Catan, which resource is represented by sheep?", ["Wool", "Ore", "Brick", "Grain"], 0],
    ["Which ancient strategy board game uses black and white stones on a grid?", ["Go", "Mancala", "Backgammon", "Parcheesi"], 0],
    ["Which video game contains the hidden 'Konami Code' in many Konami titles?", ["Contra", "Minecraft", "Portal", "The Sims"], 0],
    ["Which console was Sega's final home video game console?", ["Dreamcast", "Saturn", "Genesis", "Master System"], 0],
    ["Which game series features the fictional city of Rapture?", ["BioShock", "Half-Life", "Fallout", "Resident Evil"], 0],
    ["In poker, which hand ranks highest?", ["Royal flush", "Straight flush", "Four of a kind", "Full house"], 0],
    ["In contract bridge, how many players are at the table?", ["4", "2", "3", "5"], 0],
    ["Which solitaire variant uses seven tableau columns in its classic layout?", ["Klondike", "Spider", "FreeCell", "Pyramid"], 0],
    ["What is the classic riddle answer to 'What has keys but can't open locks?'", ["Piano", "Map", "Clock", "Book"], 0],
    ["In Dungeons & Dragons 5e, what die is commonly rolled for ability checks?", ["d20", "d4", "d8", "d12"], 0],
    ["In Dungeons & Dragons, what does NPC stand for?", ["Non-player character", "New power class", "Neutral party caster", "Night patrol captain"], 0],
    ["Which arcade game was the first major hit created by Nintendo's Shigeru Miyamoto?", ["Donkey Kong", "Pac-Man", "Space Invaders", "Street Fighter II"], 0],
    ["Which pinball component launches the ball onto the playfield?", ["Plunger", "Flipper", "Bumper", "Tilt bob"], 0],
    ["Which 1990s toy fad involved digital pets on keychains?", ["Tamagotchi", "Pogs", "Furby", "Skip-It"], 0],
    ["Which cuisine uses injera as a staple flatbread?", ["Ethiopian", "Vietnamese", "French", "Polish"], 0],
    ["Which dish is traditionally made with raw fish cured in citrus juice?", ["Ceviche", "Fondue", "Paella", "Goulash"], 0],
    ["Which spice is derived from the dried stigmas of Crocus sativus?", ["Saffron", "Turmeric", "Cardamom", "Star anise"], 0],
    ["Which herb is traditionally used in béarnaise sauce?", ["Tarragon", "Rosemary", "Cilantro", "Bay leaf"], 0],
    ["Which drink is made from fermented tea and often contains live cultures?", ["Kombucha", "Espresso", "Horchata", "Ayran"], 0],
    ["Which dessert is made from layers of filo pastry, nuts, and syrup?", ["Baklava", "Pavlova", "Cannoli", "Flan"], 0],
    ["Which baking method uses steam trapped inside dough to make layers rise in croissants?", ["Lamination", "Tempering", "Fermentation only", "Blanching"], 0],
    ["Which mascot represents Michelin tires?", ["Bibendum", "Tony", "Julius Pringles", "Chester"], 0],
    ["Which ingredient gives Worcestershire sauce much of its savory depth?", ["Anchovies", "Chocolate", "Vanilla", "Cucumber"], 0],
    ["Which cheese is traditionally used for authentic Parmigiano-Reggiano?", ["Cow's milk", "Goat's milk only", "Sheep's milk only", "Buffalo milk only"], 0],
    ["Which pasta name means 'little ears' in Italian?", ["Orecchiette", "Fusilli", "Pappardelle", "Bucatini"], 0],
    ["Which city hosted the first modern Olympic Games in 1896?", ["Athens", "Paris", "London", "Rome"], 0],
    ["Which country won the first FIFA World Cup in 1930?", ["Uruguay", "Brazil", "Argentina", "Italy"], 0],
    ["In baseball, what is a 'cycle'?", ["Single, double, triple, and home run in one game", "Four strikeouts in a row", "A no-hit inning", "Stealing every base"], 0],
    ["In sepak takraw, which body part is generally not used to hit the ball?", ["Hands", "Feet", "Head", "Knees"], 0],
    ["Which boxer was nicknamed 'The Greatest'?", ["Muhammad Ali", "Mike Tyson", "Floyd Mayweather Jr.", "Joe Frazier"], 0],
    ["Which NBA arena is nicknamed 'The Garden'?", ["Madison Square Garden", "Crypto.com Arena", "United Center", "TD Garden only"], 0],
    ["In taekwondo, what color belt commonly represents a beginner in many schools?", ["White", "Black", "Red", "Blue"], 0],
    ["Which hiking trail runs from Georgia to Maine in the United States?", ["Appalachian Trail", "Pacific Crest Trail", "Camino de Santiago", "Inca Trail"], 0],
    ["In gymnastics, which apparatus is used only in men's artistic gymnastics?", ["Pommel horse", "Balance beam", "Uneven bars", "Ribbon"], 0],
    ["Which surrealist painter created The Persistence of Memory?", ["Salvador Dalí", "Henri Matisse", "Jackson Pollock", "Georgia O'Keeffe"], 0],
    ["Which sculpture by Michelangelo depicts a biblical hero before battle?", ["David", "The Thinker", "Venus de Milo", "Pietà only"], 0],
    ["Which novel is set in the fictional county of Yoknapatawpha?", ["The Sound and the Fury", "Jane Eyre", "The Great Gatsby", "Dune"], 0],
    ["Which protagonist narrates The Catcher in the Rye?", ["Holden Caulfield", "Jay Gatsby", "Scout Finch", "Winston Smith"], 0],
    ["Which writing system is used for Korean?", ["Hangul", "Hiragana", "Cyrillic", "Devanagari"], 0],
    ["Which word is often cited as a German term for taking pleasure in another's misfortune?", ["Schadenfreude", "Déjà vu", "Saudade", "Hygge"], 0],
    ["Which creature in Greek mythology has a lion's body, eagle's head, and wings?", ["Griffin", "Minotaur", "Cyclops", "Hydra"], 0],
    ["Which architectural style is associated with raw concrete and massive forms?", ["Brutalism", "Rococo", "Gothic", "Neoclassical"], 0],
    ["Which designer founded a fashion house famous for the 'New Look' of 1947?", ["Christian Dior", "Yves Saint Laurent", "Coco Chanel", "Alexander McQueen"], 0],
    ["Which economist is associated with The General Theory of Employment, Interest and Money?", ["John Maynard Keynes", "Adam Smith", "Milton Friedman", "Karl Marx"], 0],
    ["In microeconomics, what is the price elasticity of demand concerned with?", ["Quantity demanded response to price changes", "Weather response to crops", "Interest paid on bonds", "Currency exchange dates"], 0],
    ["Which company changed its corporate name to Alphabet in a 2015 restructuring?", ["Google", "Facebook", "Microsoft", "Amazon"], 0],
    ["Which stock market index tracks 30 large U.S. companies?", ["Dow Jones Industrial Average", "NASDAQ Composite", "FTSE 100", "Nikkei 225"], 0],
    ["Which currency's symbol is ¥?", ["Japanese yen", "British pound", "Indian rupee", "Russian ruble"], 0],
    ["Who is commonly credited with inventing the modern ballpoint pen?", ["László Bíró", "Thomas Edison", "Alexander Graham Bell", "Eli Whitney"], 0],
    ["Which city is served by the public transit system known as the Tube?", ["London", "New York", "Tokyo", "Paris"], 0],
    ["Which advertising campaign used the line 'Got Milk?'", ["California Milk Processor Board", "Coca-Cola", "Nike", "Apple"], 0],
    ["Which part of a supply chain moves goods from producers to consumers?", ["Distribution", "Photosynthesis", "Refraction", "Fermentation"], 0],
    ["Which holiday tradition involves hiding painted eggs?", ["Easter", "Diwali", "Hanukkah", "Thanksgiving"], 0],
    ["Which country's flag is red with a large yellow star?", ["Vietnam", "Japan", "Canada", "Greece"], 0],
    ["Which country has the capital city Canberra?", ["Australia", "New Zealand", "Canada", "South Africa"], 0],
    ["Which DIY tool is used to make holes with rotating bits?", ["Drill", "Level", "Clamp", "Trowel"], 0],
    ["Which gardening term means trimming plants to shape or improve growth?", ["Pruning", "Soldering", "Grouting", "Priming"], 0],
    ["In Japanese etiquette, what gesture commonly accompanies a formal greeting?", ["Bowing", "Snapping fingers", "Winking", "Whistling"], 0],
    ["Which zodiac sign is represented by a water bearer?", ["Aquarius", "Capricorn", "Sagittarius", "Taurus"], 0],
    ["Which birthstone is traditionally associated with July?", ["Ruby", "Sapphire", "Pearl", "Topaz"], 0],
    ["Which textile weave creates denim's diagonal rib pattern?", ["Twill", "Satin", "Plain weave", "Jacquard only"], 0]
  ]
};

const baseQuestions = Object.fromEntries(
  Object.entries(rawTriviaQuestions).map(([difficulty, questions]) => [
    difficulty,
    questions.map(([question, answers, correctIndex]) => ({ question, answers, correctIndex })),
  ]),
);

module.exports = {
  easy: baseQuestions.easy,
  medium: baseQuestions.medium,
  hard: baseQuestions.hard,
};
