const generatedTriviaQuestions = require('./triviaGeneratedQuestions');

const rawTriviaQuestions = {
  easy: [
    ["What color is a ripe banana usually?", ["Yellow", "Black", "Blue", "Purple"], 0],
    ["How many days are in one week?", ["5", "12", "7", "10"], 2],
    ["Which animal says “meow”?", ["Cat", "Dog", "Duck", "Cow"], 0],
    ["What do bees make?", ["Milk", "Rice", "Bread", "Honey"], 3],
    ["Which planet do we live on?", ["Mars", "Jupiter", "Earth", "Venus"], 2],
    ["How many wheels does a standard bicycle have?", ["4", "1", "2", "3"], 2],
    ["What is H2O commonly called?", ["Sugar", "Water", "Salt", "Oxygen"], 1],
    ["Which fruit is known for keeping doctors away in a saying?", ["Mango", "Apple", "Pear", "Lemon"], 1],
    ["What do you use to write on paper?", ["Plate", "Spoon", "Pillow", "Pencil"], 3],
    ["Which season is usually the coldest?", ["Winter", "Autumn", "Spring", "Summer"], 0],
    ["How many months are in a year?", ["10", "12", "8", "14"], 1],
    ["What shape has three sides?", ["Hexagon", "Square", "Triangle", "Circle"], 2],
    ["Which animal is known as man's best friend?", ["Fish", "Dog", "Tiger", "Eagle"], 1],
    ["What is the opposite of hot?", ["Bright", "Cold", "Fast", "Tall"], 1],
    ["Which meal is usually eaten in the morning?", ["Supper", "Dessert", "Dinner", "Breakfast"], 3],
    ["What do plants need from the sun?", ["Glass", "Sand", "Light", "Metal"], 2],
    ["Which device is used to call people?", ["Bottle", "Toaster", "Chair", "Phone"], 3],
    ["What color do you get by mixing red and white?", ["Pink", "Orange", "Green", "Brown"], 0],
    ["How many legs does a spider have?", ["4", "10", "6", "8"], 3],
    ["Which object tells time?", ["Clock", "Key", "Brush", "Cup"], 0],
    ["What is frozen water called?", ["Ice", "Cloud", "Dust", "Steam"], 0],
    ["Which bird is often associated with delivering babies in cartoons?", ["Peacock", "Penguin", "Stork", "Ostrich"], 2],
    ["What is the main ingredient in bread?", ["Flour", "Stone", "Oil", "Cheese"], 0],
    ["How many letters are in the English alphabet?", ["18", "20", "26", "30"], 2],
    ["Which animal gives milk?", ["Frog", "Shark", "Cow", "Lion"], 2],
    ["What is the color of grass in most places?", ["Red", "Pink", "White", "Green"], 3],
    ["Which tool is used to cut paper?", ["Fork", "Scissors", "Hammer", "Sponge"], 1],
    ["Where do fish usually live?", ["Tree", "Water", "Desert", "Sky"], 1],
    ["What do you wear on your feet?", ["Gloves", "Hat", "Scarf", "Shoes"], 3],
    ["Which food is made from milk?", ["Cheese", "Potato", "Popcorn", "Pasta"], 0],
    ["What number comes after 9?", ["11", "8", "10", "7"], 2],
    ["Which sport uses a soccer ball?", ["Football", "Golf", "Baseball", "Tennis"], 0],
    ["What do you drink when you are thirsty?", ["Soap", "Sand", "Water", "Paper"], 2],
    ["Which animal has a long trunk?", ["Bear", "Rabbit", "Horse", "Elephant"], 3],
    ["What do you use to unlock a door?", ["Leaf", "Coin", "Key", "Pen"], 2],
    ["Which day usually comes after Friday?", ["Thursday", "Saturday", "Wednesday", "Monday"], 1],
    ["What is the opposite of up?", ["Down", "Wide", "Near", "Left"], 0],
    ["Which fruit is long and yellow?", ["Plum", "Banana", "Grape", "Cherry"], 1],
    ["What do you use to see in the dark?", ["Ruler", "Bowl", "Blanket", "Flashlight"], 3],
    ["Which animal hops and has long ears?", ["Snake", "Chicken", "Whale", "Rabbit"], 3],
    ["How many fingers are on one normal human hand?", ["8", "6", "4", "5"], 3],
    ["What is the color of the sky on a clear day?", ["Black", "Green", "Blue", "Orange"], 2],
    ["Which drink is made from oranges?", ["Coffee", "Tea", "Milkshake", "Orange juice"], 3],
    ["What do you call a young cat?", ["Foal", "Kitten", "Puppy", "Calf"], 1],
    ["Which room is used for cooking?", ["Garage", "Kitchen", "Bedroom", "Bathroom"], 1],
    ["What is the opposite of fast?", ["Soft", "Loud", "Slow", "Round"], 2],
    ["Which item keeps rain off your head?", ["Spoon", "Umbrella", "Sock", "Book"], 1],
    ["What do chickens lay?", ["Coins", "Eggs", "Leaves", "Rocks"], 1],
    ["Which animal is black and white and eats bamboo?", ["Panda", "Giraffe", "Fox", "Koala"], 0],
    ["What do you use to brush your teeth?", ["Paintbrush", "Toothbrush", "Comb", "Fork"], 1],
    ["Which food is commonly sliced and put on pizza?", ["Candy cane", "Rice", "Ice", "Cheese"], 3],
    ["How many sides does a square have?", ["5", "6", "4", "3"], 2],
    ["What animal is known for having stripes and looking like a horse?", ["Moose", "Camel", "Zebra", "Deer"], 2],
    ["Which vehicle travels on rails?", ["Boat", "Plane", "Train", "Scooter"], 2],
    ["What does a thermometer measure?", ["Weight", "Color", "Temperature", "Speed"], 2],
    ["Which fruit is red and often used in ketchup?", ["Coconut", "Blueberry", "Tomato", "Lemon"], 2],
    ["What do you use to eat soup?", ["Straw", "Knife", "Spoon", "Chopstick only"], 2],
    ["Which place has many books you can borrow?", ["Stadium", "Bakery", "Library", "Airport"], 2],
    ["What do you call water falling from clouds?", ["Steam", "Rain", "Smoke", "Snow only"], 1],
    ["Which animal is famous for roaring?", ["Mouse", "Goat", "Duck", "Lion"], 3],
    ["What is the first letter of the English alphabet?", ["Z", "Y", "B", "A"], 3],
    ["Which object is used to take photos?", ["Blanket", "Keyboard", "Camera", "Cup"], 2],
    ["What do you call a baby dog?", ["Puppy", "Kitten", "Chick", "Calf"], 0],
    ["Which game piece is used in chess and can move like an L?", ["Bishop", "Pawn", "King", "Knight"], 3],
    ["What do you sleep on?", ["Table", "Sink", "Bed", "Shelf"], 2],
    ["Which fruit has a hard shell and white inside?", ["Peach", "Apple", "Coconut", "Strawberry"], 2],
    ["What is the opposite of day?", ["Night", "Light", "Noon", "Morning"], 0],
    ["Which animal is known for making webs?", ["Butterfly", "Bee", "Spider", "Ant"], 2],
    ["What do you use to clean your hands?", ["Soap", "Glue", "Paint", "Salt"], 0],
    ["Which food is made by popping corn kernels?", ["Cake", "Popcorn", "Bread", "Noodles"], 1],
    ["What do you call the place where airplanes land?", ["Library", "Farm", "Airport", "Harbor"], 2],
    ["Which animal swims and has fins?", ["Cat", "Horse", "Fish", "Dog"], 2],
    ["How many cents are in one US dollar?", ["25", "10", "50", "100"], 3],
    ["Which object is used to measure length?", ["Lamp", "Bowl", "Brush", "Ruler"], 3],
    ["What do you call a group of stars forming a pattern?", ["Island", "Recipe", "Keyboard", "Constellation"], 3],
    ["Which dessert is cold and creamy?", ["Ice cream", "Toast", "Soup", "Rice"], 0],
    ["What do you wear on your head?", ["Belt", "Shoes", "Hat", "Gloves"], 2],
    ["Which animal is known for carrying a shell?", ["Rabbit", "Fox", "Bear", "Turtle"], 3],
    ["What is the opposite of big?", ["Tall", "Bright", "Small", "Heavy"], 2],
    ["Which food is commonly made from potatoes?", ["Yogurt", "Sushi", "Fries", "Pancakes"], 2],
    ["What do you use to open a can?", ["Can opener", "Pencil", "Pillow", "Mirror"], 0],
    ["Which insect has colorful wings and starts as a caterpillar?", ["Ant", "Butterfly", "Mosquito", "Beetle"], 1],
    ["What does a baker usually make?", ["Shoes", "Bread", "Jewelry", "Furniture"], 1],
    ["How many sides does a hexagon have?", ["7", "5", "6", "8"], 2],
    ["Which ocean animal is known for being very large?", ["Lizard", "Ant", "Whale", "Rabbit"], 2],
    ["What do you call cooked rice wrapped with seaweed and fillings?", ["Sushi", "Curry", "Pizza", "Taco"], 0],
    ["Which item is used to carry school supplies?", ["Plate", "Teacup", "Remote", "Backpack"], 3],
    ["What color are most lemons?", ["Brown", "Purple", "Blue", "Yellow"], 3],
    ["Which animal is known for climbing trees and liking bananas?", ["Shark", "Penguin", "Camel", "Monkey"], 3],
    ["What does a keyboard help you do?", ["Paint walls", "Type", "Cook", "Swim"], 1],
    ["Which month comes after January?", ["December", "April", "March", "February"], 3],
    ["What do you call a person who teaches students?", ["Chef", "Pilot", "Teacher", "Artist"], 2],
    ["Which sport uses a hoop and a ball?", ["Basketball", "Skiing", "Golf", "Cricket"], 0],
    ["What is the opposite of left?", ["Under", "Thin", "Over", "Right"], 3],
    ["Which vegetable is orange and loved by rabbits in cartoons?", ["Pea", "Onion", "Cabbage", "Carrot"], 3],
    ["What do you use to cut wood?", ["Comb", "Spoon", "Saw", "Needle"], 2],
    ["Which animal is known for its long neck?", ["Giraffe", "Panda", "Duck", "Pig"], 0],
    ["What do you call the star at the center of our solar system?", ["Venus", "Earth", "Moon", "Sun"], 3],
    ["Which snack is made from cocoa and sugar?", ["Cheese", "Chocolate", "Bread", "Pickle"], 1],
    ["Which object do you use to erase pencil marks?", ["Eraser", "Spoon", "Rope", "Bottle"], 0]
  ],
  medium: [
    ["Which gas do plants absorb during photosynthesis?", ["Oxygen", "Neon", "Carbon dioxide", "Helium"], 2],
    ["What is the largest planet in our solar system?", ["Jupiter", "Earth", "Mars", "Saturn"], 0],
    ["Which instrument has keys, pedals, and strings inside?", ["Flute", "Trumpet", "Piano", "Drum"], 2],
    ["What is the process of liquid water becoming vapor called?", ["Condensation", "Melting", "Evaporation", "Freezing"], 2],
    ["Which country is famous for sushi as a traditional food?", ["Italy", "Egypt", "Japan", "Mexico"], 2],
    ["What is the square root of 144?", ["16", "10", "12", "14"], 2],
    ["Which organ pumps blood through the body?", ["Liver", "Heart", "Lung", "Kidney"], 1],
    ["Which metal is commonly used in electric wires?", ["Silver only", "Copper", "Tin", "Lead"], 1],
    ["What is the main language used to style web pages?", ["SQL", "CSS", "HTML", "Python"], 1],
    ["In chess, which piece can move diagonally any distance?", ["Pawn", "Bishop", "Knight", "Rook"], 1],
    ["Which layer of Earth is liquid outer metal?", ["Outer core", "Mantle", "Inner core", "Crust"], 0],
    ["What is the freezing point of water in Celsius?", ["32°C", "10°C", "100°C", "0°C"], 3],
    ["Which vitamin is commonly produced by skin in sunlight?", ["Vitamin D", "Vitamin A", "Vitamin B12", "Vitamin K"], 0],
    ["What is the hardest natural substance?", ["Iron", "Quartz", "Gold", "Diamond"], 3],
    ["Which sport is played at Wimbledon?", ["Table tennis", "Basketball", "Rugby", "Tennis"], 3],
    ["What is the chemical symbol for gold?", ["Au", "Gd", "Go", "Ag"], 0],
    ["Which planet is known for its rings?", ["Mars", "Venus", "Saturn", "Mercury"], 2],
    ["What do you call animals that eat both plants and meat?", ["Omnivores", "Carnivores", "Insectivores", "Herbivores"], 0],
    ["Which data structure uses first-in, first-out behavior?", ["Queue", "Graph", "Stack", "Tree"], 0],
    ["Which famous scientist proposed the laws of motion?", ["Nikola Tesla", "Albert Einstein", "Isaac Newton", "Marie Curie"], 2],
    ["What is the largest ocean on Earth?", ["Indian Ocean", "Atlantic Ocean", "Arctic Ocean", "Pacific Ocean"], 3],
    ["Which part of a plant absorbs water from soil?", ["Fruit", "Petals", "Roots", "Stem only"], 2],
    ["What is the smallest prime number?", ["1", "5", "3", "2"], 3],
    ["Which programming language is often used with Node.js?", ["C", "Swift", "Ruby", "JavaScript"], 3],
    ["What is the main ingredient in guacamole?", ["Cucumber", "Potato", "Avocado", "Tomato"], 2],
    ["Which type of energy is stored in a stretched spring?", ["Potential energy", "Thermal energy", "Kinetic energy", "Light energy"], 0],
    ["What is the capital city of France?", ["Lyon", "Nice", "Paris", "Marseille"], 2],
    ["Which animal is a marsupial?", ["Tiger", "Penguin", "Elephant", "Kangaroo"], 3],
    ["How many degrees are in a right angle?", ["45", "360", "180", "90"], 3],
    ["Which blood cells help carry oxygen?", ["Platelets", "Red blood cells", "White blood cells", "Plasma"], 1],
    ["What does CPU stand for?", ["Central Processing Unit", "Core Program Unit", "Computer Power Utility", "Central Pixel Unit"], 0],
    ["Which continent is the Sahara Desert located in?", ["South America", "Europe", "Asia", "Africa"], 3],
    ["Which food is made by fermenting milk?", ["Bread crumbs", "Pasta", "Yogurt", "Jam"], 2],
    ["What is the chemical symbol for sodium?", ["So", "N", "Sd", "Na"], 3],
    ["Which unit measures electrical resistance?", ["Ampere", "Volt", "Ohm", "Watt"], 2],
    ["What is the study of weather called?", ["Botany", "Geology", "Meteorology", "Astronomy"], 2],
    ["Which polygon has eight sides?", ["Heptagon", "Octagon", "Pentagon", "Hexagon"], 1],
    ["Which bone protects the brain?", ["Tibia", "Skull", "Rib", "Femur"], 1],
    ["What is the main gas in Earth's atmosphere?", ["Hydrogen", "Oxygen", "Nitrogen", "Carbon dioxide"], 2],
    ["Which musical term means to play softly?", ["Piano", "Allegro", "Forte", "Presto"], 0],
    ["What is the largest land animal alive today?", ["Hippopotamus", "Rhino", "African elephant", "Giraffe"], 2],
    ["Which web protocol is used for secure websites?", ["FTP", "SMTP", "HTTPS", "DNS"], 2],
    ["Which part of speech describes an action?", ["Preposition", "Adjective", "Noun", "Verb"], 3],
    ["What is the formula for the area of a rectangle?", ["π × radius", "base + height", "side × side × side", "length × width"], 3],
    ["Which planet is closest to the Sun?", ["Mars", "Mercury", "Venus", "Earth"], 1],
    ["What is the name of the galaxy that contains Earth?", ["Triangulum", "Sombrero", "Andromeda", "Milky Way"], 3],
    ["Which cooking method uses hot oil?", ["Steaming", "Freezing", "Drying", "Frying"], 3],
    ["What is the main function of leaves?", ["Protect bark", "Make food", "Store seeds", "Anchor roots"], 1],
    ["Which SI unit measures force?", ["Pascal", "Newton", "Joule", "Tesla"], 1],
    ["Which animal is known for echolocation?", ["Horse", "Bat", "Panda", "Rabbit"], 1],
    ["What is the decimal form of 1/4?", ["0.25", "0.2", "0.75", "0.5"], 0],
    ["Which element has the chemical symbol O?", ["Oxygen", "Osmium", "Opal", "Gold"], 0],
    ["Which game genre focuses on building and managing resources?", ["Rhythm", "Fighting", "Simulation", "Platformer"], 2],
    ["What is the common name for NaCl?", ["Sugar", "Baking soda", "Salt", "Vinegar"], 2],
    ["Which planet is called the Red Planet?", ["Neptune", "Venus", "Mars", "Jupiter"], 2],
    ["What do you call the force that pulls objects toward Earth?", ["Gravity", "Friction", "Buoyancy", "Magnetism"], 0],
    ["Which device stores electrical energy chemically?", ["Router", "Speaker", "Monitor", "Battery"], 3],
    ["What is a group of wolves called?", ["Pack", "School", "Flock", "Herd"], 0],
    ["Which famous board game uses properties and rent?", ["Monopoly", "Clue", "Risk", "Scrabble"], 0],
    ["Which number is represented by the Roman numeral X?", ["100", "5", "10", "50"], 2],
    ["Which part of a computer displays images?", ["Printer", "Mouse", "Monitor", "Keyboard"], 2],
    ["What is the pH of pure water at room temperature?", ["14", "1", "10", "7"], 3],
    ["Which animal is the fastest land animal?", ["Horse", "Cheetah", "Lion", "Deer"], 1],
    ["What is the main ingredient of tofu?", ["Rice", "Soybeans", "Wheat", "Corn"], 1],
    ["Which branch of science studies living things?", ["Biology", "Geology", "Astronomy", "Physics"], 0],
    ["What is the value of 9 × 8?", ["68", "81", "72", "64"], 2],
    ["Which cloud type is fluffy and often seen in fair weather?", ["Nimbus", "Cirrus", "Cumulus", "Stratus"], 2],
    ["Which country is known for inventing pizza in its modern form?", ["Italy", "Brazil", "India", "Canada"], 0],
    ["What is the name of the fictional wizard school in Harry Potter?", ["Hogwarts", "Narnia", "Mordor", "Gotham"], 0],
    ["Which organ helps humans breathe?", ["Stomach", "Spleen", "Lungs", "Pancreas"], 2],
    ["What is the term for animals active at night?", ["Migratory", "Domestic", "Nocturnal", "Aquatic"], 2],
    ["Which mathematical constant is approximately 3.14159?", ["Phi", "Pi", "Euler's number", "Tau only"], 1],
    ["Which programming concept repeats code while a condition is true?", ["Array", "Class", "Comment", "Loop"], 3],
    ["What is the largest mammal?", ["Blue whale", "Orca", "Giraffe", "Elephant"], 0],
    ["Which material is made by heating sand and other minerals?", ["Rubber", "Cotton", "Glass", "Plastic"], 2],
    ["What is a baby frog called?", ["Foal", "Cub", "Larva only", "Tadpole"], 3],
    ["Which gas do humans breathe in to survive?", ["Argon", "Nitrogen only", "Methane", "Oxygen"], 3],
    ["What is the center of an atom called?", ["Molecule", "Electron cloud", "Shell", "Nucleus"], 3],
    ["Which country is associated with tacos as a traditional food?", ["Greece", "Norway", "Thailand", "Mexico"], 3],
    ["What is 15% of 200?", ["25", "30", "35", "20"], 1],
    ["Which star is closest to Earth?", ["The Sun", "Sirius", "Polaris", "Vega"], 0],
    ["What is the name of the force opposing motion between surfaces?", ["Gravity", "Friction", "Tension", "Lift"], 1],
    ["Which sea creature has eight arms?", ["Octopus", "Seal", "Crab", "Dolphin"], 0],
    ["Which kind of triangle has all sides equal?", ["Right", "Equilateral", "Scalene", "Isosceles only"], 1],
    ["Which file extension is commonly used for JavaScript files?", [".html", ".css", ".py", ".js"], 3],
    ["What is the edible part of broccoli called?", ["Roots", "Seeds", "Bark", "Flower buds"], 3],
    ["Which instrument measures air pressure?", ["Thermometer", "Barometer", "Hygrometer", "Compass"], 1],
    ["What is the main function of the skeleton?", ["Pump blood", "Filter air", "Digest food", "Support the body"], 3],
    ["Which planet has the Great Red Spot?", ["Saturn", "Neptune", "Jupiter", "Mars"], 2],
    ["Which HTML tag is commonly used for a paragraph?", ["<table>", "<script>", "<p>", "<img>"], 2],
    ["What is the process of a caterpillar becoming a butterfly called?", ["Metamorphosis", "Fermentation", "Photosynthesis", "Evaporation"], 0],
    ["Which sport uses a shuttlecock?", ["Badminton", "Volleyball", "Squash", "Tennis"], 0],
    ["What is the main ingredient in hummus?", ["Potatoes", "Chickpeas", "Eggs", "Apples"], 1],
    ["Which machine is used to print documents?", ["Scanner", "Printer", "Projector", "Router"], 1],
    ["What is the name for a word that has the opposite meaning?", ["Suffix", "Prefix", "Synonym", "Antonym"], 3],
    ["Which part of Earth do tectonic plates belong to?", ["Biosphere", "Hydrosphere", "Atmosphere", "Lithosphere"], 3],
    ["How many players are on a standard soccer team on the field?", ["9", "10", "11", "12"], 2],
    ["Which sense uses the tongue?", ["Sight", "Taste", "Touch", "Hearing"], 1],
    ["Which shape is the base of most traffic stop signs?", ["Triangle", "Octagon", "Circle", "Pentagon"], 1],
    ["What type of animal is a salmon?", ["Reptile", "Mammal", "Fish", "Bird"], 2]
  ],
  hard: [
    ["Which sorting algorithm has average-case time complexity O(n log n) and commonly uses partitioning?", ["Bubble sort", "Insertion sort", "Quicksort", "Linear search"], 2],
    ["What is the approximate speed of light in vacuum?", ["300,000 km/s", "3,000,000 km/s", "3,000 km/s", "30,000 km/s"], 0],
    ["Which element has atomic number 6?", ["Carbon", "Silicon", "Oxygen", "Nitrogen"], 0],
    ["In music theory, how many semitones are in an octave?", ["8", "7", "10", "12"], 3],
    ["Which mathematical sequence begins 0, 1, 1, 2, 3, 5?", ["Fibonacci", "Prime", "Geometric", "Triangular"], 0],
    ["What is the powerhouse organelle of the cell?", ["Mitochondrion", "Ribosome", "Golgi apparatus", "Nucleus"], 0],
    ["Which database language is commonly used for querying relational databases?", ["CSS", "Bash", "HTML", "SQL"], 3],
    ["What is the derivative of x²?", ["2x", "x³", "2", "x"], 0],
    ["Which planet has the shortest day among the planets?", ["Mercury", "Jupiter", "Earth", "Neptune"], 1],
    ["What is the main structural protein found in hair and nails?", ["Collagen", "Keratin", "Elastin", "Casein"], 1],
    ["Which algorithm finds shortest paths from one source in a weighted graph with nonnegative edges?", ["K-means", "Merge sort", "A* without heuristic", "Dijkstra's algorithm"], 3],
    ["What is the SI unit of electric capacitance?", ["Weber", "Farad", "Henry", "Ohm"], 1],
    ["Which number system uses base 16?", ["Octal", "Binary", "Decimal", "Hexadecimal"], 3],
    ["What is the term for the fear of long words?", ["Hippopotomonstrosesquipedaliophobia", "Claustrophobia", "Arachnophobia", "Acrophobia"], 0],
    ["Which amino acid is often represented by the one-letter code W?", ["Tryptophan", "Threonine", "Tyrosine", "Valine"], 0],
    ["Which protocol translates domain names into IP addresses?", ["HTTP", "DNS", "SMTP", "SSH"], 1],
    ["What is the value of 2⁸?", ["128", "256", "64", "512"], 1],
    ["Which moon is the largest moon of Saturn?", ["Europa", "Io", "Ganymede", "Titan"], 3],
    ["What is the term for a word spelled the same backward and forward?", ["Anagram", "Acronym", "Palindrome", "Homonym"], 2],
    ["Which type of bond involves shared electron pairs?", ["Metallic bond", "Hydrogen bond only", "Covalent bond", "Ionic bond"], 2],
    ["What is the normal form targeted by eliminating transitive dependency in relational design?", ["Boyce-Codd only", "Zero normal form", "Third normal form", "First normal form"], 2],
    ["Which lens type is thicker in the center and converges light?", ["Concave lens", "Flat lens", "Convex lens", "Cylindrical lens"], 2],
    ["What is the term for animals that maintain constant internal body temperature?", ["Autotrophs", "Decomposers", "Endotherms", "Ectotherms"], 2],
    ["Which compression format is commonly lossless for images?", ["JPEG", "PNG", "MP4", "AAC"], 1],
    ["What is the result of 7 factorial?", ["720", "5040", "40320", "840"], 1],
    ["Which compound is commonly known as baking soda?", ["Sodium bicarbonate", "Sodium chloride", "Calcium carbonate", "Acetic acid"], 0],
    ["Which programming paradigm treats computation as evaluating functions?", ["Object storage", "Functional programming", "Procedural programming", "Markup programming"], 1],
    ["What is the longest side of a right triangle called?", ["Base only", "Hypotenuse", "Median", "Altitude"], 1],
    ["Which biological molecule stores genetic information?", ["Cellulose", "Lipid", "DNA", "Starch"], 2],
    ["What is the name for molten rock beneath Earth's surface?", ["Lava", "Pumice", "Basalt", "Magma"], 3],
    ["Which HTTP status code means Not Found?", ["500", "301", "200", "404"], 3],
    ["What is the integral of 1/x with respect to x?", ["1/x² + C", "x² + C", "eˣ + C", "ln|x| + C"], 3],
    ["Which constellation contains the star Betelgeuse?", ["Scorpius", "Cygnus", "Orion", "Ursa Major"], 2],
    ["What is the chemical formula of glucose?", ["H2SO4", "NaOH", "C6H12O6", "CO2"], 2],
    ["Which term describes light bending as it passes between media?", ["Absorption", "Refraction", "Diffusion", "Reflection"], 1],
    ["What is the base unit of luminous intensity in SI?", ["Watt", "Lumen", "Candela", "Lux"], 2],
    ["Which software design principle says classes should have one reason to change?", ["Factory Rule", "Single Responsibility Principle", "Singleton Rule", "Open Loop Principle"], 1],
    ["Which enzyme starts starch digestion in the mouth?", ["Pepsin", "Amylase", "Lactase", "Lipase"], 1],
    ["What is the approximate value of Euler's number e?", ["3.142", "2.718", "1.618", "0.577"], 1],
    ["Which data structure is typically used for recursion call management?", ["Queue", "Hash table", "Stack", "Heap"], 2],
    ["Which planet has the most confirmed moons as of recent astronomy counts?", ["Saturn", "Venus", "Earth", "Mars"], 0],
    ["What is the term for a triangle with two equal sides?", ["Equilateral only", "Isosceles", "Scalene", "Obtuse"], 1],
    ["Which mineral scale measures scratch hardness?", ["Mohs scale", "pH scale", "Richter scale", "Beaufort scale"], 0],
    ["What is the smallest unit of sound in a spoken language?", ["Morpheme", "Clause", "Phoneme", "Syllable"], 2],
    ["Which computer memory is volatile?", ["SSD", "Blu-ray", "RAM", "ROM"], 2],
    ["What is the common name for ascorbic acid?", ["Vitamin D", "Vitamin C", "Vitamin B1", "Vitamin K"], 1],
    ["Which law states pressure and volume are inversely related at constant temperature?", ["Charles's law", "Boyle's law", "Ohm's law", "Hooke's law"], 1],
    ["What is the center of mass of a triangle called?", ["Incenter", "Orthocenter", "Centroid", "Circumcenter"], 2],
    ["Which language is primarily used with the Unity game engine for scripting?", ["C#", "Perl", "R", "PHP"], 0],
    ["What is the process of converting sugar into acids or alcohol by microorganisms?", ["Fermentation", "Pasteurization", "Caramelization", "Crystallization"], 0],
    ["Which star type is the Sun classified as?", ["G-type main-sequence star", "White dwarf", "Neutron star", "Red giant"], 0],
    ["What does API stand for?", ["Advanced Packet Input", "Applied Program Internet", "Application Programming Interface", "Automated Page Index"], 2],
    ["Which equation relates voltage, current, and resistance?", ["Ohm's law", "Bernoulli's principle", "Newton's second law", "Snell's law"], 0],
    ["What is the term for a market with one dominant seller?", ["Perfect competition", "Duopoly only", "Oligopsony", "Monopoly"], 3],
    ["Which molecule is the primary energy currency of cells?", ["Chlorophyll", "DNA", "ATP", "RNA"], 2],
    ["Which graph traversal uses a queue?", ["Depth-first search", "Breadth-first search", "Heap sort", "Binary search"], 1],
    ["What is the value of log10(1000)?", ["3", "10", "100", "2"], 0],
    ["Which spice gives curry its bright yellow color?", ["Nutmeg", "Paprika", "Turmeric", "Cinnamon"], 2],
    ["Which number is the additive identity?", ["1", "0", "-1", "10"], 1],
    ["What is the term for the boundary where two air masses meet?", ["Isobar", "Cyclone", "Jet stream", "Front"], 3],
    ["Which HTML attribute provides alternative text for images?", ["alt", "href", "class", "src"], 0],
    ["What is the primary pigment involved in photosynthesis?", ["Keratin", "Hemoglobin", "Chlorophyll", "Melanin"], 2],
    ["Which regular polygon has internal angles of 120 degrees?", ["Octagon", "Hexagon", "Square", "Pentagon"], 1],
    ["What is the name of the statistical value in the middle of ordered data?", ["Range", "Mode", "Median", "Mean"], 2],
    ["Which concept describes resistance to changes in motion?", ["Inertia", "Impulse", "Momentum only", "Torque"], 0],
    ["Which food science process browns sugars and proteins together?", ["Caramelization", "Sublimation", "Osmosis", "Maillard reaction"], 3],
    ["What is the unit of frequency?", ["Pascal", "Newton", "Joule", "Hertz"], 3],
    ["Which command-line system is commonly used to track code versions?", ["Docker", "Node", "Git", "NPM"], 2],
    ["What is the name of a 3D shape with six square faces?", ["Cylinder", "Sphere", "Cone", "Cube"], 3],
    ["Which gas is commonly used by balloons to float?", ["Nitrogen", "Helium", "Carbon dioxide", "Oxygen"], 1],
    ["What is the term for the study of fungi?", ["Ichthyology", "Ornithology", "Mycology", "Entomology"], 2],
    ["Which part of the eye controls the amount of light entering?", ["Retina", "Cornea", "Iris", "Lens only"], 2],
    ["What is the value of sin(90°)?", ["-1", "0", "0.5", "1"], 3],
    ["Which CSS layout system is one-dimensional?", ["SVG", "Grid", "Canvas", "Flexbox"], 3],
    ["What is the hardest part of the human tooth?", ["Cementum", "Pulp", "Dentin", "Enamel"], 3],
    ["Which state of matter has a fixed volume but no fixed shape?", ["Gas", "Solid", "Liquid", "Plasma"], 2],
    ["Which cloud service model provides virtualized computing resources?", ["DNS", "PaaS only", "SaaS", "IaaS"], 3],
    ["What is the term for a sentence that asks a question?", ["Exclamatory", "Imperative", "Declarative", "Interrogative"], 3],
    ["Which molecule carries amino acids to ribosomes?", ["DNA", "mRNA", "tRNA", "ATP"], 2],
    ["What is the binary representation of decimal 10?", ["1001", "1010", "1110", "1100"], 1],
    ["Which statistical chart is best for showing parts of a whole?", ["Pie chart", "Line chart", "Box plot", "Scatter plot"], 0],
    ["What is the name of the point where two axes meet on a coordinate plane?", ["Vertex", "Origin", "Focus", "Centroid"], 1],
    ["Which ecosystem is dominated by grasses and few trees?", ["Tundra", "Coral reef", "Grassland", "Rainforest"], 2],
    ["Which term means a word formed from the first letters of a phrase?", ["Synonym", "Acronym", "Prefix", "Homophone"], 1],
    ["What is the common unit for measuring computer file size?", ["Meter", "Byte", "Gram", "Volt"], 1],
    ["Which geometry term describes lines that never meet?", ["Parallel", "Skew only", "Perpendicular", "Intersecting"], 0],
    ["What is the name for heat transfer through fluid motion?", ["Convection", "Radiation", "Reflection", "Conduction"], 0],
    ["Which nutrient is the body's main quick energy source?", ["Water", "Mineral", "Vitamin", "Carbohydrate"], 3],
    ["Which JavaScript method converts JSON text into an object?", ["Object.keys", "Array.map", "JSON.parse", "JSON.stringify"], 2],
    ["What is the solution to x in 3x = 21?", ["9", "6", "7", "8"], 2],
    ["Which ocean zone receives enough sunlight for photosynthesis?", ["Hadal zone", "Photic zone", "Benthic zone only", "Abyssal zone"], 1],
    ["Which term describes a reusable block of code?", ["Variable", "Literal", "Function", "Operator"], 2],
    ["What is the name of the imaginary line around Earth's middle?", ["Axis", "Meridian", "Tropic", "Equator"], 3],
    ["Which probability value is impossible?", ["1.5", "0", "0.5", "1"], 0],
    ["Which astronomical object is made mostly of ice, dust, and rock and can show a tail near the Sun?", ["Planet", "Comet", "Meteorite", "Asteroid only"], 1],
    ["What is the unit of work and energy?", ["Watt", "Ampere", "Joule", "Volt"], 2],
    ["Which cooking term means to briefly cook food in boiling water?", ["Grill", "Bake", "Blanch", "Roast"], 2]
  ]
};

const baseQuestions = Object.fromEntries(
  Object.entries(rawTriviaQuestions).map(([difficulty, questions]) => [
    difficulty,
    questions.map(([question, answers, correctIndex]) => ({ question, answers, correctIndex })),
  ]),
);

